chainloop-dev/chainloop

- .github/workflows/release.yaml
- .goreleaser.yml
The official installation script has been added to a public repository under a new location `https://docs.chainloop.dev/install.sh` https://github.com/chainloop-dev/docs/pull/76
This new script leverages publicly available GitHub releases and hence we do not need to push artifacts to Google Blob Storage anymore.
Closes #7
> chore(ci): use new installation script

- app/artifact-cas/Makefile
- app/artifact-cas/internal/tools.go
- app/controlplane/Makefile
- app/controlplane/internal/tools.go
- go.mod
- go.sum
We use [`wire`](https://github.com/google/wire/) for dependency injection but the CLI used to generate the code wasn't tracked in our go.mod. 
This caused an indirect dependency (subcommands) to disappear causing the build process to fail
> chore: track wire/cmd dependency (subcommands)

- internal/credentials/vault/keyval_test.go
Leverage actual `Vault` health check endpoint during testing instead of a TCP check on the exposed port.
Let's keep an eye if this fixes the problem.
Closes #11
> fix(tests): vault healthcheck improvements

- README.md
- internal/blobmanager/oci/backend.go
Add quickstart installation instructions to main readme file.
Refs #4
> docs: add installation quickstart

- .goreleaser.yml
- CONTRIBUTING.md
- README.md
* Rename project tagline
* Fix invalid instructions quote
> doc: update project tagline

- app/cli/cmd/workflow_contract_describe.go
- app/cli/internal/action/workflow_run_describe.go
- app/controlplane/internal/biz/attestation.go
- app/controlplane/internal/biz/integration.go
- app/controlplane/internal/biz/ocirepository.go
- app/controlplane/internal/biz/ocirepository_test.go
- app/controlplane/internal/biz/organization_integration_test.go
- app/controlplane/internal/service/attestation.go
- internal/attestation/crafter/crafter.go
- internal/blobmanager/oci/provider.go
- internal/blobmanager/oci/provider_test.go
- internal/credentials/aws/secretmanager.go
- internal/credentials/aws/secretmanager_test.go
- internal/credentials/credentials.go
- internal/credentials/credentials_test.go
- internal/credentials/mocks/Reader.go
- internal/credentials/mocks/ReaderWriter.go
- internal/credentials/mocks/Writer.go
- internal/credentials/vault/keyval.go
- internal/credentials/vault/keyval_test.go
Updates the credentials Reader/Writer Interface to have a single method regardless of the kind of payload stored. The responsibility of the marshalling type check is on the caller size. 
Closes #22
> refactor: consolidate credentials service interface

- app/cli/internal/action/artifact_upload.go
- internal/attestation/crafter/materials/artifact.go
- internal/attestation/crafter/materials/artifact_test.go
- internal/attestation/crafter/materials/cyclonedxjson.go
- internal/attestation/crafter/materials/cyclonedxjson_test.go
- internal/attestation/crafter/materials/spdxjson.go
- internal/attestation/crafter/materials/spdxjson_test.go
- internal/casclient/casclient.go
- internal/casclient/mocks/DownloaderUploader.go
- internal/casclient/mocks/Uploader.go
- internal/casclient/uploader.go
The CAS client will be used by the control-plane too and the upload input in such case is an io.Reader not a file.
This patch updates the Uploader interface and implementation accordingly. It also keeps the `UploadFile` method encapsulated in the casclient package since it's being used by two callers, the CLI action package and the attestation materials package.
Refs #2
> chore: decouple cas-client file upload

- app/controlplane/cmd/wire.go
- app/controlplane/cmd/wire_gen.go
- app/controlplane/internal/biz/errors.go
- app/controlplane/internal/biz/integration.go
- app/controlplane/internal/biz/integration/dependencytrack/dependencytrack.go
- app/controlplane/internal/biz/integration/dependencytrack/dependencytrack_test.go
- app/controlplane/internal/biz/integration/deptrack/deptrack.go
- app/controlplane/internal/biz/integration/integration.go
- app/controlplane/internal/biz/ocirepository.go
- app/controlplane/internal/biz/organization_integration_test.go
- app/controlplane/internal/biz/testhelpers/database.go
- app/controlplane/internal/biz/testhelpers/wire.go
- app/controlplane/internal/biz/testhelpers/wire_gen.go
- app/controlplane/internal/biz/workflowcontract.go
- app/controlplane/internal/biz/workflowrun.go
- app/controlplane/internal/integrations/dependencytrack/sbom.go
- app/controlplane/internal/service/attestation.go
- app/controlplane/internal/service/integration.go
- Decouple dependency-track code from the service layer and put it in its own package in the biz layer.
- The ultimate goal will be potentially merge /biz/integrations and /internal/integrations https://github.com/chainloop-dev/chainloop/issues/38 and this sets the stage for that.
The reason for all these changes is that next we are going to proceed with leveraging CAS instead of OCI directly for SBOM retrieval #2
> chore: encapsulate dependency-track biz code

- app/artifact-cas/internal/server/grpc.go
- app/artifact-cas/internal/server/grpc_test.go
- app/controlplane/cmd/wire.go
- app/controlplane/cmd/wire_gen.go
- app/controlplane/internal/biz/casclient.go
- app/controlplane/internal/biz/casclient_test.go
- app/controlplane/internal/biz/testhelpers/wire.go
- app/controlplane/internal/biz/testhelpers/wire_gen.go
- app/controlplane/internal/server/grpc.go
- app/controlplane/internal/server/http.go
- app/controlplane/internal/service/status.go
- internal/casclient/casclient.go
- internal/casclient/downloader.go
- internal/casclient/mocks/Downloader.go
- internal/casclient/mocks/DownloaderUploader.go
- internal/casclient/mocks/Uploader.go
Update the Control plane readiness probe API endpoint to take into account that the CAS configuration is correct and can in fact reach the CAS gRPC API server.
In other words, now it checks that it can reach the `statusz` endpoint of the configured CAS dependency.
Refs #2
> feat: CAS readiness probe support

- app/controlplane/internal/biz/casclient.go
- app/controlplane/internal/biz/casclient_test.go
Since last release we detected a memory leak that was affecting both the controlplane and the CAS https://github.com/chainloop-dev/chainloop/issues/68
After profiling, we noticed that the issue was that for CP<->CAS communication we create new connections each time that we **did not close**. The reason we use different connections each time is because each requests uses a different AUTH token.
This was leaving many GRPC connections alive causing memory creep. 
Before
After
Closes #68
> fix: close GRPC connection

- .github/workflows/package_chart.yaml
Add action that packages and pushes to OCI any new change in the deployment template (chart)
The Helm Chart once pushed can be installed via `helm install oci://ghcr.io/chainloop-dev/chart`
Refs #64
> feat(ci): package and push Helm Chart

- deployment/chainloop/Chart.yaml
- deployment/chainloop/values.yaml
The values.yaml file contained some invalid keys which produced the following output
```
W0417 16:34:53.726444 1867189 warnings.go:70] unknown field "spec.template.spec.containers[0].resources.cpu"                                      
W0417 16:34:53.726456 1867189 warnings.go:70] unknown field "spec.template.spec.containers[0].resources.memory"
W0417 16:34:53.740349 1867189 warnings.go:70] unknown field "spec.template.spec.containers[0].resources.cpu"
W0417 16:34:53.740363 1867189 warnings.go:70] unknown field "spec.template.spec.containers[0].resources.memory"  
```
refs #15
> fix: spurious compute requests

- deployment/chainloop/README.md
> docs(deployment): how to guides

- deployment/chainloop/README.md
> docs(deployment): gke monitoring

- app/cli/cmd/attestation_push.go
- app/cli/internal/action/attestation_push.go
- internal/attestation/renderer/chainloop.go
- internal/attestation/renderer/chainloop_test.go
- internal/attestation/renderer/renderer.go
- internal/attestation/renderer/testdata/attestation.output.v0.1.json
- internal/attestation/renderer/testdata/attestation.source.json
Adds some tests to make sure we don't break compatibility once we move to the new in-toto 1.0 resource descriptors. As a side effect of making the test stable I made some updates on the rendering order and default inputs. 
Refs #60
> fix: stabilize materials output

- app/controlplane/internal/service/ocirepository.go
- internal/ociauth/auth.go
During OCI registry save, we now
- Capture and returns validation error with plain message instead of generic 500 error
- Do not send an exception to sentry in that case 
Before (CLI output)
```
ERR server error
```
After
```
ERR invalid repository URI: repository can only contain the characters `abcdefghijklmnopqrstuvwxyz0123456789_-./`: [REPO_URI]
```
Closes #105
> chore(oci registry): show validation error during save

- .github/workflows/release.yaml
Wait until 0.9.0 has been released.
> chore(ci): bump chainloop version

- .github/workflows/release.yaml
- .goreleaser.yml
Update the installer to get a 2.x version of cosign
Next we'll trigger a release to get a rekor recorded (pun intended) release that will work in the current installation script 
Refs #116
> fix(ci): bump to cosign 2.0

- .github/workflows/release.yaml
Now that we have a new release that is recorded in the upstream transparent log, we can make sure we check the signature while installing chainloop
Closes #116
> chore(ci): enable cosign verification during chainloop installation

- go.mod
- go.sum
current released version of Kratos is preventing some important library upgrades https://github.com/chainloop-dev/chainloop/issues/127 and https://github.com/chainloop-dev/chainloop/pull/131
This patch brings a pre-release version of kratos (which final version I assume it will be available within weeks) but instead of waiting we can go ahead and unblock security patches.
> chore(deps): upgrade kratos

- app/controlplane/configs/config.devel.yaml
Choose the random port for HTTP Metrics in the development mode to fix the already-in-use port issues on OSX, closes #155
> fix: Choose the random port for HTTP Metrics in the development mode

- app/cli/cmd/available_integration.go
- app/cli/cmd/available_integration_describe.go
- app/cli/cmd/available_integration_list.go
- app/cli/cmd/output.go
- app/cli/cmd/registered_integration_add.go
- app/cli/cmd/registered_integration_add_deptrack.go
- app/cli/internal/action/available_integration_describe.go
- app/cli/internal/action/available_integration_list.go
- app/controlplane/extensions/core/dependencytrack/v1/extension.go
- app/controlplane/extensions/sdk/v1/fanout.go
List and describe the available integrations loaded in the controlplane.
NOTE: the jsonschema parser should be considered a first version. For example, it does not support nested schemas, which in fact we should prevent in the SDK itself. Or it does not show `oneofs`. This will get fixed in a future patch.
```console
$ go run main.go --insecure integration available ls                      
┌─────────────────┬─────────┐
│ ID              │ VERSION │
├─────────────────┼─────────┤
│ dependencytrack │ 1.0     │
└─────────────────┴─────────┘
```
Describe has two modes, a default mode that's meant for the user to udnerstand the inputs outputs 
```console
┌─────────────────┬─────────┐
│ ID              │ VERSION │
├─────────────────┼─────────┤
│ dependencytrack │ 1.0     │ …
```
> feat(cli): list/describe available integrations

- app/controlplane/extensions/core/smtp/v1/README.md
- app/controlplane/extensions/core/smtp/v1/extension.go
- app/controlplane/extensions/core/smtp/v1/extension_test.go
- app/controlplane/extensions/extensions.go
This is a new extension for sending emails via SMTP. This is still a very early experimental version focusing on validating the latest cutting-edge integrations framework.
The README file provides more information on how to use this extension.
closes #158
> feat: Added SMTP extension

- app/cli/cmd/attached_integration_add.go
- app/cli/cmd/attached_integration_list.go
- app/cli/cmd/registered_integration_add.go
- app/controlplane/extensions/core/dependencytrack/v1/extension.go
- app/controlplane/extensions/core/ociregistry/v1/README.md
- app/controlplane/extensions/core/ociregistry/v1/ociregistry.go
- app/controlplane/extensions/core/ociregistry/v1/ociregistry_test.go
- app/controlplane/extensions/core/smtp/v1/README.md
- app/controlplane/extensions/core/template/v1/extension.go
- app/controlplane/extensions/extensions.go
- internal/blobmanager/oci/backend.go
- internal/blobmanager/oci/backend_test.go
Create a generic OCI registry extension that works with any static credentials keypair. This means that's compatible with most provider except AWS' Elastic Container Registry (ECR)
It supports an optional `prefix` that can be added at attachment time.
Closes #168
> feat(extensions): OCI extension for attestation upload

- devel/README.md
Added the troubleshooting section and how to address the docker.sock issue on osx.
Closes #138
> docs: Added the troubleshooting section

- app/controlplane/extensions/core/ociregistry/v1/ociregistry.go
- app/controlplane/extensions/core/smtp/v1/extension.go
- app/controlplane/extensions/sdk/v1/fanout.go
- app/controlplane/internal/dispatcher/dispatcher.go
This patch makes two main changes
- Adds additional context to the execution by also injecting a decoded intoto statement and a normalized predicate, which then can be used to quickly access the env variables and materials.
- Sends this information always, even if the trigger was a material. 
Closes #174
> feat(extensions sdk): add statement and predicate context

- app/cli/cmd/attached_integration_list.go
- app/cli/cmd/available_integration_list.go
- app/controlplane/cmd/wire_gen.go
- app/controlplane/extensions/core/discord/v1/README.md
- app/controlplane/extensions/core/discord/v1/discord.go
- app/controlplane/extensions/core/discord/v1/discord_test.go
- app/controlplane/extensions/extensions.go
- app/controlplane/extensions/sdk/v1/fanout.go
- app/controlplane/internal/dispatcher/dispatcher.go
- app/controlplane/internal/dispatcher/dispatcher_test.go
- app/controlplane/internal/service/attestation.go
- internal/attestation/renderer/chainloop/chainloop.go
Extension that leverages Discord webhooks to send attestations. 
The inputs at registration time are a required webhook URL and an optional username override
```console
$ chainloop integration available describe --id discord-webhook
Available integrations ready to be used during registration
┌─────────────────┬─────────┬──────────────────────────────┐
│ ID              │ VERSION │ DESCRIPTION                  │
├─────────────────┼─────────┼──────────────────────────────┤
│ discord-webhook │ 0.1     │ Send attestations to Discord │
└─────────────────┴─────────┴──────────────────────────────┘
┌───────────────────────────────────────────────────────────────────────────────────────┐
│ Registration inputs                                                                   │ …
```
> feat(extensions): add Discord extension and additional metadata

- app/controlplane/internal/service/attestation.go
Closes #184 
Now the CLI shows `there was an issue retrieving the attestation` which was the original behavior, or "there is an attestation in progress"  
```console
$chainloop wf run describe --id 0c27d5d0-cc38-418c-a933-46b9ef02a532
┌───────────────────────────────────────────────────────┐
│ Workflow                                              │
├────────────────┬──────────────────────────────────────┤
│ ID             │ 548995cd-e64a-4f7f-bb6b-789f8fc07afb │
│ Name           │ test                                 │
│ Team           │                                      │
│ Project        │ baz                                  │
├────────────────┼──────────────────────────────────────┤
│ Workflow Run   │                                      │ …
```
> fix: nil pointer guard when no attestation is present

- app/controlplane/internal/biz/integration.go
During integration de-registration, now we just warn log instead of failing when a associated credential can't be deleted/found.
Closes #183
> fix(integration): do not fail if can't delete associate credentials

- .github/workflows/package_chart.yaml
There was a bug in the package-chart github action workflow file that wasn't limiting runs to only the main branch. Thanks @danlishka for bringing this up!
> fix(ci): package chart only on changes main branch

- app/controlplane/extensions/README.md
Improve some wording and moves the how to build an extension content to this file.
The reason for that move is so the template readme file can become an actual readme file template not a development guide.
refs #38
> docs(extensions): improve some wording

- app/controlplane/plugins/sdk/readme-generator/main.go
- docs/integrations.md
Link to the actual extension tree, not to the non-raw readme file. The later causes problems in docusaurus since it can not retrieve it.
refs #38
> chore(docs): update integrations links and code blocks

- docs/integrations.md
Applying @danlishka feedback from here https://github.com/chainloop-dev/docs/pull/130
> docs(integrations): fix typos

- app/controlplane/plugins/sdk/readme-generator/main.go
- docs/integrations.md
Fixes the table links.
Before I didn't notice about this issue because I could see the right link in the code and the missing `/` was sneaky. The problem was the user of `filepath.join`
Now I can point to Readme file as well so docusaurus will not complain
Refs #38
> fix(docs): links in integrations table

- app/controlplane/plugins/core/guac/v1/README.md
Updates guac readme guide to include video and follow the same styleguide and content in docs.chainloop.dev
refs #209
> feat(guac): add video to guide

- app/controlplane/plugins/core/discord-webhook/v1/discord.go
- app/controlplane/plugins/core/guac/v1/guac.go
- app/controlplane/plugins/core/slack-webhook/v1/README.md
- app/controlplane/plugins/core/slack-webhook/v1/slack_webhook.go
- app/controlplane/plugins/core/slack-webhook/v1/slack_webhook_test.go
- app/controlplane/plugins/core/template/v1/extension.go
- app/controlplane/plugins/plugins.go
- docs/integrations.md
> feat: Added Slack plugin

- go.mod
- go.sum
- internal/attestation/crafter/materials/spdxjson.go
Our previous code was parsing SPDX 2.2. This change updates the parsing library and relies on a generic json marshaller, compatible with the latest version. 
refs #210
> chore: generic support for SPDX 2.x

- Makefile
- app/artifact-cas/Makefile
- app/artifact-cas/internal/service/resource.go
- app/cli/main.go
- app/controlplane/Makefile
- common.mk
- internal/blobmanager/errors.go
- internal/blobmanager/oci/backend.go
- internal/blobmanager/oci/backend_test.go
Handles the fact that an image doesn't exist in the CAS instead of returning a generic error and notifying the exception manager. 
This patch also includes some makefile refactoring to check that some of the new tools required are in place.
> fix(cas): return 404 error if artifact does not exist

- .github/workflows/contracts/releases.cue
- .github/workflows/release.yaml
Fixes https://github.com/chainloop-dev/chainloop/actions/runs/5507743809/jobs/10038247997
The issue was that now we are also building plugin binaries. Then we iterate over them and try to add them as pieces of evidence. Such pieces of evidence are not in the contract (yet).
This patch basically will do a graceful recover and move on. The verification will happen at `att push` where we make sure the required materials are in place.
> fix(release): do not fail if we can not attest a material

- .goreleaser.yml
- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/controlplane/migrate-job.yaml
- deployment/chainloop/values.yaml
NOTE: This is needed because we've moved to a better database migration mechanism #221 and now the migration process is not automatic in the app but as part of the deployment process.
Updates our Helm Chart to perform database migrations. It's been implemented using helm hooks and kubernetes jobs as suggested [here](https://atlasgo.io/guides/deploying/helm). 
I've also seen [some Bitnami Charts](https://github.com/bitnami/charts/blob/f559fa746836bf63e86ae1fe5ddbca4d72d14b68/bitnami/kong/templates/migrate-job.yaml#L10) following the same pattern, so I'll be stick to hooks + jobs instead of init containers for now.
Example of job output for the initial import
```sql
$ k logs chainloop-controlplane-migrate-5vjw7 …
```
> feat(deployment): perform database migrations

- deployment/chainloop/README.md
Required to be able to import this readme in our docs system
> docs(deployment): make links absolute

- .github/workflows/test.yml
- .goreleaser.yml
Enable upx compression during build.
On my local tests there is a reduction of about half the size, for example
```sh
$ upx bin/control-plane
Ultimate Packer for eXecutables
Copyright (C) 1996 - 2023
UPX 4.0.2       Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 30th 2023
File size         Ratio      Format      Name
--------------------   ------   -----------   -----------
59908290 ->  28271904   47.19%   linux/amd64   control-plane           
```
The discord plugin size went to 1/4 of the size. 12MB to 3MB
> chore(ci): compress binaries

- .goreleaser.yml
- app/controlplane/Dockerfile.goreleaser
- app/controlplane/plugins/core/Makefile
- app/controlplane/plugins/core/dependency-track/v1/Makefile
- app/controlplane/plugins/core/dependency-track/v1/cmd/main.go
- app/controlplane/plugins/core/smtp/v1/Makefile
- app/controlplane/plugins/core/smtp/v1/cmd/main.go
Package `dependency-track` and `smtp` plugins in the upstream container image.
Refs #195
> chore(plugins): enable smtp and dependency-track

- .github/workflows/test.yml
It seems that the issue appears in the latest version of go. Pinning to the previous one until there is a fix upstream https://github.com/testcontainers/testcontainers-go/issues/1359
refs #255
> fix(ci): pin go version

- .goreleaser.yml
Revert compression due to #259 and segment fault.
We will revisit it for some linux binaries that seem to work fine.
> chore(ci): disable upx

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/values.yaml
New flag that allows enabling sslmode during database migration. This is required for PostgreSQL 15 on AWS RDS 
This is the effect of enabling the flag
```diff
--- /tmp/before.yaml    2023-07-25 11:34:46.356110212 +0200
+++ /tmp/after.yaml     2023-07-25 11:43:03.134694777 +0200
@@ -1203,6 +1203,6 @@
- migrate
- apply
- --url
-            - "postgres://chainloop:chainlooppwd@foo-postgresql:5432/chainloop-cp?sslmode=disable"
+            - "postgres://chainloop:chainlooppwd@foo-postgresql:5432/chainloop-cp"
- --dir
- file:///migrations
```
> feat(deployment): enable SSL during migration

- .github/workflows/test.yml
Run the migrations generation make target in the CI. That way we will detect any migration that has not been generated and or checked in yet.
refs #28
> chore(ci): check generated controlplane migrations

- app/controlplane/plugins/core/slack-webhook/v1/slack_webhook.go
We've noticed that some notifications are not rendering properly, and although it's not clear why some other do, we've detected that during the previous refactoring, the new line before the escape ticks were removed.
> fix(slack): add empty line before escape lines

- app/controlplane/internal/service/cascredential.go
this code makes `chainloop artifact upload|download` fail if the current cas backend is `inline`
- Uploads are not possible in inline cas backends since in such case, uploads only make sense in the context of an attestation.
- Downloads are not yet supported, they will eventually #248 but until then we handle it as an error.
Closes #265
> feat: handle inline backend upload/download 

- app/cli/cmd/attestation_status.go
- app/cli/internal/action/attestation_status.go
Updates the attestation summary table to 
- leverage vertical space
- Split value and digest
- Indicate the annotations associated with the materials, this is important in the context of #252, since it will be the way to show the user what annotations are mandatory.
Default behavior
```
$ chainloop attestation status
───────────────────┬──────────────────────────────────────┐
│ Initialized At    │ 28 Jul 23 15:14 UTC                  │
│ Workflow          │ 3e4ef02c-0f33-4248-84be-8a55ea2e3cb0 │
│ Name              │ only-sbom                            │
│ Team              │                                      │
│ Project           │ foo                                  │
│ Contract Revision │ 7 …
```
> feat(attestation): update status output

- app/controlplane/internal/dispatcher/dispatcher.go
If during the integrations dispatch process one of the integrations can't find the credentials external dependency, it gets skipped instead of failing the execution.
> fix(dispatcher): do not fail if credentials are missing

- app/controlplane/plugins/core/dependency-track/v1/extension.go
- app/controlplane/plugins/core/dependency-track/v1/extension_test.go
- docs/integrations.md
Enables annotations interpolation (#252) in the Dependency-Track plugin.
Now, during attachment, the project name can contain material annotations that will be resolved before pushing to the dep-track instance.
For example, let's say that you have the following contract with two SBOMs and a `component` annotation (note that the value of the annotation is set in the contract but it is also now possible to set it at runtime #281) 
```json
{
"schemaVersion":  "v1",
"materials":  [
{
"type":  "SBOM_CYCLONEDX_JSON",
"name":  "controlplane-sbom",
"annotations":  [
{
"name":  "component",
"value":  "controlplane"
}
]
},
{
"type":  "SBOM_CYCLONEDX_JSON",
"name":  "cas-sbom",
"annotations":  [
{
"name":  "component",
"value":  "cas"
}
]
}
]
}
```
This annotation can then be set during attachment. …
> feat(dependecy-track): interpolated project name

- app/controlplane/plugins/core/dependency-track/v1/extension.go
- app/controlplane/plugins/core/dependency-track/v1/extension_test.go
- internal/attestation/renderer/chainloop/chainloop.go
Allows leveraging global annotations in the dependency-track project name.
For example, let's assume we have the following contract with both material (called component) and global annotations (branch)
```json
cat /tmp/schema-old.json                        
{
"schemaVersion":  "v1",
"annotations":  [
{
"name":  "branch",
"value": "stable"
}
],
"materials":  [
{
"type":  "SBOM_CYCLONEDX_JSON",
"name":  "controlplane-sbom",
"annotations":  [
{
"name":  "component",
"value":  "controlplane"
}
]
},
{
"type":  "SBOM_CYCLONEDX_JSON",
"name":  "cas-sbom",
"annotations":  [
{
"name":  "component",
"value":  "cas"
}
]
}
]
}
```
You can now attach the dependency-track instance to leverage both types of annotations
```bash
$ chainloop integration attached add .... 
--opt …
```
> feat(dependency-track): support global annotations in project name

- deployment/chainloop/Chart.yaml
Note: our automated process actually failed for some reason https://github.com/chainloop-dev/chainloop/actions/runs/5714627160/job/15482450268 so I am triggering the release myself.
> chore: Bump Chart Version v0.15.0

- .github/workflows/contracts/releases.cue
Include annotations in the Chainloop release contract. Note that this PR should be landed and applied once the new release of Chainloop that contains annotations support is live.
refs #252
> chore(ci): update Chainloop contract

- app/controlplane/plugins/core/slack-webhook/v1/slack_webhook.go
- app/controlplane/plugins/sdk/v1/helpers.go
- app/controlplane/plugins/sdk/v1/helpers_test.go
- app/controlplane/plugins/sdk/v1/testdata/attestations/truncated.txt
Add render option to truncate the output table to a number of runes. A 4000 chars limit is then set to the Slack message to prevent #272 
The truncate is slightly smart since it leaves the footer where the command to get the attestation info stays intact.
Note: ideally, eventually, we should do custom markup for Slack using Slack blocks, but this feature at least prevents broken rendering in the case of overflow.
Closes #272
> feat(slack): truncate message

- deployment/chainloop/templates/controlplane/migrate-job.yaml
> fix(deployment): include cloud-sql auth proxy in migration job when needed

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/config.secret.yaml
https://github.com/chainloop-dev/chainloop/pull/294 introduced a change in the configuration which was assumed to be used in the next version of the helm Chart.
This code change has not been released yet so the Chart instead now contains the old and the new version so it works with both.
> fix(deployment): chart should work with old version of code

- app/controlplane/cmd/wire_gen.go
- app/controlplane/internal/biz/attestation.go
- app/controlplane/internal/biz/biz.go
- app/controlplane/internal/service/attestation.go
> feat(controlplane): upload attestation to CAS

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/controlplane/config.configmap.yaml
Updates the deployment to be able to leverage the features implemented here #307 
```diff
@@ -207,7 +207,7 @@                                                            
server:                                                                   
http:         
addr: 0.0.0.0:8000
-        timeout: 1s
+        timeout: 10s                                                          
external_url: http://cp.chainloop.dev
http_metrics:                                                           
addr: 0.0.0.0:5000                                                    
@@ -218,6 +218,7 @@                                                            
grpc:                                                                   
addr: test-chainloop-cas-api:80  
insecure: true
+      download_url: …
```
> feat(deployment): support downloading redirect

- app/artifact-cas/internal/service/download.go
Replaces `image not found` for `not found`
The culprit of this bug is that the underlying implementation was returning a 404 and the reason being that the OCI image is not found.
From the CAS API POV, we do not care about the implementation details but just that the artifact is not found.
Good catch @danlishka, for some reason I thought it was my browser interpreting the mimetype as image 🤦🏼
> fix(cas): not found error

- internal/credentials/credentials.go
- internal/credentials/vault/keyval.go
- internal/credentials/vault/keyval_test.go
> fix(vault): healthcheck didn't take into account the prefix

- deployment/chainloop/templates/cas/hpa.yaml
- deployment/chainloop/templates/controlplane/hpa.yaml
> feat(deployment): generate horizontal pod autoscaling proper version based on k8s version

- deployment/chainloop/templates/cas/config.configmap.yaml
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/templates/controlplane/config.configmap.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
- deployment/chainloop/values.yaml
The helm chart now allows to specify a sercret name where a TLS certificate and key are store. If specified, it mounts the secret in the pods and update the configuration to enable TLS on the servers.
```diff
@@ -180,6 +180,9 @@
addr: 0.0.0.0:8000
timeout: 1s
grpc:
+        tls_config:
+          certificate: /data/server-certs/tls.crt
+          private_key: /data/server-certs/tls.key
addr: 0.0.0.0:9000
timeout: 1s
http_metrics:
@@ -209,6 +212,9 @@
grpc:
addr: 0.0.0.0:9000
timeout: 10s
+        tls_config:
+          certificate: /data/server-certs/tls.crt
+          private_key: /data/server-certs/tls.key
cas_server:
grpc:
addr: foo-chainloop-cas-api:80
@@ -390,6 +396,8 @@
mountPath: "/tmp"
- name: gcp-secretmanager-serviceaccountkey
mountPath: /gcp-secrets
+            - name: …
```
> feat(deployment): allow to configure TLS certificate for gRPC servers

- .github/workflows/release.yaml
This CLI version contains showing the digest of the attestation #333, useful for sharing #263
> chore: bump Chainloop CLI version

- app/controlplane/internal/service/casredirect.go
This will show a `downloading` message when the download URL is put. 
This is useful to fix an issue we found when the OIDC roundtrip was not finishing.
> fix: show downloading message during redirect

- .github/workflows/release.yaml
This reverts commit af1fa6e9d67853672c138de5468ff9c9cbf72b09.
My bad, that release is no longer available 🤦🏼
> Revert "chore: bump Chainloop CLI version (#334)"

- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/controlplane/deployment.yaml
- deployment/chainloop/templates/controlplane/deployment_sqlproxy.yaml
- deployment/chainloop/templates/controlplane/migrate-job.yaml
- deployment/chainloop/templates/controlplane/service_sql-proxy.yaml
Refs https://github.com/chainloop-dev/chainloop/pull/325
> feat: deploy cloud-sql-proxy in its down deployment

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/cas/config.secret.yaml
- deployment/chainloop/templates/controlplane/config.secret.yaml
- deployment/chainloop/values.yaml
**Overview**:
This PR addresses the issue chainloop-dev/chainloop#104. It introduces a division in the Sentry configuration to make it distinct for each service. This change ensures that top-level configured helm charts will not render and provides guidance on correcting the issue.
**Additional Changes**:
- Adjustments have been made to the readme. The helm-generator has removed extraneous spaces and empty lines. This is for better consistency and clarity.
> feat: Split Sentry configuration for individual services

- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/release.yaml
- app/artifact-cas/Dockerfile
- app/artifact-cas/Dockerfile.goreleaser
- app/controlplane/Dockerfile
- app/controlplane/Dockerfile.goreleaser
Improve scorecard score by pinning pending dependencies.
> fix: add pinned dependencies

- README.md
We can improve it later on, it will also get better over time since it does average commits
> chore: add OpenSSF scorecard

- app/artifact-cas/cmd/main.go
- app/artifact-cas/configs/config.devel.yaml
- app/artifact-cas/internal/service/bytestream.go
- app/artifact-cas/internal/service/bytestream_test.go
- app/artifact-cas/internal/service/download.go
- app/artifact-cas/internal/service/service.go
- app/cli/cmd/casbackend.go
- app/cli/cmd/casbackend_add_azureblob.go
- app/cli/cmd/casbackend_update_azureblob.go
- app/controlplane/cmd/main.go
- app/controlplane/internal/biz/casbackend.go
- app/controlplane/internal/biz/casbackend_integration_test.go
- app/controlplane/internal/biz/casbackend_test.go
- app/controlplane/internal/biz/casmapping_integration_test.go
- app/controlplane/internal/biz/organization_integration_test.go
- app/controlplane/internal/biz/workflowrun_integration_test.go
- app/controlplane/internal/data/ent/casbackend/casbackend.go
- app/controlplane/internal/data/ent/migrate/schema.go
- app/controlplane/internal/service/casbackend.go
- deployment/chainloop/templates/cas/config.configmap.yaml
- go.mod
- go.sum
- internal/blobmanager/azureblob/backend.go
- internal/blobmanager/azureblob/provider.go
- internal/blobmanager/azureblob/provider_test.go
- internal/blobmanager/backend.go
- internal/blobmanager/oci/backend.go
- internal/blobmanager/oci/backend_test.go
- internal/robotaccount/cas/robotaccount_test.go
Adds support for Azure Blob Storage as Content Addressable Storage backend.
In practice this means:
Users can now onboard their Azure Storage Account with Chainloop
```sh
$ chainloop cas-backend add azure-blob \
--client-id [servicePrincipalID]
--client-secret [servicePrincipalSecret]
--tenant [Active directory tenant]\
--storage-account [Storage Account name]
--container [optional Storage account container]
```
once done, it will appear in your list of registered backends
```console
$ chainloop cas-backend ls
──────────────────────────────────────┬─────────────────────────────────────┬───────────┬─────────────────────────────────────┬───────────────┬─────────┐
│ ID                                   │ LOCATION                            │ PROVIDER  │ DESCRIPTION                         │ …
```
> feat(cas): Azure Blob Storage support

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/config.configmap.yaml
The previous PR added a regression in the Helm Chart that was preventing its render.
NOTE: the issue was due to editor auto-formatting
> fix(deployment): wrong labeling templating

- app/cli/api/attestation/v1/crafting_state.go
- app/cli/api/attestation/v1/crafting_state_test.go
- internal/attestation/renderer/chainloop/v01.go
- internal/attestation/renderer/chainloop/v02.go
Fixes #365
The issue was that we had a hardcoded list of material types to normalize and it was outside of the testing loop.
The issue was consistent when an user tried to use any new material type, such as the new `sarif` or `vex` types.
This code makes two things
- Change the normalization code to be less brittle and dynamic based on the structure of the material type
- Adds missing error handling
Example of successful attestation
```
┌────────────────────────────────────────────────────────────────────────────────────┐
│ Materials                                                                          │
├──────────┬─────────────────────────────────────────────────────────────────────────┤
│ Name     │ image                                                                   │
│ Type …
```
> fix(attestation): generic normalization function

- app/artifact-cas/configs/config.devel.yaml
- app/artifact-cas/internal/service/download.go
- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/config.configmap.yaml
The issue in fact is a misconfiguration in the helm Chart and only Azure Blob Storage is affected.
The reason Azure is the only affected is because in its implementation we in fact use the parent `context` which by default has a `timeout`. The OCI implementation doesn't use context (it should)
The reason it only affects the HTTP endpoint is because grpc downloads don't have timeouts, http one does.
Fixes #366
> fix: extend http download timeout

- app/artifact-cas/internal/service/bytestream.go
Context cancellation during upload chunk fills was not handled properly.
This code 
- Makes sure that having an error always returns regardless of the type
- Handles the grpc cancellation so we don't get cancellation exceptions
Fixes #377
> fix(cas): handle client cancellation

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/values.yaml
Update Helm Chart to support configuring Azure KeyVault, depends on #388 
This is the result of adding the following configuration to the values.yaml file
```yaml
secretsBackend:
backend: azureKeyVault
azureKeyVault:
tenantID: [REDACTED]
clientID: [REDACTED]
clientSecret: [REDACTED]
vaultURI: https://[REDACTED].vault.azure.net/
```
Closes #357
> feat(deployment): Azure KeyVault support

- internal/blobmanager/azureblob/backend.go
- internal/blobmanager/s3/backend.go
- internal/blobmanager/s3/backend_test.go
This change https://github.com/chainloop-dev/chainloop/pull/390/files?diff=split&w=0#r1360718603 introduced a regression in the Azure code.
The problem was that in Azure, we were returning a pointer to a custom error (instead of the error value), confusing `errors.As`.
This change makes sure we return always a concrete type and we leverage the already existing backend.isNotFound method.
> fix(azure): existing file regression

- app/artifact-cas/README.md
- app/controlplane/configs/samples/config.yaml
- deployment/chainloop/README.md
- deployment/chainloop/values.yaml
- devel/README.md
Update Helm Chart readme file with instructions on how to configure Azure Key Vault at deployment time.
Refs #376
> chore(docs): update Helm Chart readme with Azure KeyVault info

- app/artifact-cas/internal/server/grpc.go
- app/controlplane/internal/server/grpc.go
This patch enables an additional Prometheus histogram with the total time per request.
For example, upload times
```
grpc_server_handling_seconds_sum{grpc_method="Read",grpc_service="google.bytestream.ByteStream",grpc_type="server_stream"} 24.683958404000002
grpc_server_handling_seconds_count{grpc_method="Read",grpc_service="google.bytestream.ByteStream",grpc_type="server_stream"} 2
```
or client stream uploads
```
grpc_server_handling_seconds_sum{grpc_method="Write",grpc_service="google.bytestream.ByteStream",grpc_type="client_stream"} 10.418738306000002
grpc_server_handling_seconds_count{grpc_method="Write",grpc_service="google.bytestream.ByteStream",grpc_type="client_stream"} 4
```
This patch also tweaks the histogram buckets on the CAS case since those requests have different time …
> chore(api): enable request time histogram

- internal/attestation/renderer/chainloop/testdata/attestation.output-2.v0.2.json
- internal/attestation/renderer/chainloop/testdata/attestation.output.v0.2.json
- internal/attestation/renderer/chainloop/v02.go
Propagate material annotations to subject structs. This will enable enhanced ingestion upstream. 
In another patch, a similar feature #383 will be handled for our custom git head subject.
> feat(attestation): add annotations to subject materials

- .github/workflows/release.yaml
This new version of the CLI runs git attestations.
> chore(ci): bump chainloop CLI to v0.25.0

- app/controlplane/internal/biz/orginvitation.go
- app/controlplane/internal/biz/orginvitation_integration_test.go
This code swaps the order of the checks done during invitation, from
- Check that the `receiver` doesn't belong to the `org` already
- Check that the `sender` can invite to the `org`
to
- Check that the `sender` can invite to the `org`
- Check that the `receiver` doesn't belong to the `org` already
That way, a sender will not be able to know if a user belongs to an organization by trying emails/uuids. 
This is an unlikely case (you need to know orgs UUDIDS and email address to positively know that it belongs to the org) but in any case this patch solves that problem.
> fix(controlplane): bubble up authorization permission

- Makefile
- app/cli/cmd/workflow_create.go
This PR just removes some unwanted spaces from a message and from the makefile.
> chore: clear some unintended trailing spaces

- app/cli/internal/action/workflow_run_list.go
- app/cli/internal/action/workflow_run_list_test.go
The new runner type for jenkins job needs its entry to be displayed well:
> chore: display jenkins job type in runner column

- app/cli/cmd/workflow_workflow_run_describe.go
- app/cli/internal/action/workflow_run_describe.go
```sh
$ chainloop wf run describe --digest sha256:29da604ade4ddc9e35f675c7b7fc6355d0b381ca23fab5d1a0614a8ea10ea425 -o statement
```
```json
{
"type": "https://in-toto.io/Statement/v1",
"subject": [
{
"name": "chainloop.workflow.test",
"digest": {
"sha256": "053857d8d1976a3008d2ca35797021a40919dd441915b179a925e4b37015ccde"
}
},
{
"name": "git.head",
"digest": {
"sha1": "cb798c19caec6932684aa97e279318dc64265c98"
},
"annotations": {
"author.email": "miguel@chainloop.dev",
"author.name": "Miguel Martinez Trivino",
"date": "2023-11-09T10:40:17Z",
"message": "rebase\n\nSigned-off-by: Miguel Martinez Trivino \u003cmiguel@chainloop.dev\u003e\n",
"remotes": [
{
"name": "origin",
"url": "git@github.com:migmartri/chainloop.git"
},
{
"name": "upstream",
"url": …
```
> feat(cli): retrieve worklowRun by attestation digest

- app/cli/internal/action/artifact_upload.go
- internal/casclient/uploader.go
Gracefully handle empty files uploads.
Closes https://github.com/chainloop-dev/chainloop/issues/380
> fix(cli): handle empty files

- app/controlplane/internal/biz/errors.go
- app/controlplane/internal/biz/referrer.go
- app/controlplane/internal/biz/referrer_integration_test.go
- app/controlplane/internal/biz/referrer_test.go
- app/controlplane/internal/data/referrer.go
This PR 
- Improves the ingestion code to allow storing two referrers with the same digest but different kinds. it includes some refactoring too.
- Updates the retrieval code to return a well-known error that: 
- makes the API return a validation error instead of a server error
- shows actionable information to the user of what's available.
For example, now, on retrieval we get.
```
$ chainloop discover -d sha256:ebe2e6ffab93f4b2e2743d3557bd094427ea059adc78cfe2cd330a72f61731e8
ERR validation error: please provide the referrer kind: failed to get referrer: digest sha256:ebe2e6ffab93f4b2e2743d3557bd094427ea059adc78cfe2cd330a72f61731e8
present in two kinds ["SBOM_CYCLONEDX_JSON" "ARTIFACT"]
```
In a future patch, the user will be able to filter out by kind.
> feat(referrer): support same digest for two different kinds

- internal/attestation/crafter/runners/circleci_build.go
- internal/attestation/crafter/runners/circleci_build_test.go
Main issue:
https://github.com/chainloop-dev/chainloop/issues/433
I am removing the environment variable CIRCLE_PR_NUMBER from the required because it's set only in very specific scenarios. Everything else is working. I artificially set this env variable to make the runner work from within CircleCI and it worked just fine:
> fix(runner): remove optional env variable from the requirements

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/controlplane/config.configmap.yaml
- deployment/chainloop/values.yaml
Adds support to configuring, at deployment time, the organizations allowlist for our public index #441
```diff
helm template foo deployment/chainloop -f ~/Desktop/values.local.yaml > /tmp/after.yaml && diff -u /tmp/before.yaml /tmp/after.yaml
--- /tmp/before.yaml    2023-11-17 10:39:47.695002643 +0100
+++ /tmp/after.yaml     2023-11-17 11:09:51.669551058 +0100
@@ -232,6 +232,9 @@
insecure: true
download_url: /download
plugins_dir: /plugins
+    referrer_shared_index:
+      allowedOrgs: []
+      enabled: false
```
Closes #435
> deploy(referrers): add public index configuration

- app/controlplane/internal/biz/referrer.go
- app/controlplane/internal/biz/referrer_integration_test.go
digest `alg` can be different than `sha256`, i.e sha1 for a commit.
This removes a check we have in the API, ideally, we should run some validation that includes the sha1 format too.
> fix(referrer): remove sha256 digest validation

- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_status.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
- internal/attestation/crafter/runner.go
- internal/attestation/crafter/runners/azurepipeline.go
- internal/attestation/crafter/runners/azurepipeline_test.go
- internal/attestation/crafter/runners/circleci_build.go
- internal/attestation/crafter/runners/circleci_build_test.go
- internal/attestation/crafter/runners/generic.go
- internal/attestation/crafter/runners/generic_test.go
- internal/attestation/crafter/runners/githubaction.go
- internal/attestation/crafter/runners/githubaction_test.go
- internal/attestation/crafter/runners/gitlabpipeline.go
- internal/attestation/crafter/runners/gitlabpipeline_test.go
- internal/attestation/crafter/runners/jenkinsjob.go
- internal/attestation/crafter/runners/jenkinsjob_test.go
- internal/attestation/crafter/runners/runner.go
- internal/attestation/crafter/runners/runners.go
- internal/attestation/crafter/testdata/contracts/jenkins_with_env_vars.yaml
This PR fixes the following issue:
https://github.com/chainloop-dev/chainloop/issues/440
> feat(runner): allow for optional environment variables

- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_unit_test.go
Shows an error message instead of blocking the attestation
> WRN failed to list remotes error="branch config: invalid merge"
> fix(cli attestation): handle non-merged branches

- app/cli/cmd/organization_leave.go
This is a proposal to fix the following issue:
https://github.com/chainloop-dev/chainloop/issues/456
The rationale behind this is based on what @migmartri said in the issue, i.e.:
> it's likely that we'll move away from setting current in the backend and instead be the client who sets it
I think this could be a step in the right direction, because the limitation is happening in the CLI command only.
I also noticed that there are no tests for these implementations, and I think I understand why that is. I think for the moment we could rely on end-to-end, before merging this. Test:
https://pastebin.com/HeGXrewd
> feat(org): prevent from leaving current organization

- app/controlplane/internal/biz/robotaccount.go
- app/controlplane/internal/jwt/common.go
- app/controlplane/internal/jwt/robotaccount/robotaccount.go
- app/controlplane/internal/jwt/robotaccount/robotaccount_test.go
- app/controlplane/internal/jwt/user/user.go
- app/controlplane/internal/jwt/user/user_test.go
- app/controlplane/internal/service/auth.go
- app/controlplane/internal/usercontext/robotaccount_middleware.go
- app/controlplane/internal/usercontext/userorg_middleware.go
- app/controlplane/internal/usercontext/userorg_middleware_test.go
This patch updates the JWT generation/verification code used today for authentication and attestation (robot-accounts) to generate and verify respective custom `audience` values.
The reason for this change is in preparation for #453, where we'll be creating additional JWT tokens that are meant to be distinct from the existing authentication ones.
The changes are as follows 
The tokens result of `chainloop auth login` now have the audience `user-auth.chainloop`, existing tokens will fail to validate, but that's ok since they have 24 hours max validity.
These tokens now have `aud=attestations.chainloop` but during verification we still support its previous value. This is to maintain compatibility with robot-accounts that are already in place. New ones will have the right `audience`
> fix: enable JWT audience verification

- app/controlplane/internal/biz/referrer.go
Equivalent to https://github.com/chainloop-dev/chainloop/pull/447 but affecting the public referrer endpoint.
> fix(referrer): remove sha256 requirement

- app/controlplane/internal/biz/casmapping.go
- app/controlplane/internal/biz/casmapping_integration_test.go
- app/controlplane/internal/biz/referrer.go
- app/controlplane/internal/biz/referrer_integration_test.go
- app/controlplane/internal/service/cascredential.go
- app/controlplane/internal/service/casredirect.go
- app/controlplane/internal/service/context.go
- app/controlplane/internal/service/referrer.go
- app/controlplane/internal/service/service.go
- app/controlplane/internal/service/service_test.go
- app/controlplane/internal/usercontext/allowlist_middleware_test.go
- app/controlplane/internal/usercontext/apitoken_middleware.go
- app/controlplane/internal/usercontext/currentuser_middleware.go
In a previous patch we added support for API tokens #351, but these couldn't be used for download/upload artifacts to the CAS. 
This PR solves that by
- Update the cas-mapping lookup logic to accept the list of organizations directly, not just the user.
- Update the `service` endpoints to use either of those methods to lookup for the mapping.
Closes #463
> feat: allow upload/downloads using API token

- .github/workflows/release.yaml
Bump CHAINLOOP_VERSION to use the latest version of Chainloop CLI.
Refs #479
> chore(deps): Bump CHAINLOOP_VERSION to use latest Chainloop CLI

- .github/workflows/release.yaml
Bump anchore/sbom-action from v0.14.3 to v0.15.6 to use the latest version of syft.
Refs #479
> chore(deps): Bump the anchore/sbom-action version

- app/controlplane/internal/authz/authz.go
- app/controlplane/internal/authz/authz_test.go
- app/controlplane/internal/biz/testhelpers/database.go
- app/controlplane/internal/biz/testhelpers/wire.go
- app/controlplane/internal/biz/testhelpers/wire_gen.go
- go.mod
- go.sum
Adds a watcher that triggers the reload of the policies when any other casbin replica has injected/removed a policy in the DB. 
Fixes #483 
cc/ @fgallina
> fix(authZ): propagate new policies across replicas

- app/cli/cmd/attestation_add.go
- app/cli/cmd/attestation_init.go
- app/cli/cmd/attestation_push.go
- app/cli/cmd/attestation_reset.go
- app/cli/cmd/attestation_status.go
- app/cli/internal/action/action.go
- app/cli/internal/action/attestation_add.go
- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_reset.go
- app/cli/internal/action/attestation_status.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
- internal/attestation/crafter/statemanager/filesystem/filesystem.go
- internal/attestation/crafter/statemanager/filesystem/filesystem_test.go
- internal/attestation/crafter/statemanager/filesystem/testdata/state.json
- internal/attestation/crafter/statemanager/local/local.go
- internal/attestation/crafter/statemanager/statemanager.go
Modularizes the code that we have today that stores state in the filesystem behind a common interface.
This will allow us to easily implement remote state support.
refs https://github.com/chainloop-dev/chainloop/issues/494
> refactor(cli): modularize current state management code

- app/cli/cmd/attestation_add.go
- app/cli/cmd/attestation_init.go
- app/cli/cmd/attestation_push.go
- app/cli/cmd/attestation_reset.go
- app/cli/cmd/attestation_status.go
- app/cli/internal/action/attestation_add.go
- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_reset.go
- app/cli/internal/action/attestation_status.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
- internal/attestation/crafter/statemanager/filesystem/filesystem.go
- internal/attestation/crafter/statemanager/filesystem/filesystem_test.go
Makes the client-side attestation process context aware. This will fit well with the new remote state API #494
> chore(cli): make attestation cmds context aware

- app/cli/cmd/attestation_add.go
- app/cli/internal/action/action.go
- app/cli/internal/action/attestation_add.go
- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_reset.go
- app/cli/internal/action/attestation_status.go
- extras/dagger/main.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/materials/materials.go
- internal/attestation/crafter/materials/materials_test.go
- internal/attestation/crafter/materials/oci_image.go
- internal/ociauth/auth.go
This patch adds support to providing OCI credentials via command-line flags or env variables, that will be used to authenticate during `CONTAINER_IMAGE` attestations.
Before, `chain loop att add` was loading the default docker credentials stored in `~/.docker/config,` and although this is still the default behavior, now, optionally, the credentials can be explicitly set.
This is important because of our push to support stateless, encapsulated, attestation processes #501 
This is also a requirement to fix #511
> feat(attestation): explicit OCI credentials support

- extras/dagger/README.md
- extras/dagger/main.go
The dagger init command now supports receiving a git repository that can be used by chainloop to automatically gather information during the attestation process.
I've also added the `--revision` feature too
Refs #509
> feat(dagger): support attestation of git repositories

- app/cli/internal/action/attestation_init.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
- internal/attestation/crafter/runner.go
- internal/attestation/crafter/runners/azurepipeline.go
- internal/attestation/crafter/runners/azurepipeline_test.go
- internal/attestation/crafter/runners/circleci_build.go
- internal/attestation/crafter/runners/circleci_build_test.go
- internal/attestation/crafter/runners/daggerpipeline.go
- internal/attestation/crafter/runners/daggerpipeline_test.go
- internal/attestation/crafter/runners/generic.go
- internal/attestation/crafter/runners/generic_test.go
- internal/attestation/crafter/runners/githubaction.go
- internal/attestation/crafter/runners/githubaction_test.go
- internal/attestation/crafter/runners/gitlabpipeline.go
- internal/attestation/crafter/runners/gitlabpipeline_test.go
- internal/attestation/crafter/runners/jenkinsjob.go
- internal/attestation/crafter/runners/jenkinsjob_test.go
Decouple the detection from the enforcement of runner types.
Now that the CLI will
- detect the runner type
- check that's the expected one, if listed in the contract
- load the required information associated with that runner context.
Closes #515
> feat(cli): automatically discover runner context

- extras/dagger/README.md
- extras/dagger/main.go
Adds support to explicit OCI credentials during material addition. It leverages the changes performed here https://github.com/chainloop-dev/chainloop/pull/513
NOTE: This change should be held until a new release of the CLI is pushed
Closes #511
> feat(dagger): support explicit OCI credentials

- app/controlplane/internal/biz/organization.go
- app/controlplane/internal/data/organization.go
When updating an org, instead of returning a generic error, now the API returns a validation error if there is an org with the same name to the one we're trying to set
Closes #528
> fix(controlplane): handle org update duplicates

- app/controlplane/plugins/core/dependency-track/v1/README.md
- app/controlplane/plugins/core/dependency-track/v1/client/sbom.go
- app/controlplane/plugins/core/dependency-track/v1/client/sbom_test.go
- app/controlplane/plugins/core/dependency-track/v1/extension.go
- app/controlplane/plugins/core/dependency-track/v1/extension_test.go
- docs/integrations.md
For now just supporting parent ID, not name and version. Although I do think it would be useful to support project version as well as parent name and version, this way a workflow could be shared by several projects if the parent name/version could be read from annotations.
No testing for the HTTP submission to dependency-track yet, although I'm not sure the best way to approach that in Go.
closes #544
> feat(dependency-track): support parent ID for autocreate projects (#534)

- .github/workflows/test.yml
- app/controlplane/Makefile
- app/controlplane/internal/data/ent/migrate/migrations/20240303145130.sql
- app/controlplane/internal/data/ent/migrate/migrations/atlas.sum
This patch adds a migration that updates `workflowrun.contract_revision_used` to its contract  `revision`. 
Before
```sql
select "contract_revision_used","contract_revision_latest" from workflow_runs;
contract_revision_used | contract_revision_latest 
------------------------+--------------------------
0 |                        2
0 |                        2
0 |                        2
0 |                        1
0 |                        2
0 |                        2
0 |                        2
0 |                        2
0 |                        2
0 |                        2
0 |                        1
2 |                        2
```
after
```
--migration ran
UPDATE 11
select "contract_revision_used","contract_revision_latest" from workflow_runs;
contract_revision_used | …
```
> chore(db): update workflow_run revision used

- app/controlplane/api/controlplane/v1/org_invitation.proto
- app/controlplane/api/controlplane/v1/org_invitation_grpc.pb.go
- app/controlplane/api/gen/frontend/controlplane/v1/org_invitation.ts
- app/controlplane/internal/biz/orginvitation.go
- app/controlplane/internal/biz/orginvitation_integration_test.go
- app/controlplane/internal/data/orginvitation.go
- app/controlplane/internal/service/orginvitation.go
This is a continuation of #553 but this time applying to `listing` and `revocation`
Now that we are going to have `admin` users in the org, this change will allow us for each admin to be able to see the pending/sent invites in their org, and match it with a list of members in the future.
Refs #535
> chore(controlplane): continue invite system org scope

- app/controlplane/internal/authz/authz.go
#559 introduced a regression where did not allow a `viewer` to change organizations.
This patch fixes this plus enables such user role to also `leave` the org
> fix: allow viewers to change or leave the org

- app/cli/cmd/organization.go
This command is now under `org member` subcommand
> chore(cli): remove invitation from top-level org cmd

- .github/workflows/lint.yml
- Makefile
Temporarily disable the Go linter for the dagger module until it gets stabilized
> chore(ci): disable dagger linter

- extras/dagger/main.go
Creates a `Sync` method that forces the execution of the `DAG`. This is important so we can make sure `Init` doesn't wait until push to create an instance of a run in the controlplane for example.
This is a workaround at not being able to do
```
att, err := chainloop.Init(...).Sync(ctx)
```
which is what the Container/File/Directory core primitives can do.
More context here: https://discord.com/channels/707636530424053791/1215428709910188133/1216885885279146074
> feat(dagger): sync method

- app/controlplane/internal/biz/biz.go
- app/controlplane/internal/biz/casmapping_integration_test.go
- app/controlplane/internal/biz/integration_test.go
- app/controlplane/internal/biz/organization.go
- app/controlplane/internal/biz/organization_integration_test.go
- app/controlplane/internal/biz/organization_test.go
- app/controlplane/internal/biz/referrer_integration_test.go
- app/controlplane/internal/biz/workflow.go
- app/controlplane/internal/biz/workflow_integration_test.go
- app/controlplane/internal/biz/workflowcontract.go
- app/controlplane/internal/biz/workflowcontract_integration_test.go
- app/controlplane/internal/biz/workflowrun_integration_test.go
- app/controlplane/internal/data/ent/migrate/migrations/20240312102059.sql
- app/controlplane/internal/data/ent/migrate/migrations/atlas.sum
- app/controlplane/internal/data/ent/migrate/schema.go
- app/controlplane/internal/data/ent/schema/workflowcontract.go
- app/controlplane/internal/data/workflowcontract.go
- app/controlplane/internal/dispatcher/dispatcher_test.go
- app/controlplane/internal/service/workflowcontract.go
- DB: 
- requires the workflow contract name to be unique in the context of an organization
- updates the existing contract entries to be DNS1123 compatible
- biz: 
- the name must be a valid `DNS1123` value
- when we auto-create a contract with a name during workflow creation, we make sure it's unique
Closes https://github.com/chainloop-dev/chainloop/issues/600
> feat(controlplane): make contract-names unique and DNS1123 compatible

- app/controlplane/internal/biz/biz.go
- app/controlplane/internal/biz/casclient_test.go
- app/controlplane/internal/biz/casmapping_integration_test.go
- app/controlplane/internal/biz/workflow.go
- app/controlplane/internal/biz/workflow_integration_test.go
- app/controlplane/internal/biz/workflowcontract.go
- app/controlplane/internal/data/ent/migrate/migrations/20240312141340.sql
- app/controlplane/internal/data/ent/migrate/migrations/atlas.sum
- app/controlplane/internal/data/ent/migrate/schema.go
- app/controlplane/internal/data/ent/schema/workflow.go
- app/controlplane/internal/data/workflow.go
Similarly to #601 but applied to workflows, it
- Makes both workflow names and project RFC 1123 compliant
- Make sure that the workflow name is unique at the organization level
- migrates the existing workflow names and projects to meet 1
Closes #602
> feat(controlplane): unique workflow name and formatted project

- app/controlplane/internal/biz/workflow_integration_test.go
- app/controlplane/internal/biz/workflowcontract_integration_test.go
- app/controlplane/internal/data/ent/migrate/migrations/20240312141340.sql
- app/controlplane/internal/data/ent/migrate/migrations/20240313115221.sql
- app/controlplane/internal/data/ent/migrate/migrations/atlas.sum
- app/controlplane/internal/data/ent/migrate/schema.go
- app/controlplane/internal/data/ent/schema/workflow.go
- app/controlplane/internal/data/ent/schema/workflowcontract.go
Take into account the `deleted_at` column in the uniqueness constraint
Closes #612
> fix(controlplane): support soft-deleted items on name constraint

- .github/workflows/docs_deploy.yml
- Start sending metadata and evidence files to Chainloop again.
- Update GitHub Actions to the latest version.
refs #488
> Improving documentation deployment + adding Chainloop

- docs/docs/guides/dagger/README.md
- docs/docusaurus.config.js
Include the Dagger demo in our guide in the docs.
I've implemented it so it gets injected when you run
```
yarn run docusaurus download-remote-dagger-module
```
refs #501
> docs: add dagger demo

- app/controlplane/internal/authz/authz.go
This patch enables `viewers` to access the new `Workflow.View` API endpoint introduced here #32 
I do not think this patch will require a re-release since we do not use this endpoint yet in the CLI.
Before
```
grpcurl --plaintext -H "authorization: Bearer $TOKEN" -d '{"id": "429a9b9e-63cf-44b9-aa8f-27cdd6775e23" }' localhost:9000 controlplane.v1.WorkflowService.View
ERROR:
Code: PermissionDenied
```
After
```
grpcurl --plaintext -H "authorization: Bearer $TOKEN" -d '{"id": "429a9b9e-63cf-44b9-aa8f-27cdd6775e23" }' localhost:9000 controlplane.v1.WorkflowService.View
ERROR:
Code: NotFound
```
> fix(authz): add read permissions in workflow.View

- .chainloop.yml
- .github/workflows/docs_deploy.yml
Fix the GitHub workflow for deploying the Chainloop documentation. There was a missing .chainloop.yml file and the robot account token used during the Chainloop init stage was incorrect. Please note that we use a remote-state approach and that the chainloop init and push actions occur in separate jobs.
> fix(docs-release) Fixed docs release and chainloop integration

- app/controlplane/internal/service/apitoken.go
- app/controlplane/internal/service/attestation.go
- app/controlplane/internal/service/attestationstate.go
- app/controlplane/internal/service/casbackend.go
- app/controlplane/internal/service/cascredential.go
- app/controlplane/internal/service/casredirect.go
- app/controlplane/internal/service/context.go
- app/controlplane/internal/service/integration.go
- app/controlplane/internal/service/organization.go
- app/controlplane/internal/service/orginvitation.go
- app/controlplane/internal/service/orgmetric.go
- app/controlplane/internal/service/referrer.go
- app/controlplane/internal/service/robotaccount.go
- app/controlplane/internal/service/service.go
- app/controlplane/internal/service/user.go
- app/controlplane/internal/service/workflow.go
- app/controlplane/internal/service/workflowcontract.go
- app/controlplane/internal/service/workflowrun.go
Gracefully handle context.Canceled error. This patch also makes sure all the error in the API are properly handled. NOTE: this will be moved to a middleware later on.
Closes #627
> chore(api): handle context.Canceled error

- app/controlplane/internal/data/workflowcontract.go
Properly return 404 errors when you try to update a contract that doesn't exist. 
This is done by the service/biz layer that will check if the data layer returned any contract object. The previous code didn't do it, that's fixed now.
> fix(controlplane): handle not-found contract on update

- app/controlplane/internal/biz/attestation.go
- app/controlplane/internal/biz/casmapping_integration_test.go
- app/controlplane/internal/biz/workflowrun.go
- app/controlplane/internal/biz/workflowrun_integration_test.go
- app/controlplane/internal/service/attestation.go
This patch makes sure that the digest of the attestation is always present. Before, only for the attestations that were stored in the CAS that was the case.
> feat(controlplane): always store the digest of the attestation

- .github/workflows/release.yaml
cosign <2.2.0 [stopped working](https://twitter.com/projectsigstore/status/1769392922707788070) requiring a version bump
> chore(ci): bump cosign version on release process

- app/cli/cmd/workflow_create.go
When a contract was provided, its name was incorrect, not matching our new DNS1123 requiremnet
> fix: auto-create contract

- docs/docs/reference/operator/api-tokens.mdx
Document API tokens in the operator reference section
> docs: document API tokens

- common.mk
While working in #687, we noticed that atlas releases have been changed recently, forcing users to download them from their release server. `go install` doesn't work anymore, since it won't include some code that it's indeed included in the binary release, for example, the `ent://` schema handler. 
More information can be found in this issue https://github.com/ariga/atlas/issues/2388, explaining why `atlas` binary cannot be built from source anymore.
Also note that this install script performs a `sudo` command to install `atlas` in `/usr/local/bin`. I haven't found a workaround for it, so from now on, running `make init` will require escalating privileges to copy the files.
fixes #687
> fix(makefile): fixes atlas installation by using its own install script

- README.md
- docs/docs/reference/operator/contract.mdx
This PR updates the documentation so it states Chainloop now supports HELM_CHART file type as new material.
Refers to #684
> feat(docs): Update documentation to reflect the HELM_CHART material type

- .github/workflows/package_chart.yaml
This PR allows to attest the generated Helm Chart of Chainloop as part of the package process of the Helm Chart.
> feat(ci): Attest Chainloop Helm Chart on every release

- .github/workflows/scorecards.yml
This PR adds chainloop CLI to scorecards workflows to attest SARIF results.
Closes #706
> feat(ci): Adds chainloop to scorecards pipeline

- .github/workflows/docs_deploy.yml
This PR leverages the changes introduced in https://github.com/chainloop-dev/labs/pull/6 so all needed git repository information is being retrieved before the attestation init is being done.
Closes #705
> feat(docs-deploy): Bump version of chainloop action to perform checkout before init

- .github/workflows/scorecards.yml
Scorecard action is complaining about top level env vars in a production workflow, aka: a workflow running on the default branch on the repository.
```bash
2024/04/26 11:42:48 error sending scorecard results to webapp: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: scorecard job contains env vars, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."}
2024/04/26 11:42:48 retrying in 1s...
2024/04/26 11:42:50 error sending scorecard results to webapp: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: scorecard job contains env vars, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."}
2024/04/26 11:42:50 retrying in 3s... …
```
> fix(scorecards): Move env variable to individual steps

- .github/workflows/docs_deploy.yml
Bumps the version of chainloop action and introduces a dependency from `deploy_docs` to `chainloop_init`.
Refers to #705
> fix(ci): Bump version of chainloop action

- .chainloop.yml
- .github/workflows/scorecards.yml
Leverages the use of chainloop action rather the manual steps so it complies with ossf/scorecard constraints.
> fix(ci): Use chainloop action on scorecard pipeline

- .github/workflows/package_chart.yaml
This PR adds the container images present in the chart tor the Chainloop attestation, during the package phase. This way, Chainloop will add the proper references to the Release phase in the Trust Hub, providing a full end to end view of the release->package->deployment proocess.
Package contract has been updated accordingly.
> feat(package): attest container images in helm package gh action

- app/controlplane/internal/biz/referrer.go
- app/controlplane/internal/biz/referrer_integration_test.go
- app/controlplane/internal/biz/referrer_test.go
makes sure that each node in the graph points back to the attestation. Not only the ones that are `subjects` of the attestations, but all materials or subjects.
Closes #703
> feat(referrer): store backlinks unconditionally

- app/cli/cmd/workflow_workflow_run_list.go
- app/cli/internal/action/workflow_run_list.go
- app/cli/internal/action/workflow_run_list_test.go
Added a status flag with the possible values that are verified on the `actions` package. Passing the flag works as expected:
Ref: #718 
```
$chainloop wf workflow-run ls --status FAILED
┌──────────────────────────────────────┬────────────────────────────────┬───────┬─────────────────────┬────────┐
│ ID                                   │ WORKFLOW                       │ STATE │ CREATED AT          │ RUNNER │
├──────────────────────────────────────┼────────────────────────────────┼───────┼─────────────────────┼────────┤
│ 56220bdc-5e28-4e92-b955-c8ffa25cca6f │ chainloop/chainloop-codeql     │ error │ 29 Apr 24 08:28 UTC │ GitHub │
│ d21220ae-907f-40af-99ac-0d88af1636e7 │ chainloop/chainloop-codeql     │ error │ 29 Apr 24 08:10 UTC │ GitHub │
│ ab3ea91e-f1b9-4a24-ba06-34c3cf8c6bf4 │ …
```
> feat(cli): Workflow run can receive a status flag

- app/controlplane/internal/biz/apitoken.go
This PR adds to the list of available policies of an apitoken the listing of `WorkflowRuns`.
Tests are covering the case where the apitoken should have all default tokens when created.
Closes #717
> feat(apitoken): Adds workflow run list policy to default apitoken policies

- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_unit_test.go
In some cases, like the case of Gitlab, the CI will inject a remote with some temporary credentials to pull from the private repositories. This meant that the attestations had those temporary credentials in it as part of the `git.head` object in the attestation.
This patch updates the attestation cli to make sure the URI is sanitized before being ingested.
> fix(cli): sanitize remote url

- app/cli/cmd/artifact_download.go
- app/cli/internal/action/artifact_download.go
This PR allows the user to pass a `--output` to `artifact download` command to specify the output.
This work in different modes:
- Passing an actual filename to to the flag to override the custom name:
```bash
$ chainloop artifact download --digest sha256:a614bb8b24252994a821476bdac82bba822461468b092c196e68a3db297bc6bd --path /tmp/artifacts --output myfile.txt
INF API token provided to the command line
INF downloading file name=myfile.txt to=/tmp/artifacts/myfile.txt
99.96% [#################.] [2.80KB in 224.154ms; 12.49KB/s] ...
... done! [2.80KB in 251ms; 11.13KB/s]
$ ls -l /tmp/artifacts
total 8
-rw-r--r--  1 javirln  wheel  2800 Apr 29 17:30 myfile.txt
```
- Sending the output to a pipe:
```bash
$ chainloop artifact download --digest …
```
> feat(cli): Allow to pass --output flag to artifact download

- app/cli/cmd/attestation_push.go
- app/cli/internal/action/attestation_push.go
This patch implements the json output for the att push command. This output includes the envelope in string format and its digest.
note that the default output is kept the same for compatibility reasons.  
default view (not changed)
```
chainloop att push
{
"payloadType": "application/vnd.in-toto+json",
"payload": "eyJfdHlwZSI6Imh0dHBzOi8vaW4tdG90by5pby9TdGF0ZW1lbnQvdjEiLCJzdWJqZWN0IjpbeyJuYW1lIjoiY2hhaW5sb29wLndvcmtmbG93LnRlc3QyIiwiZGlnZXN0Ijp7InNoYTI1NiI6ImIzM2MyMmIxYWE2YjQ5YWQzNDVmMDZlZGQyODhiMDdkZDQ0YmM2NTBjMzc2NGZjN2UwYzRhNGJiZDdmZTJhODMifX0seyJuYW1lIjoiZ2l0LmhlYWQiLCJkaWdlc3QiOnsic2hhMSI6IjM1MTBkZDE1YzJiYTRmMWFkMDk0YjVlNTI3ZjNjYTAxNjVhNjk2MDAifSwiYW5ub3RhdGlvbnMiOnsiYXV0aG9yLmVtYWlsIjoibWlndWVsQGNoYWlubG9vcC5kZXYiLCJhdXRob3IubmFtZSI6Ik1pZ3VlbCBNYXJ0aW5leiBUcml2aW5v …
```
> feat(cli): add json output to attestation push

- .github/workflows/sync_contracts.yml
This PR makes use of the new GitHub workflow for reusable sync of chainloop contracts.
> feat(ci): Use reusable workflow for sync contracts

- .github/workflows/sync_contracts.yml
This PR makes the sync of chainloop contracts to only run when changes are on `.github/workflows/contracts`.
> fix(ci): Only run contract sync on changes in contracts path

- .github/workflows/release.yaml
This PR removes the constraint of only parsing amd64 binaries and instead, look for both arm64 and amd64 to comply with the new contract version introduced https://github.com/chainloop-dev/chainloop/pull/741
Locally tested:
`$ cat 'goreleaser.json' | jq -r '.[] | select(.type=="Binary" and .goos=="linux") | { "name": "\(.extra.ID)-\(.goos)-\(.goarch)", "path":"\(.path)"} '`
```json
{
"name": "artifact-cas-linux-amd64",
"path": "dist/artifact-cas_linux_amd64_v1/artifact-cas"
}
{
"name": "control-plane-linux-amd64",
"path": "dist/control-plane_linux_amd64_v1/control-plane"
}
{
"name": "chainloop-plugin-discord-webhook-linux-amd64",
"path": "dist/chainloop-plugin-discord-webhook_linux_amd64_v1/chainloop-plugin-discord-webhook"
}
{
"name": "chainloop-plugin-smtp-linux-amd64",
"path": …
```
> feat(ci): Update release pipeline to include all architecture binaries

- app/controlplane/internal/authz/authz.go
This PR adds a new resource type `attestation` with three new permissions for: `create, read and list`. Additionally it create a new permissions for `workflow` resource, `create`.
The addition to the default policy list for API Tokens and to the server URL mapping will come in a different PR.
Refs #752
> feat(policies): Add attestation as new resource type and workflow create permission

- .github/workflows/codeql.yml
- .github/workflows/package_chart.yaml
- .github/workflows/release.yaml
- docs/docs/getting-started/attestation-crafting.md
- docs/examples/ci-workflows/github.yaml
- extras/dagger/main.go
Bump the version of Chainloop used in our pipelines and in the dagger module.
The latest version of our CLI has support for recording container images tags
> chore(ci): bump chainloop CLI version

- app/controlplane/internal/authz/authz.go
Restore a policy that was wronly removed in a previous merge.
refs #761
> fix(chainloop): add missing policy

- docs/examples/contracts/csaf/contract.yaml
Updates de documentation examples with how CSAF profiles can be added to a Chainloop contract.
> chore(docs): Add CSAF contract example

- app/controlplane/internal/authz/authz.go
Viewer roles couldn't use `GetDownloadURL`
> fix(authz): allow viewer to download artifacts

- app/cli/cmd/attestation.go
- app/cli/cmd/errors.go
- app/cli/cmd/root.go
- docs/docs/getting-started/attestation-crafting.md
- docs/docs/reference/operator/api-tokens.mdx
This PR consolidates `CHAINLOOP_API_TOKEN` and `CHAINLOOP_ROBOT_ACCOUNT` into `CHAINLOOP_TOKEN` on attestations commands it is from:
```bash
$ export CHAINLOOP_ROBOT_ACCOUNT=deadbeef
$ chainloop attestation init ...
```
To
```bash
$ export CHAINLOOP_TOKEN=deadbeef
$ chainloop attestation init ...
```
Or
```bash
$ chainloop attestation init --token deadbeaf
```
> refactor(cli): Consolidates API Token and Robot Account into Token on attestations

- .github/workflows/package_chart.yaml
This PR leverages the resolvable workflow on Chainloop labs ([link](https://github.com/chainloop-dev/labs/blob/main/.github/workflows/chainloop_onboard.yml)) that onboards a new Workflow created from the context of the GitHub Action, if it does not exist.
Additionally, it uses a global API Token to perform all steps in the attestation process.
Refs https://github.com/chainloop-dev/platform/issues/630
> feat(ci): Use reusable workflow creation on Helm package

- app/cli/cmd/root.go
- app/cli/cmd/root_test.go
Parse the stored authentication token to know what kind of user is using the CLI.
This is a best effort approach.
Refs: #780
> feat(authentication): Parse auth token on root command

- app/controlplane/internal/biz/workflowrun.go
- app/controlplane/internal/data/workflowrun.go
- app/controlplane/internal/service/attestation.go
Makes sure to load the workflow from the three possible contexts always scoped for the current organization in the auth.
The three contexts are, 
- the workflow_id in the robot-account
- the workflow_name in the parameter in `init`
- the runID in the rest of the subsequent calls
Closes #783
> fix(attestations): support attestations workflow for API_TOKENS

- app/controlplane/internal/authz/authz.go
- app/controlplane/internal/biz/apitoken.go
This PR allows to invoke `chainloop wf create` without passing the flag `--skip-robot-account-create` when using API tokens to authenticate:
```
✗ go run app/cli/main.go --insecure --token $TOKEN wf create --name my-wf --project my-proj
INF API token provided to the command line
┌──────────────────────────────────────┬───────────┬─────────┬─────────────────────┬────────┬─────────────────┐
│ ID                                   │ NAME      │ PROJECT │ CREATED AT          │ RUNNER │ LAST RUN STATUS │
├──────────────────────────────────────┼───────────┼─────────┼─────────────────────┼────────┼─────────────────┤
│ 0c76d9d6-d056-4ca9-84be-fb4d1202af24 │ sdfsdffs2 │ asdfs   │ 16 May 24 14:17 UTC │        │                 │ …
```
> feat(api-tokens): Allow API TOKENs to create robot accounts

- app/cli/cmd/workflow_workflow_run_describe.go
This is a simple PR to fix the failure reason value shown in the table view.
```
✗ go run app/cli/main.go --insecure wf run describe --id 6f88410e-77d0-4dc3-90f3-add091381f8b
┌───────────────────────────────────────────────────────┐
│ Workflow                                              │
├────────────────┬──────────────────────────────────────┤
│ ID             │ 5fba63eb-e410-4546-baf2-99702b3bc0f0 │
│ Name           │ new-workflow                         │
│ Team           │                                      │
│ Project        │ my-project                           │
├────────────────┼──────────────────────────────────────┤
│ Workflow Run   │                                      │
├────────────────┼──────────────────────────────────────┤
│ ID …
```
> fix(CLI): fix correct failure reason in table view

- app/cli/internal/action/attestation_init.go
- app/controlplane/internal/service/attestation.go
- app/controlplane/internal/usercontext/apitoken_middleware.go
- app/controlplane/internal/usercontext/robotaccount_middleware.go
This code improves the user feedback by returning an error when the user is using a robot-account-based attestation and a workflow-name at the same time.
I do it by refactoring a little bit the code to explicitly check the kind of authentication is received and handle both cases. Note that I required to do a change in the CLI too so send the `name` only if only the user provided it.
API token auth missing name
```
go run main.go --insecure att init --replace                         
ERR rpc error: code = InvalidArgument desc = when using an API Token, workflow name is required as parameter
```
using ROBOT account with name
```
go run main.go --insecure att init --replace --workflow-name fo
ERR rpc error: code = InvalidArgument desc = workflow name is not compatible with robot-account …
```
> feat(attestations): handle authentication combinations

- docs/docs/getting-started/installation.md
The version shown in the instructions is very old and can confused people. It's best to not to show the version but indicate how to find it.
refs #792
> docs: remove hardcoded CLI version

- app/controlplane/internal/biz/apitoken.go
- app/controlplane/internal/jwt/apitoken/apitoken.go
- app/controlplane/internal/jwt/apitoken/apitoken_test.go
- app/controlplane/internal/usercontext/apitoken_middleware.go
- app/controlplane/internal/usercontext/attjwtmiddleware/attmiddleware.go
The generated API JWT token didn't contain the organization ID in it, which made it non-consistent with the robot-account token.
This patch a) adds the organization to the token and b) makes sure that the middleware does the proper parsing 
refs #780
> chore: add organizationID to API token

- app/cli/cmd/attestation_init.go
- app/cli/cmd/attestation_push.go
- app/cli/cmd/attestation_status.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_status.go
This PR improves the way `att push` result is shown. It uses now the status action logic (in `full` mode) before running the actual push to gather all the information from the current attestation.
```
✗ go run app/cli/main.go --insecure --token $TOKEN att push --key ./cosign.key
Enter password for private key:
│ Initialized At    │ 17 May 24 11:11 UTC                  │
│ Attestation ID    │ efb770a4-203f-4bba-9310-50272e39de26 │
│ Name              │ mywf                                 │
│ Team              │                                      │
│ Project           │ myproj                               │
│ …
```
> feat(cli): improve attestation push result in table format

- .github/workflows/release.yaml
- .goreleaser.yml
- app/cli/Makefile
- app/cli/cmd/root.go
- app/cli/cmd/root_test.go
- app/cli/internal/telemetry/posthog/posthog.go
- app/cli/internal/telemetry/telemetry.go
- app/cli/main.go
- docs/docs/reference/operator/cli-telemetry.mdx
This PR creates a new implementation of a Tracker client based on Posthog.
Users can deactivate telemetry by setting the env variable `DO_NOT_TRACK=1`, it follows the convention at: https://consoledonottrack.com/
Information being tracked:
- System information (OS, ARCH)
- Command ran
- CI Runner information if detected
- CLI version
- Hashed Control Plane URL
- Anonymous device ID
- User and Organization if logged in
Refs: #780
> feat(posthog): Add Telemetry client Posthog

- app/cli/cmd/root.go
Handles a `nil` client when running the build of the code outside of goreleaser.
Refs #809
> fix: handle posthog nil client

- app/cli/cmd/attestation_push.go
Show digest in stdout instead of stderr, so that command output doesn't break.
Fixes #805
> fix(cli): show digest in stdout in att push command

- docs/docusaurus.config.js
This is a cleanup of gtag leftovers as the posthog exchanges its functionality
> chore(docs): remove gtag preset option

- app/cli/cmd/attestation_add.go
- app/cli/internal/action/attestation_add.go
- app/controlplane/api/workflowcontract/v1/crafting_schema_validations.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
This patch ease the addition of new materials to an attestation by enabling by default the auto discovery of materials' kind. If the material is not on the contract nor a specific kind is flagged, the CLI will try to match the material with any of the registered kinds.
**Please note this is a best effort.**
Example of usage. Given the following contract:
```bash
$ chainloop --insecure attestation init --replace --workflow-name wf-test
INF Attestation initialized! now you can check its status or add materials to it
│ Initialized At    │ 22 May 24 13:38 UTC                  │
│ Attestation ID    │ 583553ef-d051-4c41-aec4-a4cdd725bf89 │ …
```
> feat(attestation): Allow the auto discovery of material's kind

- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
- internal/attestation/crafter/materials/materials.go
This patch creates a base error for the `uploadAndCraft` method that can be used to determine errors during the upload of and artifact.
This is needed for cases where the incoming material is detected correctly but the error happens when trying to upload it to a CAS.
A part from being added to the debug sequence is returned to the user as follows:
```bash
$ chainloop --insecure attestation add --value ./internal/attestation/crafter/materials/testdata/sbom.cyclonedx.json --debug | pbcopy
DBG Telemetry enabled, to disable it use DO_NOT_TRACK=1
DBG loading state state=file:///var/folders/ct/h8h0pjcd6q180cnxqhykjv3c0000gn/T/chainloop-attestation.tmp.json
DBG loaded state state=file:///var/folders/ct/h8h0pjcd6q180cnxqhykjv3c0000gn/T/chainloop-attestation.tmp.j …
```
> fix(craft): Wrap upload and craft errors to raise errors

- .github/workflows/sync_contracts.yml
This patch changes the pointer to the environment variable to use a `CHAINLOOP API TOKEN`.
Old token will be removed once this PR is merged.
Refs #785
> feat(sync-contract): Change pointer of env variable to use CHAINLOOP API TOKEN

- .github/workflows/github_release.yaml
- .github/workflows/release.yaml
This patch uses changes introduced in https://github.com/chainloop-dev/chainloop/pull/820 to auto discover materials based on the GitHub releases' assets.
Changes:
- Uses the workflow chainloop-vault-release
- Rename the file from `github_release` to `release`
- Attests everything included on the GitHub Release
Refs #785
> feat(action): Create new action to consume GitHub releases

- .github/workflows/release.yaml
This patch injects to a GitHub release the attestation URL to inspect the attestation that release represents.
For demo purposes we see how the v0.88.1 is updated with a link to Chainloop's attestation.
Refs #785 
Closes https://github.com/chainloop-dev/chainloop/issues/787
> feat(workflows): Include attestation URL to release workflow

- app/controlplane/internal/usercontext/apitoken_middleware.go
I was silently getting a "context deadline exceeded" error but it was being reported as a "error extracting organization from APIToken". This will improve it for easier debugging:
```
✗ go run app/cli/main.go --insecure --token $TOKEN att init --replace --workflow-name mywf
ERR rpc error: code = DeadlineExceeded desc = error extracting organization from APIToken: error retrieving the API token: finding token: getting APIToken: context deadline exceeded
exit status 1
```
Refs #840
> chore(chainloop): embed error in when org ID cannot be retrieved

- .github/workflows/release.yaml
This patch adds back the the attestation for all three container images.
It additionally sets a condition to not add the Chainloop Attestation URL if the release notes has it already.
> fix(release-workflow): Add back container images for attestation

- docs/docs/guides/deployment/hydra-oauth2/hydra-oauth2.mdx
This patch adds documentation regarding the configuration needed to use Ory Hydra as OAuth2 provider.
Closes https://github.com/chainloop-dev/chainloop/issues/829
> feat(docs): Document Ory Hydra as OAuth2 provider

- app/cli/internal/telemetry/posthog/posthog.go
- extras/dagger/main.go
The issue with Dagger pipelines was that there was a bug in the condition when machine_id was nil. 
machineID can not be set in a dagger pipeline since it's run in a scratch container
```
failed to get machine ID: machineid: machineid: open /etc/machine-id: no such file or directory
```
note, this will not be taken into effect until we do a new release AND update the dagger module to use the updated container image
> fix: do not fail telemetry on containers

- app/controlplane/internal/biz/referrer_integration_test.go
- app/controlplane/internal/data/referrer.go
The discovery endpoint now returns the list of references sorted by createdAt in descending order. This sets the stone to add pagination in the future.
```diff
diff -u /tmp/before.json /tmp/after.json                  
--- /tmp/before.json    2024-05-29 15:55:06.872510711 +0200
+++ /tmp/after.json     2024-05-29 15:54:51.387947393 +0200
@@ -6,11 +6,11 @@
"createdAt": "2024-05-29T13:53:00.822503Z",
"references": [
{
-         "digest": "sha256:8dc72d0b36f95ffd76cddd31205d3c167695eb1f4c9f415ddc6a6c8a32bc7fff",
+         "digest": "sha256:999089a5c4fe4c08c7ab28e8f7cc5a70b89fb1ccb6ec1425d459f055c570fa3e",
"kind": "ATTESTATION",
"downloadable": true,
"public": false,
-         "createdAt": "2024-05-29T13:53:20.398237Z",
+         "createdAt": "2024-05-29T13:53:00.817285Z",
"references": [], …
```
> feat(discovery): return latest entries

- .github/workflows/build_and_package.yaml
- docs/docs/getting-started/attestation-crafting.md
- docs/examples/ci-workflows/github.yaml
It seems that fetch-depth=0 is the opposite of what I thought it did.
From https://github.com/actions/checkout
> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set fetch-depth: 0 to fetch all history for all branches and tags. Refer [here](https://docs.github.com/actions/using-workflows/events-that-trigger-workflows) to learn which commit $GITHUB_SHA points to for different events.
> chore(ci): change fetch modality

- docs/docs/guides/github-releases/github-releases.md
This patch adds a guide on how to use the GitHub Releases reusable workflow to attest GitHub Releases, automatically.
Closes https://github.com/chainloop-dev/chainloop/issues/849
> feat(docs): Add information about reusable workflow

- .github/workflows/build_and_package.yaml
This patch fixes out goreleaser is casted into a file by using `jq`.
Refs #785
> fix(workflow): Replace quoting

- .github/workflows/release.yaml
This reverts commit b92d97f360ec6c6cbd4e5de0a06e1367a341f278.
Until a solution is found for the GitHub reusable workflow.
> Revert "feat(workflows): Integrate GitHub Release reusable workflow (#851)

- app/controlplane/internal/biz/biz.go
- app/controlplane/internal/biz/signing.go
- app/controlplane/internal/biz/signing_test.go
- go.mod
- go.sum
This is the first of a set of PRs to implement keyless signing in chainloop vault and CLI.
This PR focuses on the implementation of the signing use case. The use case receives a certificate request and signs it with a configured certificate authority. It uses some of the Sigstore logic for this purpose.
> feat(keyless): signing use case

- app/cli/cmd/workflow_workflow_run_list.go
This patch ensures that if a --status filter flag is passed to `workflow run ls` it receives a valid value.
Tested locally as:
```bash
$ chainloop --insecure  wf run list --status RANDOM --workflow $WORKFLOW_ID -o json
INF API token provided to the command line
ERR invalid status "RANDOM", please chose one of: [SUCCEEDED FAILED EXPIRED CANCELLED INITIALIZED]
```
```bash
$ chainloop --insecure  wf run list --status FAILED --workflow $WORKFLOW_ID -o json
INF API token provided to the command line
[
{
"id": "177a8e15-0075-4ada-a96c-0c4b5447ef44",
"state": "error",
"createdAt": "2024-05-16T13:41:52.229947Z",
"finishedAt": "2024-05-16T13:42:05.9596Z",
"workflow": {
"name": "wf-test",
"id": …
```
> feat(workflow-run): Ensure not invalid status is passed to CLI

- docs/static/install.sh
The problem was that `sha256sum` on Alpine does not recognize the following options: `--ignore-missing`, `--quiet `. More info in the #587 issue.
```
sha256sum: unrecognized option '--ignore-missing'
BusyBox v1.36.1 (2024-05-23 13:45:30 UTC) multi-call binary.
Usage: sha256sum [-c[sw]] [FILE]...
Print or check SHA256 checksums
-c	Check sums against list in FILEs
-s	Don't output anything, status code shows success
-w	Warn about improperly formatted checksum lines
```
I have tested this change on OS X, Alpine (chainguard/bash), and Ubuntu (node:latest).
> fix(install.sh): Make install.sh work on Alpine, fixes #587

- app/controlplane/cmd/wire_gen.go
- app/controlplane/internal/service/attestationstate.go
- app/controlplane/internal/service/service.go
This patch fixes the attestation state service by inspecting the workflowRunID from the requests and comparing them with the `orgID`.
This issue was preventing the use of `--remote-state` flag on the `attestation` command. Tests performed locally:
Attestation init passing the `workflow-name` because we are using an API token
```bash
$ chainloop --insecure attestation init --replace --workflow-name wf-test --remote-state
INF Attestation initialized! now you can check its status or add materials to it
│ Initialized At    │ 03 Jun 24 17:50 UTC                  │
│ Attestation ID    │ 311ccbf5-9dc9-4bc0-ab78-e55c9f4521a3 │
│ Name …
```
> fix(remoteattestations): Allow API tokens to work with remote state

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/controlplane/config.secret.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
- deployment/chainloop/templates/controlplane/file_ca.secret.yaml
- deployment/chainloop/values.yaml
This PR adds the secrets and configuration to support keyless signing in the K8s deployment.
Before and after applying keyless configuration in values.yaml
```diff
--- before.yaml	2024-06-04 19:01:52
+++ after.yaml	2024-06-04 19:02:02
@@ -129,6 +129,12 @@
generated_jws_hmac_secret: "REDACTED"
stringData:
+  fileca.secret.yaml: |
+    certificate_authority:
+      file_ca:
+        cert_path: "/ca_secrets/file_ca.cert"
+        key_path:  "/ca_secrets/file_ca.key"
+        key_pass: "REDACTED"
data:
database:
@@ -156,6 +162,24 @@
cas_robot_account_private_key_path: "/secrets/cas.private.key"
---
+# Source: chainloop/templates/controlplane/file_ca.secret.yaml
+apiVersion: v1
+kind: Secret
+metadata:
+  name: test-chainloop-controlplane-keyless-file-ca
+  labels:
+ …
```
> feat(keyless): add keyless config to deployment template

- docs/docusaurus.config.js
This patch adds the cookie consent script which should display the cookie consent banner at the bottom of the page. `autoBlock=on` should prevent other scripts to load cookies until being accepted
> feat(docs): add cookie consent script

- docs/docs/getting-started/attestation-crafting.md
- docs/docs/guides/dagger/README.md
- docs/docs/guides/dependency-track/dependency-track.mdx
- docs/docs/guides/guac/guac.mdx
- docs/docs/how-does-it-work/how-does-it-work.mdx
- docs/docs/intro/intro.mdx
- docs/docusaurus.config.js
This patch add `nocookie` to youtube links, this way we want to prevent youtube from using cookies for advertising and gathering information about the user in our docs page.
> feat(docs): update youtube video links to use privacy mode

- internal/attestation/renderer/renderer_test.go
This PR adds a regression test to prevent https://github.com/chainloop-dev/chainloop/pull/881 from happening again. 
The test checks that the rendered envelope follows the correct format, by verifying its signature. It also includes a simulation of the bug.
refs #865
> test(keyless): tests for renderer

- extras/dagger/README.md
- extras/dagger/main.go
This patch allows Dagger users to not pass `--name` when attesting materials and can leave that work to Chainloop to figure out the material kind even if the material does not belong to the target contract.
Example adding a generic artifact without `--name`:
```bash
$ dagger call -m . init --token env:CHAINLOOP_TOKEN --workflow-name dagger-wf add-file-evidence --path ./CONTRIBUTING.md push --key file:./cosign.key --passphrase env:COSIGN_PASSWORD
│ Initialized At    │ 05 Jun 24 06:31 UTC                  │
│ Attestation ID    │ f6ca9154-4c0b-48ac-9387-ae83cc194692 │
│ Name              │ dagger-wf                            │
│ Team              │ founding …
```
> feat(dagger): Allow auto discovery of materials

- extras/dagger/main.go
This patch modifies the behavior of the push command on dagger so the signing `--key` and --passphrase` are optional and the `--workflow-name`, required.
Example using the keyless feature:
```bash
$ dagger call -m . init --token env:CHAINLOOP_TOKEN --workflow-name dagger-wf add-file-evidence --path ./README.md push
│ Initialized At    │ 05 Jun 24 13:08 UTC                  │
│ Attestation ID    │ 82cf6e71-d212-4d58-b77c-adfd28d77ea2 │
│ Name              │ dagger-wf                            │
│ Team              │ founding                             │
│ Project           │ core                                 │
│ Contract Revision │ 5 …
```
> feat(dagger): Make signing keys optional and workflow-name required

- .github/workflows/build_and_package.yaml
- .github/workflows/codeql.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/package_chart.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecards.yml
- .github/workflows/sync_contracts.yml
This patch drops support for Chainloop Robot Accounts in favor of API Tokens by using the env variable `CHAINLOOP_TOKEN`. It additionally performs the following changes:
- Bump version of Chainloop CLI to ensure latest compatibility
- Bump reusable workflows to their latest version available on Chainloop's labs
> feat(workflows-chainloop): Consolidates robot accounts into API token

- app/cli/cmd/root.go
To prevent unexpected credentials overrides in the case the user has previously logged in explicitly but has an env variable, the system will not give priority to the user authentication instead and will show a warning message.
In addition to that, the credentials load logic has been improved to being able to detect when credentials are explicitly set vs loaded from env variables, and notify the user accordingly. 
Token provided
```
chainloop wf ls --token $T
INF API token provided to the command line
...
```
with env var instead CHAINLOOP_TOKEN=foobar
```
chainloop wf ls           
WRN Both user credentials and $CHAINLOOP_TOKEN set. Ignoring $CHAINLOOP_TOKEN.
...
```
refs #891
> fix: load chainloop_token gracefully if auth login has happened before

- .github/workflows/codeql.yml
This patch adds missing `--workflow-name` on codeql workflow.
> fix(workflows-chainloop): Add missing --workflow-name on codeql

- docs/docs/intro/intro.mdx
- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
When I did the upgrade to 3.x I overlooked a couple of requirements from their [migration guide](https://docusaurus.io/docs/migration/v3)
- I missed upgrading all the dependencies `@mdx-js/react` and `prism-react-renderer`.
- I missed that the theme now loads via esmodules  
After the fix, we have now properly configured code blocks (with copy button cc/ @jiparis) and attention banners.
> NOTE: the rest of the updates in the dependencies is just because I upgraded to the latest version of docusaurus 
closes #904
> fix(docs): fix code-blocks, theme and admonitions

- app/cli/cmd/organization_apitoken_create.go
This patch adds an additional output flag value `token` to the `api-token create` command that outputs just the raw API token.
This is useful for automation and one-liner quickstart
```
export CHAINLOOP_TOKEN=$(chainlooop org api-token create --name quickstart -o token)
```
refs #891
> feat: raw token output in CLI

- app/cli/internal/action/attestation_push.go
Fixes a rendering output issue from the CLI that was causing problems when dumping the output to a variable.
It's been fixed by removing some manual rendering we used to do about the payload and instead leverage the native rendering of the json marshaller. The reason this was different in the past is because the default output was a formatted json output, now it's not the case anymore.
```
go run main.go att init --name test --replace                                  
INF Attestation initialized! now you can check its status or add materials to it
│ Initialized At    │ 06 Jun 24 09:44 UTC                  │
│ Attestation ID    │ 27c34933-3e64-4ad2-b12a-42d202e6b737 │
│ …
```
> fix(cli): do not double render the envelope on attestation push

- .github/workflows/build_and_package.yaml
This patch adds a missing `--workflow-name` on the attestation init on for the `build and package` workflow.
Refs: #891
> fix(workflows-build-and-package): Add missing workflow-name

- docs/docs/getting-started/attestation-crafting.md
- docs/docs/getting-started/workflow-definition.mdx
- docs/docs/guides/dagger/README.md
- docs/docs/guides/dependency-track/dependency-track.mdx
- docs/docs/guides/github-releases/github-releases.md
- docs/docs/guides/sbom-management/sbom-management.mdx
- docs/docs/quickstart.md
- docs/docs/reference/operator/api-tokens.mdx
- docs/examples/ci-workflows/github.yaml
- docs/examples/ci-workflows/gitlab.yaml
- removes Robot-account references
- assumes that all attestations processes now are performed using API_TOKENS which require passing a `name`
- minor improvements, and fixes
refs #891
> docs: remove RA references

- app/cli/internal/action/attestation_add.go
- app/controlplane/internal/service/attestation.go
When running an attestation in dry-mode, we should not upload files either and hence we do not need to ask for the cas-backend information to the server.
This PR makes sure that the controlplane `GetUploadCreds` is only called if regular attestation mode is engaged.
fixes #926
> fix(attestation): do not load cas-backend on dry-mode

- app/cli/cmd/attestation_status.go
`--full` flag in `chainloop att status` was not working anymore. It was always rendering the table without values
> fix(cli): show full output

- app/cli/cmd/attestation_init.go
- app/cli/cmd/attestation_status.go
- internal/attestation/crafter/api/attestation/v1/crafting_state_validations.go
- internal/attestation/crafter/crafter.go
There was a problem while trying to `att push` an attestation that was initialized in `dry-run` mode. The validation error was
```
ERR invalid crafting state: validation error:
- attestation.workflow.organization: value length must be at least 1 character [string.min_len]
```
This patch skips that schema validation when running in `dry-run` mode since in this mode it's know to not to be fully complete.
refs #796
> fix(attestation): push on dry-run

- app/artifact-cas/Dockerfile.goreleaser
- app/cli/Dockerfile.goreleaser
- app/controlplane/Dockerfile.goreleaser
- app/controlplane/Dockerfile.migrations
builds all our container images indicating a non-root user `1001`
Next, we can release these images and give them a try in our helm chart, which will probably require some changes to pick the right usercontext
refs #936
> build images with username

- app/controlplane/Dockerfile.migrations
Fixes the permissions of the `atlas` binary. Before it was 001 which didn't work in openshift by default. Now it has a regular read only permission across the board.
Tested in openshift 4.15
Fixes #922 
cc/ @hanygirgis
> fix: make migrations work in openshift

- deployment/chainloop/templates/controlplane/config.secret.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
Move controlplane init container connection string to a secret instead of loading it from an env var. 
```diff
diff -u /tmp/before.yaml /tmp/after.yaml                                   
--- /tmp/before.yaml    2024-06-15 22:15:13.698002272 +0200
+++ /tmp/after.yaml     2024-06-15 22:17:10.401682053 +0200
@@ -333,7 +333,8 @@
type: Opaque
data:
-  generated_jws_hmac_secret: "dTRzWGpnQzkwMQ=="
+  generated_jws_hmac_secret: "OFp2dThPc0E5cQ=="
+  db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQGNoYWlubG9vcC1wb3N0Z3Jlc3FsOjU0MzIvY2hhaW5sb29wLWNwP3NzbG1vZGU9ZGlzYWJsZQ=="
stringData:
data:
@@ -357,7 +358,7 @@
-      generated_jws_hmac_secret: "u4sXjgC901"
+      generated_jws_hmac_secret: "8Zvu8OsA9q"
cas_robot_account_private_key_path: …
```
> feat(deployment): move init-container connection string

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/controlplane/customcas.secret.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
- deployment/chainloop/values.yaml
Add support to providing custom CAs available during TLS verification by the application HTTP clients.
Example of applying this change and adding a custom CA
- Will create a secret
- Will mount it in a default system path understood by golang's crypto library https://go.dev/src/crypto/x509/root_linux.go
I've tested it locally pointing my OIDC server to an nginx with a TLS certificate provided by the [staging certificate](https://letsencrypt.org/docs/staging-environment/) from let's encrypt. 
Closes https://github.com/chainloop-dev/chainloop/issues/956
```diff
---
+# Source: chainloop/templates/controlplane/customcas.secret.yaml
+apiVersion: v1
+kind: Secret
+metadata:
+  name: chainloop-2-controlplane-custom-cas
+  labels:
+    app.kubernetes.io/name: chainloop
+    helm.sh/chart: …
```
> feat(deployment): support custom CAs

- app/cli/cmd/workflow_workflow_run_describe.go
- app/cli/cmd/workflow_workflow_run_describe_test.go
This PR implements the `payload-pae` output format to obtain the PAE-encoded payload for easier verification:
```
go run app/cli/main.go --insecure wf run describe --digest sha256:8e0bb3ce5b2aa98fb1aaab2cb9e8ba8015e9802d2a6d0ddb75aa09a96750bc85  --output payload-pae > payload.pae.txt
```
payload.pae.txt would look like:
```
DSSEv1 28 application/vnd.in-toto+json 1414 {"_type":"https://in-toto.io/Statement/v1","subject" ...
```
Then, it can be easily matched against the signature with Cosign:
```
cosign -d verify-blob --signature sig.txt --insecure-ignore-tlog --key cosign.pub payload.pae.txt
```
Closes #968
> feat(cli): output format to export PAE-encoded payload

- app/controlplane/internal/server/grpc.go
```
grpcurl --plaintext -H "authorization: Bearer $TOKEN"  localhost:9000  controlplane.v1.UserService.ListMemberships
{
}
```
```
go run main.go --insecure org ls -o json                                                                          
[]
```
> fix: return empty list of memberships instead of error

- app/controlplane/internal/server/grpc.go
- app/controlplane/internal/usercontext/allowlist_middleware.go
AllowList middleware was not working on orgCreate endpoint since it was skipped in the parent selector.
This PR makes sure the allowList middleware uses it's on selector that's just limited to login and delete account
> fix(allowlist): run in most of the routes

- app/controlplane/internal/server/grpc.go
- app/controlplane/internal/service/context.go
This patch allows users to delete their accounts even if they don't belong to any organization.
Closes #998
> fix(auth): Allow users to delete account even without org

- app/artifact-cas/internal/server/grpc_test.go
- app/artifact-cas/internal/service/bytestream.go
- app/artifact-cas/internal/service/bytestream_test.go
- app/controlplane/internal/service/attestation.go
- app/controlplane/internal/service/cascredential.go
- app/controlplane/internal/service/casredirect.go
- app/controlplane/pkg/biz/cascredentials.go
- internal/robotaccount/cas/robotaccount.go
- internal/robotaccount/cas/robotaccount_test.go
We now make sure that the uploads (both from attestation or from `artifacts upload`) are restricted by the cas-backend size.
This is done by injecting the maxSizebytes in the JWT used to communicate with the cas-backend proxy. Then the proxy uses this value during the upload and continuously check for overflows during the reception of the chunk. 
If it goes over the limit, it rejects the upload.
```
2024-06-19T23:15:11.925+0200    DEBUG   {"component": "service", "msg": "upload chunk received", "digest": "49bc20df15e412a64472421e13fe86ff1c5165e18b2afccf160d4dc19fe68a14", "currentSize": 104857600, "maxSize": 104857600, "chunkSize": 1048576}
2024-06-19T23:15:11.926+0200    ERROR   {"component": "service", "msg": "max size of upload exceeded: current=105906176, max=104857600"}
``` 
closes …
> feat: upload size server-size validation

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/values.yaml
This patch allows users to configure the `externalURL` of the chart and adds the option of not relaying on the ingress/svc.
Adding the value in custom `values.yaml` file:
```
development: true
controlplane:
auth:
oidc:
url: http://chainloop-dex:5556/dex
clientID: chainloop-dev
clientSecret: REDACTED
externalURL: http://random-instance.com
```
Produces the following changes:
```diff
index c3d1213..65bcbd5 100644
--- a/old.yml	
+++ b/new.yml	
@@ -331,11 +331,11 @@ metadata:
app.kubernetes.io/part-of: chainloop
app.kubernetes.io/component: controlplane
type: Opaque
data:
-  generated_jws_hmac_secret: "cldaRE5nOE84Tw=="
+  generated_jws_hmac_secret: "aG5majRmZU9yZA=="
db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQGNoYWlubG9vcC1wb3N0Z3Jlc3FsOjU0 …
```
> feat(chart): Allow configuration of externalURL on values.yaml

- docs/docs/getting-started/attestation-crafting.md
- docs/docs/quickstart.md
- docs/docs/reference/attestations.md
This patch updates the documentation to include a section for contract-less and auto-discovery of materials.
Resulting page is the following, download for a better inspection:
Closes #901
> feat(docs): Update documenttion for contract-less and auto-discovery

- docs/docs/faq.md
- docs/docs/reference/operator/cli-telemetry.mdx
This patch documents the telemetry endpoint used by the CLI so users have and understanding in case they ran into problems.
Closes #1007
> feat(docs): Document telemetry endpoint

- extras/dagger/go.mod
- extras/dagger/go.sum
Bumps version of indirect dependency:
```bash
$ go get -u github.com/vektah/gqlparser/v2
go: upgraded github.com/vektah/gqlparser/v2 v2.5.11 => v2.5.16
```
> chore(go.mod): Update gqlparser from 2.5.11 => 2.5.16

- app/controlplane/internal/service/status.go
Expose error message in StatusZ endpoint to help with troubleshooting the connection to CAS
```
2024-06-24T11:03:05.175+0200    ERROR   {"kind": "server", "component": "grpc", "operation": "/controlplane.v1.StatusService/Statusz", "args": "readiness:true", "code": 503, "reason": "CAS_NOT_READY", "stack": "error: code = 503 reason = CAS_NOT_READY message = contacting API to ge
t status: rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority\" metadata = map[] cause = <nil>", "latency": 0.016060832}
```
> feat(api): show error message

- app/cli/cmd/output.go
- app/cli/cmd/workflow_create.go
- app/cli/cmd/workflow_describe.go
- app/cli/cmd/workflow_list.go
Before
```
go run main.go --insecure wf describe --name sfooobar -o json
[
{
"name": "sfooobar",
"id": "6d3e8897-e979-4086-9f2e-c7905ed34e2f",
"team": "",
"project": "bar",
"createdAt": "2024-06-22T21:03:32.71815Z",
"runsCount": 0,
"contractID": "69e8a312-030e-4692-b20f-f8c16c34f54f",
"contractRevisionLatest": 1,
"public": false
}
]
```
After
```
$ go run main.go --insecure wf describe --name sfooobar -o json           
{
"name": "sfooobar",
"id": "6d3e8897-e979-4086-9f2e-c7905ed34e2f",
"team": "",
"project": "bar",
"createdAt": "2024-06-22T21:03:32.71815Z",
"runsCount": 0,
"contractID": "69e8a312-030e-4692-b20f-f8c16c34f54f",
"contractRevisionLatest": 1,
"public": false
}
```
Closes #1014
> fix(cli): show wf output as json object instead of array

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/controlplane/config.configmap.yaml
Automatically configure the CP->CAS communication to be secure if TLS settings are set in CAS.
```diff
@@ -463,7 +463,7 @@                                                   
cas_server:                                                      
grpc:                                                          
addr: chainloop-2-cas-api:80
-      insecure: true                                                 
+      insecure: false                                                
download_url: /download                                        
plugins_dir: /plugins                                            
referrer_shared_index:     
```
Closes https://github.com/chainloop-dev/chainloop/issues/1018
> feat(chart): configure CP-CAS TLS flag

- docs/docs/reference/signing.md
This is a documentation page for our currently supported signing and verification methods.
> feat(docs): document signing methods

- app/cli/cmd/auth_login.go
This patch fixes a bug that made `xdg-open` not to return error and hence not triggering the headless login process
> fix(cli): wait for the command to finish

- app/cli/cmd/organization_leave.go
- app/cli/cmd/organization_list.go
- app/cli/cmd/organization_set.go
org leave and set now uses `name` instead of `id`
Closes https://github.com/chainloop-dev/chainloop/issues/1034
> chore(cli): manage organizations by name

- app/controlplane/internal/service/orgmetric.go
- app/controlplane/internal/service/service.go
- app/controlplane/pkg/biz/errors.go
- app/controlplane/pkg/biz/orgmetrics.go
- app/controlplane/pkg/data/orgmetrics.go
This patch modifies the OrgMetrics use case to receive a start and end date which are more flexible that a time.Duration. Do all the changes up until the repository.
Ent does not have a between operator for dates that's the reason of using gte and lte. In operator does not produce the proper SQL query:
`In` operator:
```sql
SELECT COUNT(DISTINCT "workflow_runs"."id")
FROM "workflow_runs"
JOIN (SELECT "workflows"."id"
FROM "workflows"
JOIN (SELECT "organizations"."id" FROM "organizations" WHERE "organizations"."id" = $1) AS "t1"
ON "workflows"."organization_id" = "t1"."id") AS "t1"
ON "workflow_runs"."workflow_workflowruns" = "t1"."id"
WHERE "workflow_runs"."created_at" IN ($2, $3)
```
`gte` and `lte` operators:
```sql
SELECT COUNT(DISTINCT "workflow_runs"."id")
FROM "workflow_runs"
JOIN …
```
> feat(orgmetrics): Accept start and end date for metrics

- app/cli/cmd/casbackend_add_s3.go
- pkg/blobmanager/s3/backend.go
- pkg/blobmanager/s3/backend_test.go
- pkg/blobmanager/s3/provider.go
- pkg/blobmanager/s3/provider_test.go
Adds support to registering an S3-compatible CAS-backend by providing a custom endpoint. making it compatible with Minio and Cloudflare R2
AWS S3 support has not changed, except that the region now is optional. Region is optional now because it doesn't make much sense in the concept of other providers.
```
chainloop cas-backend add aws-s3 --access-key-id AKIA5CHQ4CJGSHYWLEZF --secret-access-key ${SECRET_KEY} --bucket chainloop-test --name aws-test                     
┌──────────┬────────────────┬──────────┬─────────────┬───────────────┬─────────┐
│ NAME     │ LOCATION       │ PROVIDER │ DESCRIPTION │ LIMITS        │ DEFAULT │
├──────────┼────────────────┼──────────┼─────────────┼───────────────┼─────────┤
│ aws-test │ chainloop-test │ AWS-S3   │             │ MaxSize: 100M │ false   │ …
```
> feat(casbackends): support for s3 compatible endpoints (minio, cloudflare R2, ...)

- deployment/chainloop/README.md
The linter is complaining after doing a `yarn run docusaurus download-remote-deployment-readme` with this version of the README. This small PR fixes it.
> chore(docs): fix README link

- app/controlplane/pkg/biz/apitoken.go
- app/controlplane/pkg/biz/mocks/APITokenRepo.go
- app/controlplane/pkg/data/apitoken.go
There was a bug that prevented revoking tokens which name might have existed in another organization. This fixes it by moving the authz scope to the query itself
```
finding token: ent: api_token not singular
```
> fix: scope down revocation

- deployment/chainloop/README.md
- deployment/chainloop/values.yaml
This is a follow up of https://github.com/chainloop-dev/chainloop/pull/1056 to fix some other invalid characters when interpreting this doc as MDX
> chore(docs): fix README to use HTML-encoded characters

- app/controlplane/internal/usercontext/allowlist_middleware.go
- app/controlplane/internal/usercontext/allowlist_middleware_test.go
API tokens were being captured in the allowlist middleware. This meant in practice that any operations like `creating workflows` or `updating contracts` were failing with `USER not found` error.
> fix(controlplane): skip allow-list for API tokens

- app/artifact-cas/internal/server/grpc.go
- app/artifact-cas/internal/server/grpc_test.go
This PR fixes a compatibility problem with latest reflection API (used by recent versions of grpcurl) and CAS auth middleware.
Closes #1073
> fix(cas): Fix compatibility with Reflection API

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/cas/customcas.secret.yaml
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/values.yaml
This PR allows to mount system-wide CAs certificates in the CAS deployment. This is specially useful when connecting to custom backends like Minio.
Closes #1077
> feat(cas): Allow custom CAs in CAS deployment

- deployment/chainloop/README.md
Update the configuration example to add a certificate validity (as it defaults to 1 month).
> chore(deployment): add certificate validity to file CA example

- app/controlplane/Dockerfile.migrations
- go.sum
This PR fixes CVE-2024-2455, CVE-2024-29018 and CVE-2024-24791
> chore(vulns): fix CVEs in base image

- app/artifact-cas/internal/server/http.go
- pkg/middlewares/http/jwt.go
- pkg/middlewares/http/jwt_test.go
This patch adds two jwt middleware to validate JWT tokens in http servers, one for tokens that are part of a query param and other from authorization headers.
Refs #1098
> feat(http): Create jwt middlewares for http servers

- internal/attestation/crafter/crafter.go
- internal/attestation/renderer/renderer.go
- pkg/policies/policies.go
Logging violations in the CLI was implemented in a prior version of policies, but got lost somehow.
Refs #122
> chore(policies): log policy violations

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/controlplane/config.configmap.yaml
- deployment/chainloop/values.yaml
This patch allows to include a set of organizations as part of the configuration to activate the Prometheus integration:
Refs https://github.com/chainloop-dev/chainloop/issues/1098
> feat(chart): Change template to allow prometheus integration config

- app/controlplane/pkg/metrics/prometheus/collector.go
This patch changes the labels exposed by Prometheus simplifying them. 
Refs https://github.com/chainloop-dev/chainloop/issues/1098
> feat(prometheus): Rename prometheus labels

- app/cli/cmd/attestation.go
- app/cli/cmd/attestation_init.go
- app/cli/cmd/attestation_push.go
- app/cli/cmd/attestation_status.go
- app/cli/cmd/root.go
- app/cli/internal/action/action.go
- app/cli/internal/action/attestation_add.go
- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_reset.go
- app/cli/internal/action/attestation_status.go
Removes the requirement of passing --remote-state to each subsequent command after init.
Now, by having initialized the attestation with `--remote-state` you can just use `attestation-id` in `add, reset, status or push`
Closes #972
> chore: do not require remote-state flag

- internal/attestation/crafter/crafter.go
- pkg/policies/policies.go
By implementing a specific error type, we can stop the guess-type loop for contractless materials:
```
DBG loading state state=file:///var/folders/ls/cv3k03v57ns18mmwjjbgy8z00000gn/T/chainloop-attestation.tmp.json
DBG loaded state state=file:///var/folders/ls/cv3k03v57ns18mmwjjbgy8z00000gn/T/chainloop-attestation.tmp.json
DBG decoding OpenVex file path=sbom-spdx.json
DBG failed to add material error="crafting material: invalid OpenVEX file: unexpected material type" kind=OPENVEX
DBG error decoding file: [I#] [S#] doesn't validate with http://cyclonedx.org/schema/bom-1.6.schema.json#
[I#] [S#/required] missing properties: 'bomFormat', 'specVersion'
[I#] [S#/additionalProperties] additionalProperties 'relationships', 'spdxVersion', 'dataLicense', 'SPDXID', …
```
> fix(policies): fail adding material if policy cannot be parsed

- app/cli/cmd/workflow_workflow_run_describe.go
This PR adds policies to `att describe` command:
```
┌──────────────────────────────────────────────────────────────────────────────────────────┐
│ Workflow                                                                                 │
├────────────────┬─────────────────────────────────────────────────────────────────────────┤
│ ID             │ e56ea38d-67f4-408a-8bb2-6ac54ba22da3                                    │
│ Name           │ policytest                                                              │
│ Team           │                                                                         │
│ Project        │ myproject                                                               │
├────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ …
```
> chore(policies): add policies to table output

- app/controlplane/configs/config.devel.yaml
- app/controlplane/configs/samples/config.yaml
- app/controlplane/pkg/biz/orgmetrics.go
- app/controlplane/pkg/biz/prometheus.go
- app/controlplane/pkg/metrics/prometheus/collector/collector.go
- app/controlplane/pkg/metrics/prometheus/manager.go
- app/controlplane/pkg/metrics/prometheus/registry/registry.go
Minor refactoring on the prometheus packages
- decouple `manager` from `collector` by moving the collector code to another package.
- moves `manager` to the top level `prometheus` package
- adds examples in the config and enables it in development
ref #1118
> refactor: prometheus packages

- extras/dagger/main.go
Fixes a known breaking change of Dagger 0.12. Now dagger by default doesn't run entrypoint, even if it's explicitly set. 
cc/ @jpadams
Closes #1139
> fix(dagger): make module work with Dagger 0.12

- .github/workflows/test.yml
This should mitigate #1146. We'd need probably a permanent fix which involves removing the deprecated feature.
Fixes #1146
> chore: lock atlas version in test workflow

- docs/docs/guides/prometheus/README.md
This patch adds a missing meta tag for the new Prometheus documentation's page.
Refs #1115
> feat(docs): Add meta tag to Prometheus

- app/controlplane/pkg/biz/orgmetrics.go
- app/controlplane/pkg/metrics/prometheus/collector/collector.go
This patch adds the `runner` type to the metric `chainloop_workflow_up` to keep consistency.
Closes #1160
> feat(prometheus): Add runner type to prometheus metric

- app/controlplane/pkg/metrics/prometheus/manager.go
- app/controlplane/pkg/metrics/prometheus/manager_test.go
- app/controlplane/pkg/metrics/prometheus/registry/registry.go
- app/controlplane/pkg/metrics/prometheus/registry/registry_test.go
This patch ensures that the histogram metric is a local reference not a shared one.
> chore(prometheus): update histogram variable reference

- go.mod
- go.sum
This patch bumps the version of golang grpc `v1.62.1` to `v1.64.1` to fix: https://github.com/chainloop-dev/chainloop/security/dependabot/55
> fix(grpc): Bump golang grcp dependency

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/NOTES.txt
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/controlplane/config.configmap.yaml
This patch includes changes on the NOTES.txt to comply with Bitnami's Chart standards.
Example of output in development mode:
```
NAME: chainloop
LAST DEPLOYED: Wed Jul 31 12:42:21 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: chainloop
CHART VERSION: 1.85.0
APP VERSION: v0.95.2
** Please be patient while the chart is being deployed **
###########################################################################
CONFIGURE CLI
###########################################################################
Configure the CLI to point to this instance, for example
chainloop --insecure config save \
--control-plane my-controlplane.acme.com:80 \
--artifact-cas cas.acme.com:80
Refer to this link for more information …
```
> feat(chart): Modify NOTES.txt

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/cas/config.configmap.yaml
- deployment/chainloop/templates/controlplane/config.configmap.yaml
- deployment/chainloop/values.yaml
This patch changes the configmaps so it's compliance with Bitnami's Chart standards.
Diff of changes:
```diff
diff --git a/old.yaml b/new.yaml
index a9b1acf..635b3d8 100644
--- a/old.yaml
+++ b/new.yaml
@@ -333,7 +333,7 @@ metadata:
type: Opaque
data:
-  generated_jws_hmac_secret: "MDVUY3NONkNCNA=="
+  generated_jws_hmac_secret: "Mkp4Y0NvdzkxVQ=="
db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQGNoYWlubG9vcC1wb3N0Z3Jlc3FsOjU0MzIvY2hhaW5sb29wLWNwP3NzbG1vZGU9ZGlzYWJsZQ=="
stringData:
@@ -357,7 +357,7 @@ stringData:
-      generated_jws_hmac_secret: "05TcsN6CB4"
+      generated_jws_hmac_secret: "2JxcCow91U"
cas_robot_account_private_key_path: "/secrets/cas.private.key"
@@ -405,13 +405,13 @@ apiVersion: v1
kind: ConfigMap
metadata:
name: chainloop-cas
+ …
```
> feat(chart): Modify configmaps

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/config.secret.yaml
- deployment/chainloop/templates/controlplane/config.secret.yaml
This patch changes the secrets so it's compliance with Bitnami's Chart standards.
Diff of changes:
```diff
index a9b1acf..c9d81f8 100644
--- a/old.yml
+++ b/new.yml
@@ -278,13 +278,13 @@ apiVersion: v1
kind: Secret
metadata:
name: chainloop-cas
+  namespace: "default"
labels:
-    app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.85.0
app.kubernetes.io/instance: chainloop
app.kubernetes.io/managed-by: Helm
-    app.kubernetes.io/version: "v0.95.2"
-    app.kubernetes.io/part-of: chainloop
+    app.kubernetes.io/name: chainloop
+    app.kubernetes.io/version: v0.95.2
+    helm.sh/chart: chainloop-1.85.0
app.kubernetes.io/component: cas
type: Opaque
stringData:
@@ -322,18 +322,18 @@ apiVersion: v1
kind: Secret
metadata:
name: …
```
> feat(chart): Modify secrets

- app/cli/internal/action/attestation_add.go
- internal/attestation/crafter/crafter.go
- internal/attestation/crafter/crafter_test.go
This patch allows materials that are not part of a contract to have a custom name if desired instead of auto generating
Example:
```shell
$ chainloop --insecure wf contract describe --name core-deployment
INF To download the contract, run the command with the "--output schema" option
┌────────────────────────────────────────────┐
│ Contract                                   │
├──────────────────────┬─────────────────────┤
│ Name                 │ core-deployment     │
├──────────────────────┼─────────────────────┤
│ Description          │                     │
├──────────────────────┼─────────────────────┤
│ Associated Workflows │                     │
├──────────────────────┼─────────────────────┤
│ Revision number      │ 1                   │ …
```
> feat(attestations): Allow custom name on external evidence

- docs/docs/reference/policies.mdx
- docs/examples/policies/sbom/cyclonedx-licenses.yaml
- Updates the sbom licenses policy to show a shorter message
- Imports such policy directly in the docs so we do not need to maintain both copies.
> docs: update sbom license policy

- dagger.json
- extras/dagger/go.mod
- extras/dagger/go.sum
This patch fixes the dependency of google.com/grpc to a patched version.
`dagger develop` and manual change on `go.mod` has been performed.
This fixes: https://github.com/chainloop-dev/chainloop/security/dependabot/55
> fix(dagger): Bump google.com/grpc dependency

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/serviceaccount.yaml
- deployment/chainloop/templates/controlplane/serviceaccount.yaml
This patch modifies the service accounts to be compliant with Bitnami Charts' practices.
Diff of changes:
```diff
index 96660cc..a18d00e 100644
--- a/old.yml
+++ b/new.yml
@@ -218,13 +218,13 @@ apiVersion: v1
kind: ServiceAccount
metadata:
name: chainloop-cas
+  namespace: "default"
labels:
-    app.kubernetes.io/name: chainloop
-    helm.sh/chart: chainloop-1.86.0
app.kubernetes.io/instance: chainloop
app.kubernetes.io/managed-by: Helm
-    app.kubernetes.io/version: "v0.95.3"
-    app.kubernetes.io/part-of: chainloop
+    app.kubernetes.io/name: chainloop
+    app.kubernetes.io/version: v0.95.3
+    helm.sh/chart: chainloop-1.86.0
app.kubernetes.io/component: cas
---
@@ -232,13 +232,13 @@ apiVersion: v1
kind: ServiceAccount
metadata:
name: …
```
> feat(chart): Modify sevice accounts

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/_helpers.tpl
The latest patch added am additional tag that makes upgrades of existing releases fail
refs #1151
> chore: remove additional label to allow upgrades

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
This patch changes the names of the main container in `cas` and `controlplane`.
Will bump the chart patch version.
Diff:
```diff
index 7bb317e..d56b0e5 100644
--- a/old.yml
+++ b/new.yml
@@ -103,7 +103,7 @@ metadata:
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: chainloop
app.kubernetes.io/version: v0.95.3
-    helm.sh/chart: chainloop-1.86.13
+    helm.sh/chart: chainloop-1.86.14
app.kubernetes.io/component: cas
spec:
podSelector:
@@ -131,7 +131,7 @@ metadata:
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: chainloop
app.kubernetes.io/version: v0.95.3
-    helm.sh/chart: chainloop-1.86.13
+    helm.sh/chart: chainloop-1.86.14
app.kubernetes.io/component: controlplane
app.kubernetes.io/component: controlplane
spec:
@@ -307,7 +307,7 @@ …
```
> feat(chart): Change container names

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/controlplane/networkpolicy.yaml
This patch removes a duplicated label present on the deployment of the `controlplane`.
Diff:
```diff
diff --git a/Users/javirln/Library/Application Support/JetBrains/GoLand2024.1/scratches/scratch_13.yml b/Users/javirln/Library/Application Support/JetBrains/GoLand2024.1/scratches/scratch_14.yml
index 3a2aa37..842836f 100644
--- a/Users/javirln/Library/Application Support/JetBrains/GoLand2024.1/scratches/scratch_13.yml
+++ b/Users/javirln/Library/Application Support/JetBrains/GoLand2024.1/scratches/scratch_14.yml
@@ -103,7 +103,7 @@ metadata:
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: chainloop
app.kubernetes.io/version: v0.95.3
-    helm.sh/chart: chainloop-1.86.14
+    helm.sh/chart: chainloop-1.86.15
app.kubernetes.io/component: cas
spec:
podSelector:
@@ -131,8 +131,7 @@ …
```
> fix(chart): Remove duplicated label

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/networkpolicy.yaml
- deployment/chainloop/templates/controlplane/networkpolicy.yaml
Add missing ports on `cas` and `controlplane` network policies.
Refs #1208
> fix(chart): Missing ports on network policies

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/cas/configmap.yaml
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/templates/controlplane/configmap.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
- deployment/chainloop/values.yaml
This patch modifies the name of the TLS config param.
Diff:
```diff
index 7bb317e..bb56aef 100644
--- a/old.yml	
+++ b/new.yml	
@@ -441,7 +441,7 @@ metadata:
type: Opaque
data:
-  generated_jws_hmac_secret: "dkNTVk5SaTVrWg=="
+  generated_jws_hmac_secret: "MWh5U2p1eVVnVw=="
db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQGNoYWlubG9vcC1wb3N0Z3Jlc3FsOjU0MzIvY2hhaW5sb29wLWNwP3NzbG1vZGU9ZGlzYWJsZQ=="
stringData:
@@ -465,7 +465,7 @@ stringData:
-      generated_jws_hmac_secret: "vCSVNRi5kZ"
+      generated_jws_hmac_secret: "1hySjuyUgW"
cas_robot_account_private_key_path: "/secrets/cas.private.key"
@@ -1582,7 +1582,7 @@ spec:
metadata:
annotations:
checksum/config: 7ebb40b21af918bef7decf41a5d6bbfcbdcab8a7b275e06922e7174f4ecfd …
```
> feat(chart): Modify TLS config param

- app/cli/cmd/attestation_add.go
I noticed in the wild that 10 seconds was not enough in some cases to recover from conflicts. This patch increases the upper limit so I'll watch it
> feat(cli): increase retry time

- app/cli/cmd/workflow_create.go
- app/controlplane/internal/service/service.go
- app/controlplane/pkg/biz/apitoken.go
- app/controlplane/pkg/biz/casbackend.go
- app/controlplane/pkg/biz/errors.go
- app/controlplane/pkg/biz/integration.go
- app/controlplane/pkg/biz/organization.go
- app/controlplane/pkg/biz/organization_test.go
- app/controlplane/pkg/biz/workflow.go
- app/controlplane/pkg/biz/workflowcontract.go
- app/controlplane/pkg/data/apitoken.go
- app/controlplane/pkg/data/casbackend.go
- app/controlplane/pkg/data/integration.go
- app/controlplane/pkg/data/organization.go
- app/controlplane/pkg/data/workflow.go
- app/controlplane/pkg/data/workflowcontract.go
This patch adds a flag `--skip-if-exists` on `chainloop workflow create` command that performs a graceful exit (exit code 0) if the workflow with the same name exists.
First creation
```
chainloop wf create --name my-wf --project bar 
┌───────┬─────────┬───────────┬────────┬────────┬─────────────────┬─────────────────────┐
│ NAME  │ PROJECT │ CONTRACT  │ PUBLIC │ RUNNER │ LAST RUN STATUS │ CREATED AT          │
├───────┼─────────┼───────────┼────────┼────────┼─────────────────┼─────────────────────┤
│ my-wf │ bar     │ bar-my-wf │ false  │        │                 │ 12 Aug 24 20:58 UTC │
└───────┴─────────┴───────────┴────────┴────────┴─────────────────┴─────────────────────┘
```
as expected, it will fail if you try to create it again.
```
chainloop wf create --name my-wf --project bar …
```
> feat(cli): allow graceful exit on workflow create

- app/cli/internal/action/action.go
- app/cli/internal/action/attestation_push.go
- pkg/attestation/crafter/crafter.go
- pkg/attestation/crafter/crafter_test.go
- pkg/attestation/renderer/renderer.go
- pkg/attestation/renderer/renderer_test.go
- pkg/policies/loader.go
- pkg/policies/policies.go
- pkg/policies/policies_test.go
This is the closing PR for #1180 
This change adds the capability to load policies from remote providers, by using the `chainloop://[provider-name/]policy-name` syntax in the `ref` field in contracts.
Note that for the feature to fully work, at least one provider must be configured in the control plane deployment. If no provider is set in the `ref` field, the default provider will be tried.
Previously, only policies coming from local filesystem and public HTTPS were supported.
Note that I've removed policy validations during contract craft operations, since they might not be present during contract creation.
Example execution:
```
> chainloop wf contract update --name embedded --contract test/my-contract.yaml
WRN Both user credentials and …
```
> feat(policies): load and evaluate remote policies on attestation operations

- pkg/policies/loader.go
- pkg/policies/policies.go
- pkg/policies/policies_test.go
This PR adds some tests to the protocol parsing logic in policy loaders. It also renames URLLoader to be less confusing.
Closes #1221
> chore(policies): add tests for policy loader

- pkg/policies/loader.go
- pkg/policies/policies.go
This PR fixes 2 issues:
* properly wrap upstream error
* add provider and policy name to the error messsage
```
ERR applying policies to statement: policy error: loading policy spec: requesting remote policy (provider: idontexist, name: sbom-present): rpc error: code = NotFound desc = policy not found
```
Fixes #1225
> chore(policies): improve error message when policy is not found

- app/cli/main.go
- app/controlplane/internal/service/service.go
Shows just the gRPC error not the whole wrapped chain to the user for expected gRPC errors.
Examples
Before
```
$ go run main.go --insecure org api-token create --name test
ERR creating API token: creating API token: rpc error: code = AlreadyExists desc = duplicated: name already taken
```
after
```
$ go run main.go --insecure org api-token create --name test
ERR duplicated: name already taken
```
before
```
$ go run main.go --insecure org api-token create --name test_foo
ERR creating API token: creating API token: rpc error: code = InvalidArgument desc = validation error: "test_foo": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is …
```
> fix: show only grpc error

- app/controlplane/internal/dispatcher/dispatcher.go
- app/controlplane/internal/service/integration.go
- app/controlplane/pkg/biz/integration.go
- app/controlplane/pkg/biz/integration_test.go
- app/controlplane/pkg/data/integrationattachment.go
This patch wraps the integration attachments listing into a structure that holds both a `Integration` and `IntegrationAttachment`.
> refactor(integration-attachments): Map all integration attachments properties

- .github/workflows/release.yaml
Removes the version from the installation script.
Fixes #1251
> chore: unlock Chainloop CLI version in github workflow

- docs/docs/guides/prometheus/README.md
This patch adds to the public documentation the link to the Grafana Dashboard published in Grafana Labs.
> feat(docs): Add link to public Grafana dashboard on docs

- app/artifact-cas/configs/config.devel.yaml
- app/controlplane/configs/config.devel.yaml
- compose.yaml
- devel/compose.yml
- devel/dex/config.dev.yaml
- devel/labs.compose.yaml
This PR adds a new docker compose file for those who want to quickly setup a local instance of Chainloop using upstream images.
This configuration sets up: control-plane, artifacts-cas, control-plane-migrations, and leverages existing devel compose configuration for postgresql, vault and dex.
I've setup service dependencies properly so that they are run in order. Interestingly, I've added a service for running DB migrations.
Caveats:
* It uses `dex` as the Dex host (this is to ensure there is connectivity between docker instances). This means that users must add a `127.0.0.1 dex` entry in `/etc/hosts`, otherwise `chainloop auth login` won't work. This might be fixed by running all services with `host` networking, but it only works in Linux and recent versions of Docker Desktop.
How to …
> feat: docker compose configuration for local testing

- pkg/policies/policies_test.go
Fixes an annoying lint error in our CI (caused by a previous merge)
> chore: fix lint error

- .github/workflows/build_and_package.yaml
- .goreleaser.yml
This PR introduces changes for building multiarch images with goreleaser. Note that it needs `buildx`,  which in turn uses qemu binaries (that's the reason for the workflow changes).
Basically duplicates all `docker` configurations for both architectures (I've already checked that we use multiarch base images), and adds new `docker_manifests` for the multiarch index manifests.
Building locally:
```
> goreleaser release --clean --snapshot --skip=sign,sbom
...
```
Running (see the warning for AMD in MacOS with Rosetta)
```
✗ docker run ghcr.io/chainloop-dev/chainloop/cli:v0.96.2-amd64
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Chainloop Command Line Interface
Usage:
chainloop …
```
> feat: Build multiarch images

- docs/docs/reference/policies.mdx
- pkg/policies/loader.go
- pkg/policies/policies_test.go
this PR add support for explicit `file://` scheme when referencing a local policy. The goal is to slowly move to Chainloop provider policies when no scheme is present.
> chore(policies): support file:// to reference filesystem policies

- deployment/chainloop/Chart.yaml
Adding the CLI image in our Helm Chart so it can be part of the relocation process
> chore(deployment): record CLI in Helm Chart images annotations

- app/cli/cmd/root.go
- app/cli/internal/telemetry/posthog/posthog.go
Make the telemetry code less intrusive in scenarios where the connectivity is limited. This means removing the default logging and adding a timeout to the call so the CLI doesn't hang.
> fix(cli): add timeout to telemetry

- app/cli/cmd/auth_login.go
Instead of not setting the callback value, we now make it empty to indicate that it has no value.
```
$ go run main.go auth login --skip-browser --insecure
To authenticate, click on the following link and paste the result back here
http://0.0.0.0:8000/auth/login?callback=&long-lived=true
```
Fixes #1273
> fix(cli): set explicit empty callback URL

- Makefile
- app/cli/Dockerfile.goreleaser
- app/cli/cmd/config.go
- app/cli/cmd/root.go
- Exposes main configuration through env vars and documents it in the CLI itself
```
Flags:
--artifact-cas string       URL for the Artifacts Content Addressable Storage API ($CHAINLOOP_ARTIFACT_CAS_API) (default "api.cas.chainloop.dev:443")
--artifact-cas-ca string    CUSTOM CA file for the Artifacts CAS API (optional) ($CHAINLOOP_ARTIFACT_CAS_API_CA)
-c, --config string             Path to an existing config file (default is $HOME/.config/chainloop/config.toml)
--control-plane string      URL for the Control Plane API ($CHAINLOOP_CONTROL_PLANE_API) (default "api.cp.chainloop.dev:443")
--control-plane-ca string   CUSTOM CA file for the Control Plane API (optional) ($CHAINLOOP_CONTROL_PLANE_API_CA)
--debug                     Enable debug/verbose logging mode
-h, --help …
```
> feat(cli): add support for env vars

- extras/dagger/go.sum
- extras/dagger/main.go
This patch bumps the CLI version of the dagger module and remove unneeded dependencies.
The contract-less support was added when we developed the feature so it's up to date.
Refs #1145
> chore(dagger): Bump CLI version and update dependencies

- pkg/policies/loader.go
- pkg/policies/loader_test.go
fixes
```
ERR applying policies to statement: policy error: loading policy spec: Get "raw.githubusercontent.com/chainloop-dev/chainloop/main/docs/examples/policies/sbom/sbom-present.yaml": unsupported protocol scheme ""
```
> fix(policies): allow downloading policies form http endpoint

- app/cli/cmd/artifact.go
- app/cli/cmd/attestation_add.go
- app/cli/cmd/root.go
In a previous patch https://github.com/chainloop-dev/chainloop/pull/1274, we moved the `insecure` flag as part of the viper configuration, but I missed propagating some of those changes through the CLI.
> fix(cli): load insecure option from viper

- README.md
- deployment/chainloop/README.md
- docs/docs/guides/dagger/README.md
- docs/docs/guides/deployment/k8s/k8s.mdx
- docs/docs/guides/ejbca/ejbca.md
- docs/docs/guides/signserver/signserver.md
- docs/docs/reference/_category_.json
- docs/docs/reference/operator/contract.mdx
- docs/docs/reference/signing.md
- extras/dagger/README.md
- updates contract reference with the rest of materials, plus policies
- Expands the reference guide section
- Updates project name
- Fixes broken link in readme 
- Updates dagger info
> docs: add policy information in reference docs

- app/controlplane/api/workflowcontract/v1/crafting_schema.proto
- app/controlplane/api/workflowcontract/v1/crafting_schema_test.go
- app/controlplane/api/workflowcontract/v1/crafting_schema_validations.go
- app/controlplane/pkg/biz/workflowcontract.go
This PR adds validations to the `ref` property in the policy attachment, including
- making sure the protocol is either empty or one of the supported ones
- if we are using a file, HTTP protocol make sure the file has an extension i.e .yaml
- if we are using provider protocol, make sure that both the provider and the policy name are DNS compatible.
- If we are providing a digest (not used yet), make sure it's a valid formed digest
Errors are exposed now during the contract create/updaet
```sh
ERR validation error: invalid reference "https://raw.githubusercontent.com/chainloop-dev/chainloop/main/docs/examples/policies/sbom/sbom-present": missing extension
ERR validation error: invalid reference "unknown:///Users/miguelmartinez/work/chainloop/policies-playground/cyclonedx-licenses.yaml": …
```
> feat(policies): improve attachment validations

- app/controlplane/pkg/biz/workflowcontract.go
- app/controlplane/pkg/policies/policyprovider.go
from
```
ERR validation error: failed to get policy 'sbom-present': failed to resolve policy: error executing policy request: Get "http://localhost:8002/v1/policies/sbom-present": dial tcp [::1]:8002: connect: connection refused. Available providers: [chainloop]
```
to
```
ERR policy "cyclonedx-freshness" not found
```
and
```
ERR validation error: failed to get policy 'sbom-present': policy "sbom-present" not found
```
> fix(policies): handle provider 404

- .github/workflows/build_and_package.yaml
- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .golangci.yml
- app/controlplane/Dockerfile.migrations
- common.mk
- docs/docs/getting-started/attestation-crafting.md
- docs/examples/ci-workflows/github.yaml
- go.mod
This patch upgrades the Golang version to latest at the moment, 1.23.1.
Refs: https://github.com/chainloop-dev/chainloop/issues/1299
> chore(golang): Upgrade Golang version to 1.23.1

- docs/docs/reference/policies.mdx
Added an integrity check section in the docs, also fixed some links
Ref #1111
> docs(policies): digest integrity checks

- app/controlplane/api/workflowcontract/v1/crafting_schema_test.go
- app/controlplane/api/workflowcontract/v1/crafting_schema_validations.go
this PR adds support to local file URLs with no path like: `file://my-policy.yaml`
Fixes #1307
> fix(policies): Support file:// URLs with no path

- .github/workflows/contracts/chainloop-docs-release.yml
- .github/workflows/contracts/chainloop-vault-codeql.yml
- .github/workflows/contracts/chainloop-vault-helm-package.yml
- .github/workflows/contracts/chainloop-vault-release.yml
- .github/workflows/contracts/chainloop-vault-scorecards.yml
This patch adds some default policies to the declarative contracts we have in Chainloop source code.
Refs #1312
> feat(contracts): Add default policies to contracts

- app/controlplane/internal/service/attestation.go
Old policies were raising a nil pointer
> fix(policies): handle old policy evaluations

- .github/workflows/contracts/chainloop-docs-release.yml
- .github/workflows/contracts/chainloop-vault-codeql.yml
- .github/workflows/contracts/chainloop-vault-scorecards.yml
This patch adds a missing parameter for the `sarif-vulns` and `cyclonedx` policies. 
Ref #1312
> fix(contract): Add missing parameter to contracts

- .github/workflows/build_and_package.yaml
- .github/workflows/codeql.yml
This patch removes the pinned version of Chainloop CLI on the GitHub workflows.
Refs #1312
> feat(workflows): Remove pinned version of Chainloop CLI

- extras/dagger/README.md
- extras/dagger/main.go
```
dagger call with-instance -h
Configure the Chainloop instance to use
USAGE
dagger call with-instance [arguments] <function>
FUNCTIONS
init            Initialize a new attestation
resume          Resume an attestation from its identifier
with-instance   Configure the Chainloop instance to use
ARGUMENTS
--cas-api string            Example: "api.cas.company.com:443" [required]
--controlplane-api string   Example: "api.controlplane.company.com:443" [required]
--cas-ca File               Path to custom CA certificate for the CAS API
--controlplane-ca File      Path to custom CA certificate for the Control Plane API
--insecure                  Whether to skip TLS verification
```
Closes #1325
> feat(dagger): support customizing instance

- .github/workflows/build_and_package.yaml
- .github/workflows/utils/bump-chart-and-dagger-version.sh
This patch modifies the bump chart version to also upgrade the version of dagger in every release.
Refs: #1330
> feat(.github): Bump Dagger version on new releases

- dagger.json
- extras/dagger/README.md
- extras/dagger/go.mod
- extras/dagger/main.go
extends our dagger module to support creating workflows
```
Create a new workflow
USAGE
dagger call workflow-create [arguments]
ARGUMENTS
--name string          Workflow name [required]
--project string       Workflow project [required]
--token Secret         Chainloop API token [required] (default )
--description string
--public               Set workflow as public so other organizations can see it
--skip-if-exists       If the workflow already exists, skip the creation and return success
--team string
```
closes #1323
> feat(dagger): support workflow creation

- dagger.json
https://github.com/chainloop-dev/chainloop/pull/1324 introduced by mistake a dagger engine upgrade. We should do this upgrade separately to allow clients that do not have this version to stick to this commit hash.
> chore(dagger): downgrade dagger engine

- app/controlplane/pkg/biz/membership_integration_test.go
- app/controlplane/pkg/biz/orginvitation.go
- app/controlplane/pkg/biz/orginvitation_integration_test.go
- app/controlplane/pkg/biz/user.go
- app/controlplane/pkg/biz/user_integration_test.go
- app/controlplane/pkg/data/ent/migrate/migrations/20240920193509.sql
- app/controlplane/pkg/data/ent/migrate/migrations/atlas.sum
- stores email addresses for users and invitations in lowercase
- updates all email addresses in the DB to be lowercase
Fixes #1344
> fix(controlplane): make email case insensitive

- pkg/attestation/crafter/crafter_test.go
- pkg/attestation/crafter/runners/jenkinsjob.go
- pkg/attestation/crafter/runners/jenkinsjob_test.go
> fix(jenkins): use WORKSPACE instead of AGENT_WORKDIR

- docs/docs/reference/policies.mdx
- docs/examples/policies/sbom/cyclonedx-banned-licenses.yaml
- docs/examples/policies/sbom/cyclonedx-banned-packages.yaml
- docs/examples/policies/sbom/cyclonedx-freshness.yaml
- docs/examples/policies/sbom/cyclonedx-licenses.yaml
- docs/examples/policies/sbom/cyclonedx-required-packages.yaml
- docs/examples/policies/sbom/sbom-present.yaml
- docs/examples/policies/sbom/spdx-sbom-syft.yaml
Follow up to document multi-kind policies.
Also, all examples have been moved to multikind format
> feat(policies): document multi-kind policies

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/values.yaml
This patch fixes a regression introduced in the chart that was taking only into account the legacy option for TLS configuration and not the new one.
Refs: #1353
> fix(chart): Map server-certs to correct secret name

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
This patch fixes a regression introduced when migrating to Bitnami Chart guidelines. It was missing a call to a helper method that ensures the deployment compatibility with OpenShift clusters.
```
$ kubectl get pods
NAME                                        READY   STATUS    RESTARTS        AGE
chainloop-cas-f4bdc8b8c-kkvg7               1/1     Running   2 (4m38s ago)   4m46s
chainloop-cas-f4bdc8b8c-rktbv               1/1     Running   2 (4m38s ago)   4m46s
chainloop-controlplane-644c5b487d-9vkt6     1/1     Running   0               4m46s
chainloop-controlplane-644c5b487d-sdpwq     1/1     Running   0               4m46s
chainloop-dex-765df5d877-vxlfc              1/1     Running   0               4m46s
chainloop-postgresql-0                      1/1     Running   0 …
```
> fix(chart): Ensure security context is overridden in OpenShift clusters

- pkg/attestation/crafter/materials/zap.go
- pkg/attestation/crafter/materials/zap_test.go
This patch removes the check for zip files in ZAP material type since it will load the whole file into memory.
Refs: #1359
> fix(materials): Remove check on zip files

- .github/workflows/contracts/chainloop-docs-release.yml
- .github/workflows/contracts/chainloop-vault-codeql.yml
- .github/workflows/contracts/chainloop-vault-scorecards.yml
This PR updates all policy references to use the new names.
Fixes #1368
> chore: rename policy references in github workflows

- .github/workflows/contracts/chainloop-chainloop-github-release.yaml
This is the contract that chainloop-vault-release workflow uses under the hood. Adding here to enable the gitops approach.
Related to #1369
> chore(policies): add missing contract for chainloop-valut-release workflow

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/cas/deployment.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
Quote version to prevent errors like
```
: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```
> fix(deployment): quote app version

- pkg/policies/policies.go
This fallback was introduced in #1267  for backwards compatibility. It's not needed anymore.
> chore(policies): remove fallback to file:// when ChainloopLoader fails

- extras/dagger/main.go
For now project is optional to allow people to migrate but it will stop being optional soon.
> feat(dagger): add support for optional project name during attestation

- .github/workflows/build_and_package.yaml
- .github/workflows/codeql.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/package_chart.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecards.yml
- extras/dagger/README.md
Block until new release is up and https://github.com/chainloop-dev/labs/pull/34 is merged
Refs #1375
> chore(ci): provide project name

- docs/docs/reference/policies.mdx
Minor addition to the policy engine documentation.
Ref: #1395
> fix(docs): Typo on policy engine docs

- pkg/policies/engine/rego/rego.go
- pkg/policies/engine/rego/rego_test.go
- pkg/policies/engine/rego/testfiles/restrictive_mode_networking.rego
This patch activates the strict mode on errors when the restrictive environment is active so network errors for example, raise an exception and halts the policy evaluation.
Ref #1395
> feat(policies): Add strict builtin mode

- app/controlplane/api/workflowcontract/v1/crafting_schema_test.go
- pkg/policies/loader.go
- pkg/policies/policies_test.go
This PR fixes a bug that prevented pinned policies in contracts, after the refactoring to support org-scoped policies.
I've also added some more tests.
```
✗ cldev wf contract update --name myproject-mywf --contract test/my-contract.yaml
WRN Both user credentials and $CHAINLOOP_TOKEN set. Ignoring $CHAINLOOP_TOKEN.
INF Contract updated!
┌────────────────────────────────────────────┐
│ Contract                                   │
├──────────────────────┬─────────────────────┤
│ Name                 │ myproject-mywf      │
├──────────────────────┼─────────────────────┤
│ Description          │                     │
├──────────────────────┼─────────────────────┤
│ Associated Workflows │ /                   │
├──────────────────────┼─────────────────────┤
│ …
```
> fix(policies): fix provider parsing for pinned policies

- pkg/policies/policies.go
- pkg/policies/policies_test.go
- pkg/policies/testdata/materials.yaml
- pkg/policies/testdata/multi-kind.yaml
- pkg/policies/testdata/sbom_syft.yaml
- pkg/policies/testdata/sbom_syft_not_typed.yaml
- pkg/policies/testdata/with_arguments.yaml
- pkg/policies/testdata/workflow.yaml
- pkg/policies/testdata/wrong_policy.yaml
This PR changes the way that file-based rego policies are loaded. Instead of requiring the full path, rego code will be found releatively to their yaml file. This improves policy portaibility. 
Closes #1411
> fix(policies): load rego code relative to policy yaml file

- .github/workflows/docs_deploy.yml
- .github/workflows/scorecards.yml
Scorecards seems to be fixed to a previous version of the script.
This change I believe will make it load from the latest version in `main`
> fix(ci): remove branch chainloop script

- extras/dagger/README.md
- extras/dagger/main.go
Since creating a workflow is no longer mandatory, it will get created automatically on init. We needed a way to indicate what contract to use for the new workflow
ref #1415
> feat(dagger): add support for choosing the contract on init

- .github/workflows/docs_deploy.yml
- .github/workflows/package_chart.yaml
- .github/workflows/release.yaml
- .github/workflows/scorecards.yml
> fix(ci): bump chainloop labs

- app/controlplane/internal/service/auth.go
- app/controlplane/internal/service/auth_test.go
This PR adds support for `preferred_username` claim present in Microsoft Entra OIDC IdP.
https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#payload-claims
This claim will allow us to use the proxy email that might have been used during authentication, as explained in [this other guide](https://learn.microsoft.com/en-us/entra/identity/authentication/howto-authentication-use-email-signin).
But before using this new claim, we make sure it's a valid email.
> feat(oidc): take preferred_username if present

- pkg/policies/engine/rego/rego.go
- pkg/policies/engine/rego/rego_test.go
- pkg/policies/engine/rego/testfiles/arrays.rego
This small PR adds the ability to accept arrays as the input for Rego policies.
Related to #1429
> feat(policies): allow arrays as input for policies

- app/artifact-cas/internal/service/download.go
This option allows a custom filename in the Content-Disposition header.
Closes #1440
> feat(cas): allow custom filename in HTTP Download query parameters

- app/controlplane/pkg/policies/policyprovider.go
- app/controlplane/pkg/policies/policyprovider_test.go
- pkg/policies/group_loader.go
- pkg/policies/loader.go
- pkg/policies/loader_test.go
- pkg/policies/policies.go
- pkg/policies/policies_test.go
- pkg/policies/policy_groups.go
This PR fixes the way policy references are calculated in the CLI and does some refactor by removing protobuf dependency in this calculation. Once resolved, a descriptor is created containing the URI, Name, OrgName (for custom remote policies) and Digest, which is then used through the attestation process. Previously, a in-toto protobuf message was used instead.
Fixes #1448
> fix(policies): Fix policy reference

- docs/docs/reference/attestations.md
- made attestation reference guide generic, calling it `advanced features`
- added project/versions section
- added remote state section
> docs: projects/versions

- app/controlplane/pkg/biz/workflowcontract.go
If we can't detect the format, we want to return a validation error instead of an internal error.
> fix: return validation error

- app/cli/cmd/attestation_status.go
- app/cli/cmd/attestation_status_test.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_status.go
This code decouples the output of the release information to take into account the stage of the output, either transient of final.
> fix(cli): improve pre-release output during attestation

- app/cli/cmd/attestation_status.go
- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_status.go
If no version was provided during attestation and you were using a remote state, you would get a validation error.
This makes sure to store the version object, if only if, the version number exists.
> fix: remote state with no version

- app/controlplane/pkg/data/workflow.go
- app/controlplane/pkg/data/workflowrun.go
context errors were being swallowed during the workflow run. This change makes error handling more explicit
> feat: do not swallow run error

- app/controlplane/internal/sentrycontext/sentry_context.go
- app/controlplane/internal/sentrycontext/sentry_context_test.go
- app/controlplane/internal/server/grpc.go
This patch creates a new Sentry Context interceptor that populates the request context of a possible Sentry exception to include the information about the user and the request.
> feat(sentry): Add more information to sentry

- .github/workflows/contracts/chainloop-docs-release.yml
Our current policy group doesn't support SPDX right away. Let's remove this check until it's resolved.
> fix: Remove sbom-spdx from policy check

- pkg/policies/policies.go
This small PR fixes args in policy evaluations when they have placeholders, rendering the final computed value.
```
{
"annotations": {
"category": "sbom, security"
},
...
"skipped": false,
"type": "SBOM_CYCLONEDX_JSON",
"with": {
"components": "log4j@2.14.1"
}
```
Fixes #1509
> fix(policies): report rendered args in evaluations

- docs/docs/guides/rego-policies/rego-policies.mdx
New "Policy inputs" section in the Rego policies reference, documenting `inputs`, `args` and `chainloop_metadata` fields.
> feat(docs): document policy inputs

- .github/workflows/build_and_package.yaml
- .github/workflows/release.yaml
This patch changes the definition of the `release` workflow to be a reusable workflow. This workflow will be called once the release process done by Goreleaser is done, so we can attest the whole GitHub release by passing the tag information.
> feat(ci): Add reusable workflow for GitHub release

- app/controlplane/pkg/biz/referrer_integration_test.go
- app/controlplane/pkg/data/referrer.go
Updates the referrer storage code to leverage upsert and prevent the following concurrency control error
```
saving referrers: failed to create referrer: ent: constraint failed: ERROR: duplicate key value violates unique constraint "referrer_digest_kind" (SQLSTATE 23505)
```
> fix(controlplane): concurrency control referer API

- app/cli/cmd/attached_integration_add.go
- app/cli/cmd/attached_integration_list.go
- app/cli/internal/action/attached_integration_add.go
- app/cli/internal/action/attached_integration_list.go
This pull request introduces changes to the CLI commands for attaching and listing integrations, adding support for specifying a project name. The most important changes include modifying the command functions to accept and require a project name, and updating the corresponding action methods to handle the project name.
> fix(integration): Add missing project name

- .github/workflows/build_and_package.yaml
Reusable workflows cannot be added into the steps, they need to be at jobs level.
> fix(ci): Fixes ci workflow

- .github/workflows/build_and_package.yaml
Remove the call to GitHub release reusable workflow altogether.
> fix(ci): Remove GitHub release pipeline

- .github/workflows/build_and_package.yaml
- .github/workflows/release.yaml
This pull request includes an important change to the GitHub Actions workflow configuration to automate the release process when a tag is pushed.
Changes to GitHub Actions workflow:
* [`.github/workflows/build_and_package.yaml`](diffhunk://#diff-6da07ad9f67c905cf311036b9b3ae522ff5a7af74dab5c6d91f2aa00f154ef40R148-R156): Added a `github-release` job that triggers when a tag is pushed. This job uses the `chainloop-dev/chainloop/.github/workflows/release.yaml` workflow to handle the release process, including setting permissions to write packages and contents.
> fix(ci): Include GitHub release workflow with proper permissions

- .github/workflows/build_and_package.yaml
This patch adds a job dependency to the previous job so it waits until it's done to proceed.
> fix(github-release): Add job dependency

- app/cli/internal/action/action.go
option to override the default state path for local-based attestation process.
I decided to not to expose it through flags yet since it's a debugging feature for now (will be used for load testing), and I am not sure it's worth exposing
> feat: support overriding state path

- app/cli/cmd/attestation.go
- app/cli/cmd/attestation_add.go
- app/cli/cmd/attestation_init.go
- app/cli/cmd/attestation_push.go
- app/cli/cmd/attestation_reset.go
- app/cli/cmd/attestation_status.go
- app/cli/internal/action/action.go
- app/cli/internal/action/attestation_add.go
- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_reset.go
- app/cli/internal/action/attestation_status.go
support overriding the default attestation path. Useful for parallelism 
```
chainloop attestation [init,add,push,reset,status] --local-state-path /my-dir/state.json
```
ref #1533
> feat: add support to configure local path

- app/cli/cmd/root.go
- app/cli/cmd/version.go
cobra output is used by `cmd.Printf` family of commands. It was sending its ouput to stderr by default.
This way, `chainloop version` can be used in automations (eg. to check the version is correct after downloading the CLI)
Before:
```shell
> chainloop version > version.txt
> cat version.txt
```
Now:
```shell
> chainloop version > version.txt
> cat version.txt
chainloop version dev
```
> chore: set default cobra output to os.Stdout

- app/controlplane/pkg/data/workflowrun.go
the following query has a locking issue when performing an attestation on the same run with the same version.
```
INSERT INTO "project_versions" ("version", "created_at", "prerelease", "project_id", "id") VALUES ($1, $2, $3, $4, $5) ON CONFLICT ("version", "project_id") WHERE "deleted_at" IS NULL DO UPDATE SET "version" = "project_versions"."version", "created_at" = "project_versions"."created_at", "prerelease" = "project_versions"."prerelease", "project_id" = "project_versions"."project_id", "id" = "project_versions"."id" RETURNING "id"
```
This PR adds a guard to the method that queries in advance the version instead of relying on the upsert mechanism always.
ref #1533
> chore: improve performance project creation

- app/cli/cmd/options/pagination.go
- app/cli/cmd/workflow_list.go
- app/cli/cmd/workflow_workflow_run_describe.go
- app/cli/cmd/workflow_workflow_run_list.go
- app/controlplane/internal/service/attestation.go
- app/controlplane/pkg/biz/workflowrun_integration_test.go
- app/controlplane/pkg/data/ent/utils.go
- app/controlplane/pkg/data/workflowrun.go
- removes eager loading from init method
- fixes project/version loading
refs #1533 
Closes https://github.com/chainloop-dev/chainloop/issues/1536
> chore: improve init performance

- app/controlplane/internal/server/grpc.go
- app/controlplane/internal/usercontext/wrappers.go
As explained inline, the only way to add an existing grpc interceptor in front of kratos' middlewares is to wrap such grpc interceptor as a kratos middleware. That's what I've done in this PR with the prometheus interceptor
Fixes #1582
> feat: move prometheus middleware early in the chain

- docs/package.json
- docs/yarn.lock
Upgrade docusaurus and dependencies to keep CVEs behind.
```shell
> trivy fs --security-checks vuln,config --severity HIGH,CRITICAL .
2024-11-25T19:06:33+01:00	WARN	'--security-checks' is deprecated. Use '--scanners' instead.
2024-11-25T19:06:33+01:00	WARN	'--scanners config' is deprecated. Use '--scanners misconfig' instead. See https://github.com/aquasecurity/trivy/discussions/5586 for the detail.
2024-11-25T19:06:33+01:00	INFO	[vuln] Vulnerability scanning is enabled
2024-11-25T19:06:33+01:00	INFO	[misconfig] Misconfiguration scanning is enabled
2024-11-25T19:06:34+01:00	INFO	[misconfig] Need to update the built-in checks
2024-11-25T19:06:34+01:00	INFO	[misconfig] Downloading the built-in checks...
160.25 KiB / 160.25 KiB [-----------------------------------------------------------] …
```
> chore: upgrade docusaurus

- .github/workflows/build_and_package.yaml
- .github/workflows/release.yaml
https://github.com/chainloop-dev/chainloop/actions/runs/12000221724/job/33449294844 is failing because some secrets are not found (since it's a reusable workflow, they need to be passed in).
> fix: release workflow was missing some secrets

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
This patch removes a duplicated key on the controlplane manifest that was preventing the chart from being deployed.
> fix(chart): Remove duplicated key from deployment

- app/controlplane/configs/config.devel.yaml
- app/controlplane/internal/service/attestation.go
- app/controlplane/pkg/data/referrer.go
- devel/compose.common.yml
There were a couple of issues with storing attestations
- The go-routine was leaving some open connections, this was a regression introduced a couple of days ago.
- But these open connections were happening because of the referrer storage logic that was runnign a very long transaction. This code removes the transaction and simplifies the code.
before we were getting this
```
SELECT count(*) as total, usename AS username, state, query FROM pg_stat_activity where state = 'idle in transaction' group by (username, state, query);
total | username  |        state        | query
-------+-----------+---------------------+-------
50 | chainloop | idle in transaction | begin
```
refs #1533
> chore: improve performance store attestation

- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_init_test.go
- app/controlplane/pkg/biz/workflowcontract.go
- pkg/policies/policy_groups.go
These validations were skipped when schema changed at #1351 . Now it's safe to take them back.
> fix: re-add validations for policy groups

- app/controlplane/pkg/data/orgmetrics.go
when we removed eager loading by default we added a regression on the topWorkflowsEndpoints. This patch adds the project loading on demand.
See how project name is now returned
```
grpcurl -H "Authorization: Bearer $API_TOKEN" -d '{"num_workflows": 5, "time_window": "METRICS_TIME_WINDOW_LAST_30_DAYS"}' -plaintext localhost:9000 controlplane.v1.OrgMetricsService/TopWorkflowsByRunsCount
{
"result": [
{
"workflow": {
"id": "c08f4ffc-2ace-44fe-8939-2c62bf470cd4",
"name": "was-in-project-2-too",
"project": "project-www21222",
"createdAt": "2024-11-29T00:25:58.976858Z",
"runsCount": 2
},
"runsTotalByStatus": [
{
"count": 1,
"status": "RUN_STATUS_EXPIRED"
},
{
"count": 1,
"status": "RUN_STATUS_SUCCEEDED"
}
]
}
]
}
```
> fix(metrics): load project

- app/cli/cmd/version.go
`chainloop version` now returns server version if possible. It also adds `json` output support to the command
```
chainloop version
Client Version: dev
Server Version: dev
```
```
chainloop version -o json
{
"client": "dev",
"server": "dev"
}
```
closes #1619
> feat(cmd): add server version to cli

- app/controlplane/pkg/data/ent/migrate/migrations/20241210063348.sql
- app/controlplane/pkg/data/ent/migrate/migrations/atlas.sum
- app/controlplane/pkg/data/ent/migrate/schema.go
- app/controlplane/pkg/data/ent/schema/workflowrun.go
This patch adds an index on the `workflowrun` table to ease the count of number of workflows by version.
The index places the most selective column on the left side, in this case, `version_id`.
From:
```
Aggregate  (cost=12.91..12.92 rows=1 width=8) (actual time=0.060..0.060 rows=1 loops=1)
->  Bitmap Heap Scan on workflow_runs  (cost=8.89..12.91 rows=1 width=0) (actual time=0.057..0.057 rows=0 loops=1)
Recheck Cond: ((workflow_id = 'eebfe9fe-8b2f-43b9-a405-cb99985cba68'::uuid) AND (version_id = 'b1b1b1b1-b1b1-b1b1-b1b1-b1b1b1b1b1b1'::uuid))
->  BitmapAnd  (cost=8.89..8.89 rows=1 width=0) (actual time=0.045..0.045 rows=0 loops=1)
->  Bitmap Index Scan on workflowrun_workflow_id  (cost=0.00..4.32 rows=4 width=0) (actual time=0.044..0.044 rows=0 loops=1)
Index Cond: (workflow_id = …
```
> feat(workflowrun): Add index to calculate workflow runs per version

- deployment/chainloop/Chart.yaml
- deployment/chainloop/README.md
- deployment/chainloop/templates/_helpers.tpl
- deployment/chainloop/templates/controlplane/secret-config.yaml
- deployment/chainloop/values.yaml
re-enable configuring nats through Helm Chart. This was reverted by mistake
This reverts commit 7210202b9ad38fa3d0a3098a3c77b65406ce5f93.
> re-enable: deployment: support nats configuration

- app/controlplane/cmd/wire_gen.go
- app/controlplane/internal/usercontext/apitoken_middleware_test.go
- app/controlplane/pkg/auditor/events/organization.go
- app/controlplane/pkg/auditor/events/user.go
- app/controlplane/pkg/auditor/logentry.go
- app/controlplane/pkg/biz/auditor.go
- app/controlplane/pkg/biz/membership.go
- app/controlplane/pkg/biz/organization.go
- app/controlplane/pkg/biz/organization_test.go
- app/controlplane/pkg/biz/orginvitation.go
- app/controlplane/pkg/biz/testhelpers/wire_gen.go
new set of events for org management
- orgCreate
- orgInvite
- OrgJoined
- OrgLeft
This PR also adds some logic to allow `event publishers` to define if the event must contain actor or not. That way the system will not send events that do not have the full context
refs #1628
> feat(events): org created/invited

- app/controlplane/pkg/data/ent/migrate/migrations/20241210063348.sql
- app/controlplane/pkg/data/ent/migrate/migrations/atlas.sum
This patch allows the migration tool to run a concurrent index on a table that cannot happen inside a sql transaction.
> fix(transaction): Allow atlas to run a concurrent index on the DB

- app/controlplane/configs/config.devel.yaml
Pushing events to nats is optional but it was not from the dev env POV, this patch changes it.
> fix: do not require nats in dev

- app/cli/cmd/attached_integration_add.go
Fixes #1660 
Also #1515 was incorrect, wrong variable name.
> fix(cli): attached add fix

- app/controlplane/pkg/biz/workflowcontract.go
- app/controlplane/pkg/policies/policyprovider.go
This is an extension of the remote provider feature. Given that they would expose a /policies/validate endpoint that would validate a policy attachment via POST.
```
curl -d '{"policy_attachment":"{\"ref\":\"source-commit\",\"requirements\":[\"foo/bar\"]}"}' -H "Authorization: Bearer $USER_TOKEN" -H "Content-Type: application/json" "localhost:8002/v1/policies/validate"
```
Then it would be used during contract validation to validate any custom metadata in the attachment. For instance, if requirement references were validated:
```shell
> chainloop wf contract update --name myproject-mywf --contract test/my-contract.yaml
ERR validation error: invalid attachment: validation failures: [finding requirement: requirement bar not found]
```
> feat(policies): validate policy attachments against remote provider

- app/controlplane/pkg/policies/policyprovider.go
When validating attachment, it's possible that the policy provider doesn't implement all endpoints and/org methods. This PR adds an additional exception to ignore those cases.
> fix(policies): ignore http 405 as well as 404 

- app/controlplane/cmd/wire.go
- app/controlplane/cmd/wire_gen.go
- app/controlplane/pkg/biz/casbackend.go
- app/controlplane/pkg/biz/casbackend_test.go
- app/controlplane/pkg/biz/testhelpers/database.go
- app/controlplane/pkg/biz/testhelpers/wire.go
- app/controlplane/pkg/biz/testhelpers/wire_gen.go
This patch refactors the dependencies of `CASBackendUseCase` to use an intermediate structure and avoid using the internal configuration object.
Close #1675
> chore(conf): Refactor configuration of use case

- app/cli/cmd/attestation_status.go
- app/cli/cmd/workflow_workflow_run_describe.go
- app/cli/internal/action/attestation_status.go
Adds policy output in `att status` and improves the output in `wf run describe`
- Clearly showing material policies in the context of the wrapping materials
- Attestation policies were moved to the attestation section on the top
- Violations output has been improved with list-type output and coloring
- More condensed view overall
before
after
refs #1616
> feat(cli): improve policy output on describe

- app/cli/internal/action/attestation_push.go
- app/cli/internal/action/attestation_status.go
- pkg/attestation/crafter/crafter.go
- pkg/attestation/renderer/chainloop/v02.go
- pkg/attestation/renderer/renderer.go
Runs the attestation-related policy evaluations in the crafting layer storing it in the state.
This is a pre-requisite for #1685.
In practice nothing changes except that policy-level evaluations happen in `status` and `push` and then the renderer layer just takes the info in the state.
> refactor: run attestation-level policy evaluations in crafting layer

- docs/.syft.yaml
`rtl-detect` library includes some github workflows not relevant to the release, that are polluting the docs SBOM.
This small change instructs `syft` to ignore such paths.
> chore: ignore path not relevant for docs sboms in scanners

- app/controlplane/plugins/README.md
- app/controlplane/plugins/core/webhook/v1/README.md
- app/controlplane/plugins/core/webhook/v1/webhook.go
- app/controlplane/plugins/plugins.go
- devel/integrations.md
Webhook plugin for chainloop.  Sends attestation by default, materials can be sent by adding opt materials=materialtype,materialtype2 on attachment
> feat(plugin):  webhook plugin

- docs/package.json
- docs/yarn.lock
This patch upgrades the version of Docusaurus to version 3.7.0 in an attempt to fix https://github.com/chainloop-dev/chainloop/security/dependabot/79
> chore(docs): Upgrade version of Docusaurus

- .github/workflows/test.yml
- app/controlplane/Dockerfile.migrations
This patch upgrades the version of atlas to version 0.30 since it's the only that is no reporting CVEs.
This will fix: CVE-2024-45338 and CVE-2024-45337 on Chainloop migration image.
> chore(atlas): Upgrade atlas to version 0.30

- app/cli/internal/action/attestation_status.go
String material includes digest but it was not shown in the status/push CLI output, this PR changes that.
```
┌────────────────────────────────────────────────────────────────────────────────────┐
│ Materials                                                                          │
├──────────┬─────────────────────────────────────────────────────────────────────────┤
│ Name     │ material-1736347748127656000                                            │
│ Type     │ STRING                                                                  │
│ Set      │ Yes                                                                     │
│ Required │ No                                                                      │
│ Value    │ 1023544 …
```
> feat(cli): show digest for string material

- .github/workflows/scorecards.yml
This patch moves the environment variables from being a top level on the jobs to individual steps.
It failed in `main` but not in the pull request. Here the job: https://github.com/chainloop-dev/chainloop/actions/runs/12710303333/job/35431292657
Apparently there are restrictions: https://github.com/ossf/scorecard-action#workflow-restrictions
Ref: #1721
> fix(github): Move env from top level to steps

- .github/workflows/scorecards.yml
This patch basically reverts 497feb44c816dcc5589fa3729f2e76288b533c8d since it failed yet again in `main` we need to figure out a different way to do this.
Run: https://github.com/chainloop-dev/chainloop/actions/runs/12710646680/job/35432178119
Error:
```
error processing signature: error sending scorecard results to webapp: http response 400, status: 400 Bad Request, error: {"code":400,"message":"workflow verification failed: scorecard job must only have steps with `uses`, see https://github.com/ossf/scorecard-action#workflow-restrictions for details."}
```
Ref: #1721
> Revert "feat(github): Use regular CLI steps in scorecards workflow (#1723)"

- app/controlplane/pkg/biz/orgmetrics.go
This patch fixes an issue provoked by the prometheus collector if the name of the organization changes and that organization has a registered prometheus registry provoking that the fetch of metrics failed because of an unhandled check on organizations.
> fix(orgmetrics): Prevent org metrics if org does not exist

- .github/workflows/build_and_package.yaml
This PR fixes a bug introduced in https://github.com/chainloop-dev/chainloop/pull/1743 while attesting artifacts in a different job.
Closes https://github.com/chainloop-dev/chainloop/issues/1715
> fix: release job not finding artifacts

- .github/workflows/test.yml
This PR makes sure that only top level packages are tested in the `main-module` target. The rest of the code is already covered by `controlplane`, `artifact-cas` and `cli`.
This should also mitigate those flaky tests that fail from time to time.
Closes #1746
> fix: remove duplicated tests in GH workflow

- .github/workflows/build_and_package.yaml
Archives are too large for attesting. All container images are attested anyways.
Closes https://github.com/chainloop-dev/chainloop/issues/1715
> fix(release): don't attest archives

- .github/workflows/build_and_package.yaml
Fixes the release job by setting a missing env var.
Closes https://github.com/chainloop-dev/chainloop/issues/1715
> fix(releases): add missing chainloop token to job

- .github/workflows/build_and_package.yaml
They are causing failures when applying some policies, since `latest` is translated to the actual digest.
https://github.com/chainloop-dev/chainloop/actions/runs/12933576750/job/36073698762
Related to https://github.com/chainloop-dev/chainloop/issues/1715
> feat(releases): exclude latest tag

- app/controlplane/internal/service/attestation.go
- pkg/attestation/renderer/chainloop/chainloop.go
- pkg/attestation/renderer/chainloop/v02.go
- pkg/attestation/renderer/chainloop/v02_test.go
Follow up for #1756 hiding the compatiblity logic so that callers don't need to use a different interface.
Related to #1755
> chore: hide compatibility logic

- app/cli/cmd/attestation_push.go
The message was showing the wrong flag name
fixes #1763
> fix(cli): wrong error message on bypass

- extras/dagger/main.go
This patch allows the dagger module to receive the `exception-bypass-policy-check` flag to avoid failing the `attestation push` command if any of the policies in the contract hasn't been met.
> feat(dagger): Allow to bypass policy checks on failures

- app/cli/internal/action/attestation_init.go
- app/cli/internal/action/attestation_init_test.go
This simple PR allows empty strings to be passed to arguments whose purpose is material name interpolation.
For example, having this group definition
```yaml
apiVersion: workflowcontract.chainloop.dev/v1
kind: PolicyGroup
metadata:
name: my-group
spec:
inputs:
- name: sbom_name
default: "sbom"
policies:
materials:
- name: "{{ inputs.sbom_name }}"
type: SBOM_SPDX_JSON
policies:
- ref: my-policy
```
When attaching it, there are three possible outcomes:
* Attaching with `sbom_name: mysbom`. It will enforce the material `mysbom` to be present
* Attaching with no arguments. It will enforce the material `sbom` to be present
* Attaching with `sbom_name: ""`. It will behave like a generic policy group, applying the policies to ANY SPDX material.
```bash
➜  chainloop att init --name mywf --project …
```
> feat(policygroups): allow empty strings in material templates

- .github/workflows/docs_deploy.yml
Docs workflow is already generating a CycloneDX report. SPDX is not needed.
> chore: do not generate spdx in docs

- .github/workflows/release.yaml
This patch allows to push to the GitHub release the output of the syft command uploading the generated SBOMs of the built artifacts.
It also fixes a reference to the tag being released.
> chore(ci): Upload SBOMs to GitHub release

- .github/workflows/codeql.yml
- .github/workflows/contracts/chainloop-chainloop-github-release.yaml
- .github/workflows/contracts/chainloop-docs-release.yml
- .github/workflows/contracts/chainloop-vault-codeql.yml
- .github/workflows/contracts/chainloop-vault-helm-package.yml
- .github/workflows/contracts/chainloop-vault-scorecards.yml
- .github/workflows/contracts/release.yml
- .github/workflows/docs_deploy.yml
- .github/workflows/package_chart.yaml
- .github/workflows/scorecards.yml
This patch removes the `chainloop-vault` and `chainloop-docs` as prefix from the workflow names.
> chore(ci): Rename workflows

- pkg/attestation/renderer/renderer.go
- pkg/attestation/renderer/renderer_test.go
Sigstore bundles v3.0 should only contain the leaf certificate used for signing. Intermediates and root certificates must be trusted and provided out-of-band.
https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_bundle.proto#L91
> fix(bundles): do not store full chain

- .github/workflows/release.yaml
This patch moves the GH_TOKEN to the job level to be able to use the gh cli.
> chore(ci): Move env to job level

- .github/workflows/release.yaml
Adds missing output on job to be able to propagate the attestation id to other jobs.
> fix(ci): Fix attestation reference

- .github/workflows/release.yaml
Prevents the upload of artifacts to GitHub release for the moment.
> fix(ci): Prevent release artifact upload

- .github/workflows/release.yaml
Remove not needed status command, since `att push` already shows the status. The command was lacking the `--attestation-id` field for remote attestations.
> fix(workflows): remove status command

- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/release.yaml
- .github/workflows/test.yml
- app/artifact-cas/Dockerfile
- app/artifact-cas/Dockerfile.goreleaser
- app/cli/Dockerfile.goreleaser
- app/controlplane/Dockerfile
- app/controlplane/Dockerfile.goreleaser
- docs/docs/getting-started/attestation-crafting.md
- docs/examples/ci-workflows/github.yaml
- go.mod
There is no newer image for `atlas` yet.
Fixes #1798
> chore: upgrade go to 1.23.6

- .github/workflows/release.yaml
This patch restore the push of sbom materials to GitHub release.
> fix(ci): Restore push of sbom to GitHub release

- app/cli/cmd/output.go
- app/cli/cmd/workflow_workflow_run_describe.go
- app/cli/internal/action/workflow_run_describe.go
This PR switches from DSEE envelope to Bundle format when using `--output attestation` option in `workflow run describe` command.
> chore: dump attestation bundle for "attestation" output format

- .github/workflows/release.yaml
This patch removes a duplicate `attestation push` command being sent on the release process.
> fix(ci): Remove duplicate attestation push command

- .github/workflows/release.yaml
This patch adds missing `GH_TOKEN` environment variable to be able to edit GitHub release notes.
> fix(ci): Add missing GH_TOKEN env

- .vex/artifact-cas.vex.json
- .vex/cli.vex.json
- .vex/controlplane.vex.json
This patch includes three VEX files for the individual projects in the repository: artifacts-cas, cli, and controlplane. These files provide the current status of any CVEs that may affect Chainloop, allowing us to keep the end users informed.
> chore(vex): Include VEX files for projects

- .github/workflows/test.yml
- app/controlplane/Dockerfile.migrations
- common.mk
This patch bumps the version of atlas to `latest` pining its sha. Since there is not a patch version yet, we will wait for version `v0.31.1` to be released to pin to that version fixing CVEs.
> chore(atlas): Upgrade atlas version

- .github/workflows/codeql.yml
- .github/workflows/github_release.yaml
Follow up of https://github.com/chainloop-dev/chainloop/pull/1821 to remove some additional signing keys
Refs #914
> chore: remove cosign for signing attestations

- deployment/chainloop/Chart.yaml
- deployment/chainloop/values.yaml
When using the deprecated format the rendering was failing due to the way the templating in flux merges values entries.
```
helm template foo . --set development=true > /tmp/after.yaml && diff -u /tmp/before.yaml /tmp/after.yaml
Error: execution error at (chainloop/templates/controlplane/secret-config.yaml:75:27): EJBCA server URL is mandatory
```
> fix(chart): do not render CAs when merged

- app/controlplane/internal/service/attestation.go
- app/controlplane/pkg/biz/workflowcontract.go
- app/controlplane/pkg/policies/policyprovider.go
To resolve ambiguity when token doesn't contain the organization data (when using native CI tokens, for example), policy providers should accept a `Chainloop-Organization` header set to the unique name of the organization.
Refs #1817
> feat(integrations): propagate current org name to policy providers

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/controlplane/deployment.yaml
- deployment/chainloop/templates/controlplane/secret-config.yaml
- deployment/chainloop/templates/controlplane/secrets-signer-ca.yaml
This PR fixes secret names in deployment to be RFC 1123 compatible.
Refs #1822 
```diff
445c445
<   generated_jws_hmac_secret: "S1BlTkNvekdxSA=="
---
>   generated_jws_hmac_secret: "MzJRemN5RFlIdg=="
452,453c452,453
<           cert_path: "/sign_secrets_fileCA_0/file_ca.cert"
<           key_path:  "/sign_secrets_fileCA_0/file_ca.key"
---
>           cert_path: "/sign_secrets_fileca_0/file_ca.cert"
>           key_path:  "/sign_secrets_fileca_0/file_ca.key"
477c477
<       generated_jws_hmac_secret: "KPeNCozGqH"
---
>       generated_jws_hmac_secret: "32QzcyDYHv"
502c502
<   name: test-chainloop-controlplane-keyless-fileCA-0
---
>   name: test-chainloop-controlplane-keyless-fileca-0
1614c1614
<         checksum/secret-config: b1dee35ccd0a15f584e519cb49cfd035ff7789f938f0a2b88a79956e364ff0d1 …
```
> fix secret names

- .github/workflows/contracts/release.yml
This patch replaces the custom policy `sbom-quality` for the builtin one.
> chore(contract): Use builtin policy group

- app/cli/cmd/attestation_add.go
To support adding contractless materials by providing its name alongside the kind. The underlying code actually supported it.
Closes #1699
> feat: allow passing kind and name at the same time

- deployment/chainloop/templates/controlplane/configmap.yaml
Fixes a typo in the config field name "timestamp_authorities"
```diff
580c580
<     timestampAuthorities:
---
>     timestamp_authorities:
595,596c595,596
```
> fix: config field name

- app/cli/cmd/attestation_status.go
- app/cli/internal/action/attestation_status.go
Add a new row to the status table to show the timestamp authority if configured:
```
┌───────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ Initialized At            │ 21 Feb 25 13:04 UTC                                                     │
├───────────────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ Attestation ID            │ ca757e20-2a8d-4632-8761-33a4d8a13b64                                    │
│ Digest                    │ sha256:4b49ac919d9858d47990400e5a9430c0a4a948fda1d8a54496e2b8e589096dd5 │
│ Organization              │ my-org                                                                  │
│ Name                      │ mywf …
```
> chore: show timestamp authority in att status

- .github/workflows/release.yaml
This patch modifies the attestation hash being passed from `finish_attestation` job to `modify_release_notes` an injecting it an environment variable of the needed step.
> fix(release-notes): Passes correctly the attestation hash to release notes

- app/cli/cmd/attestation_push.go
- app/cli/internal/action/attestation_push.go
- docs/docs/guides/signserver/signserver.md
- pkg/attestation/signer/signer.go
- pkg/attestation/signer/signserver/signserver.go
This PR allows to configure SignServer for client certificate authentication, as described at https://docs.keyfactor.com/signserver/latest/client-certificate-authorizer
It also removes unused flags in the SignServer integration logic.
Given that End Entities have been created in EJBCA, and SignServer Sign Worker has been configured properly to accept payloads from those users, attestation can be signed and pushed this way:
```shell
> chainloop att push --key signserver://localhost:8443/PlainSigner --signserver-ca-path ../keyfactor/localhost-chain.pem --signserver-client-cert ../keyfactor/clientcert/Chainloop.pem
┌───────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ Initialized At            │ 26 Feb 25 18:09 UTC …
```
> feat(signing): support SignServer authentication with client certificate

- app/cli/cmd/attestation_add.go
- pkg/resourceloader/resourceloader.go
This patch enhances the `attestation add` command by allowing it to accept HTTP(S) URLs. When a URL is provided, the CLI downloads the file and uses it for attestation, eliminating the need for users to have the file locally. Internally, the CLI stores the downloaded file in a temporary directory, preserving its base name for material verification before pushing it to the configured CAS.
The existing behavior of loading files from the local file system remains unchanged.
A few examples:
Loading a GitLab Security Report from the file system:
```
$ chainloop attestation add --value ./pkg/attestation/crafter/materials/testdata/gl-secret-detection-report.json
INF material kind detected kind=GITLAB_SECURITY_REPORT
INF material added to attestation …
```
> feat(cli): Allow to load materials from external sources

- app/cli/cmd/attestation_push.go
- app/cli/internal/action/attestation_push.go
- go.mod
- go.sum
- pkg/attestation/signer/signer.go
- pkg/attestation/signer/signserver/signserver.go
This PR adds a `--signserver-client-pass` flag to optionally provide a passphrase for the SignServer client certificate. It supports RFC 1423 and PKCS#8 encryption methods.
When not used, the provided PEM is assumed not encrypted.
Full command:
```
> chainloop att push --key signserver://localhost:8443/PlainSigner --signserver-ca-path localhost-chain.pem --signserver-client-cert client-user.pem --signserver-client-pass $SIGNSERVER_PASS
```
> feat(signserver): support encrypted PEM in TLS connection with SignServer

- app/controlplane/api/controlplane/v1/response_messages.pb.go
- app/controlplane/api/controlplane/v1/response_messages.proto
- app/controlplane/api/controlplane/v1/response_messages_errors.pb.go
- app/controlplane/api/gen/frontend/controlplane/v1/response_messages.ts
- app/controlplane/internal/usercontext/attjwtmiddleware/attmiddleware.go
This PR allows exposing the auth error returned by a delegated auth provider. It also improves the output format to make it more user friendly.
Expired token
Ambiguous registration
> feat: expose error from federated oidc provider

- docs/docs/quickstart.mdx
- docs/examples/quickstart/sbom.json
This patch reduces the size of example SBOM being used in the quickstart.
> fix(docs): Reduce size of example SBOM

- pkg/resourceloader/resourceloader.go
This pull request includes an improvement to the `loadFromURL` function in the `pkg/resourceloader/resourceloader.go` file. The change ensures better error handling when loading content from a URL.
Improvements to error handling:
* [`pkg/resourceloader/resourceloader.go`](diffhunk://#diff-6844a78ff7547fa02662f82d0df7c827e08f5a513eb4e4cf4f9b07c3c766c0b9R76-R88): Added a check to ensure the HTTP response status is OK before attempting to read the response body. If the status is not OK, an error is returned with the status message.
> chore(pkg): Only download material if 200

- .github/workflows/release.yaml
This PR adds a flag to skip new file catalogers introduced in Syft 1.20.0. Chainloop binaries don't have the required metadata (purl, author ...) for NTIA . While we figure it out, we'll just go back to the behaviour in Syft 1.19.0
I've also made sure that the job fails when there is an error code != 0 in `attestation push`
> fix(release): skip file cataloger in syft scans

- app/controlplane/internal/service/auth.go
When there is a callback error (ie, when SSO is delegated to Auth0), this PR redirects to the configured login URL with the provided error message from the Auth provider.
> chore: redirect to login URL with error message

- app/controlplane/internal/service/auth.go
- app/controlplane/internal/service/auth_test.go
We want to redirect only in case there is a dedicated login page, otherwise we can incur in login loops.
> chore: only redirect if login URL is overridden

- app/cli/cmd/workflow_workflow_run_list.go
This patch fixes and issue with the `wf run ls` command where the columns were not being filled properly due to a missing value regarding the prerelease of a project version.
Before:
```
$ chainloop wf run ls
┌──────────────────────────────────────┬───────────────────────┬───────────────────────┬─────────────┬─────────────────────┬─────────────────┬────────┐
│ ID                                   │ WORKFLOW              │ VERSION               │ PRERELEASE  │ STATE               │ CREATED AT      │ RUNNER │
├──────────────────────────────────────┼───────────────────────┼───────────────────────┼─────────────┼─────────────────────┼─────────────────┼────────┤
│ e903906d-e937-4bf0-828a-5bc6054e7324 │ myproject/mywf        │ v0.0.1                │ success     │ 05 Mar 25 09:49 UTC │ …
```
> fix(cli): Add missing prerelease value to wf run ls command

- app/cli/cmd/workflow_workflow_run_list.go
This patch removes the `Prerelease` column from the `wf run ls` command to make it consistent with the rest of commands.
Follow up of comment: https://github.com/chainloop-dev/chainloop/pull/1879#discussion_r1981265887
> chore(cli): Remove Prerelease column on wf run ls

- app/controlplane/internal/server/grpc.go
- app/controlplane/internal/usercontext/attjwtmiddleware/attmiddleware.go
- app/controlplane/internal/usercontext/currentuser_middleware.go
This PR adds support to perform attestations with an user token, the change basically includes two things
1 - Chain a user-token authenticator to the JWTMulti cascade-based middleware we use during attestations
2 - Add an additional middleware to set the required user and org context required in the service layer.
About 2: I managed to implement it basically reusing the existing middlewares just doing wrap calling, additionally we do an authorization check to make sure read only users can not attest in the org.
I have three orgs with organization-2 set as default client-side
```
go run main.go org ls
WRN Both user credentials and $CHAINLOOP_TOKEN set. Ignoring $CHAINLOOP_TOKEN.
┌────────────────┬─────────┬─────────┬───────┬─────────────────────────┬────── …
```
> feat: allow to perform attestations with user token

- pkg/attestation/crafter/runners/azurepipeline.go
- pkg/attestation/crafter/runners/azurepipeline_test.go
Some of them are not available in classic pipelines, and some of them are only available in classic pipelines. So I'm making them optional to avoid undesired failures.
> fix: make some Azure pipeline env vars optional

- app/cli/cmd/attestation.go
- app/cli/cmd/root.go
This is a follow up of #1003 to pass the user token to the attestation commands if the API token hasn't been provided via env var nor command line.
I've also removed the duplicated `--token` flag.
The affected commands (attestations) will now prompt the user to confirm the operation, since it will be performed against the "current" organization, which might vary depending on the `chainloop org set` command. The confirmation can be bypassed with the `-y` or `--yes` flag
Without CHAINLOOP_TOKEN:
```bash
✗ go run app/cli/main.go att init --workflow mywf --project myproject --replace
This command is will run against the organization "my-org"
Please confirm to continue y/N
n
ERR command canceled by user
```
```bash
✗ go run app/cli/main.go att init --workflow …
```
> chore: use user token for attestation commands

- app/cli/cmd/attestation_init.go
- app/cli/cmd/root.go
Follow up on #1003 to only ask for confirmation on `att init` instead of all attestation commands.
> fix: only ask for confirmation on att init

- app/controlplane/pkg/data/workflowrun.go
When using old CLI versions, only DSSE envelope is available. There is a bug introduced in #1890 that prevents it from being stored in the WorkflowRun table. This PR fixes it, so that it's backwards compatible.
> fix: Store DSSE envelope when bundle is not available

- app/controlplane/pkg/biz/user.go
- app/controlplane/pkg/data/ent/mutation.go
- app/controlplane/pkg/data/ent/schema/user.go
- app/controlplane/pkg/data/ent/user.go
- app/controlplane/pkg/data/ent/user_create.go
- app/controlplane/pkg/data/user.go
This change allows the HasRestrictedAccess field to represent three states: true, false, and nil.
A missing value (nil) is fundamentally different from false, which is why the Nillable option was added.
This change only produces modification in the generated code, the SQL remains unchanged.
> feat(users): Make field HasRestrictedAccess nillable

- pkg/casclient/uploader.go
The CAS backend will close the stream if it detects a duplicated upload (to save resources). In that case, the returned EOF must be ignored. This PR fixes a race condition where that EOF was causing an error.
Related to #1849
> fix(uploads): ignore EOF when sending finish write message

- .github/workflows/release.yaml
This patch reverts the PR #1873 since the underlaying NTIA policy has been modified to allow local files.
> chore(ci): Include all catalogers in syft analysis

- app/controlplane/pkg/biz/useraccess_syncer.go
This patch adjusts the log position for user access sync to minimize noise in stdout.
> chore(users): Move logs to reduce noise

- app/controlplane/api/buf.gen.yaml
~Apparently there was a lot of changes regarding code generation. Probably because of a lack of rebase in the most recent PR.~
Last night, the JSON schema plugin generator was upgraded to v0.3.0, introducing changes that altered our current generation process. For now, I’ve pinned it to the previous version v0.2.0 until we assess the impact.
> chore(gen): Run code generation

- .github/workflows/utils/bump-chart-and-dagger-version.sh
- .github/workflows/utils/bump-project-version.sh
This patch updates the version bumper scripts for both the Chainloop project version and the Chart version. It adds support for release candidates (-rc prefix) and minor versions.
Note: Major versions are NOT supported by this script—we’ll need a different solution for those.
> feat(ci): Modify version bumper script to allow release candidates

- .github/workflows/codeql.yml
- .github/workflows/github_release.yaml
- .github/workflows/package_chart.yaml
This patch updates the CI pipelines to reference the latest version of the Chainloop CLI, v1.0.0-rc.2
> chore(ci): Point to latest version of CLI in CI workflows 

- .goreleaser.yml
To simplify the installation of Chainloop’s CLI, we want to include a generic binary in GitHub releases that can be downloaded using `latest`. To achieve this, we must expose the binaries to the GitHub release without the version.
The checksums are updated, from this:
```
a0b4760007e44d64dc44afa56829e1a108088078fb495217db3ad8f0ba830864  chainloop-cli-1.0.0-rc.2-SNAPSHOT-82578394-darwin-amd64.tar.gz
b80d265f182d331236b214a1527119e6a4cb13fbd67580950ad1f45fd9fc09e7  chainloop-cli-1.0.0-rc.2-SNAPSHOT-82578394-darwin-arm64.tar.gz
47dbb136cbd589c0e5f69625d819f2e0369d6a3b3bae433b40769c35ed8c100e  chainloop-cli-1.0.0-rc.2-SNAPSHOT-82578394-linux-amd64.tar.gz
3e1f3beea847a7c50eabd158de576c8ebc07e4f140084ba285a62ffe7f822546  chainloop-cli-1.0.0-rc.2-SNAPSHOT-82578394-linux-arm64.tar.gz
```
To this: …
> feat(ci): Release binaries without version

- .github/workflows/release.yaml
This patch adds a missing `attestation-id` on the release process.
> fix(release): Add missing attestation id on attestation

- docs/static/install.sh
This patch updates the `install.sh` script to support both legacy and modern GitHub release formats for the Chainloop CLI.
In newer releases (starting from version `v1.0.0-rc.3`), the CLI is distributed as a plain binary without a version in the filename and without a `.tar.gz` archive. The script now detects whether a given release is legacy or modern and downloads the appropriate artifact accordingly—either the `.tar.gz` archive for older versions or the standalone binary for newer ones.
For modern releases, the latest version can be downloaded using the following URL:
```
https://github.com/chainloop-dev/chainloop/releases/latest/download/chainloop-OS-ARCH
```
Please note that legacy and modern GitHub releases referrers to the way Chainloop pushes artifacts to GitHub's releases. …
> chore(install): Modify install.sh to support new GitHub release artifacts

- .goreleaser.yml
Since we’re already publishing the plain binaries in the GitHub release, there’s no need to continue uploading them in .tar.gz format. This patch removes the .tar.gz archives.
> chore(ci): Remove the creation of .tar.gz on releases

- .github/workflows/release.yaml
This patch corrects the path to the attestation digest, ensuring it is properly propagated for inclusion in the GitHub release notes.
> fix(release-notes): Add missing path to get attestation digest

- .github/workflows/docs_deploy.yml
- .github/workflows/package_chart.yaml
- .github/workflows/scorecards.yml
- .github/workflows/sync_contracts.yml
This patch changes the pinned version of labs so it includes the latest changes regarding the install.sh before a new release of Chainloop goes out.
> chore(ci): Change pinned version of labs

- .github/workflows/release.yaml
This patch generates a SLSA attestation that includes the binaries and Docker images produced by GoReleaser. The final attestation is derived from a checksum file with the following format:
```
984da8d576b3bd9f13bb33dedc29a11bd36752adaf7e1d1ff9d784fd2fba17c8 *chainloop-plugin-discord-webhook
9ecf812d8f462c8efc9b96b2b0dd1431d79e96dbe1b61479b909937902a0ded4 *chainloop-plugin-smtp
75cf34ce56f0299b27bf57bc1aeba78f3a1fb04c03c70365c541bd940a5fc86d *chainloop-plugin-dependency-track
83f69c22625c13b789ee47b93c648d82780b2a45e9a183cf72893f5e83d2fc7c *artifact-cas
39149252e9f42188e7e1d6808992b1b45a74ca0e3b23b7323852e0cd7822b4d5 *control-plane
49c35c45be38cd936b57990fc440f502d49be2c80048ab901eaa48f2178d237d *chainloop-linux-arm64
050fed0589a73c06fc2c868c81ead4526f1d46dd95f4833702a19d7687ceff52 …
```
> chore(ci): Generate SLSA attestation

- .github/workflows/codeql.yml
- .github/workflows/github_release.yaml
- .github/workflows/package_chart.yaml
This patch points to the latest version available of the `install.sh` at the moment.
> chore(ci): Point to latest version of install.sh

- .github/workflows/contracts/release.yml
This patch modifies the chainloop release contract so it includes the policy group that maps the SLSA framework.
> feat(contract): Update chainloop release contract

- .github/workflows/release.yaml
This patch adds the source code of the GitHub release to Chainloop's attestation.
Close: #1958
> feat(ci): Include source code to chainloop attestation

- .github/workflows/release.yaml
This patch updates the syntax used to assign the attestation sha to GITHUB_OUTPUT, which passes it to the next job for updating the release notes.
> fix(ci): Modify condition that assigns attestations hash

- .github/workflows/contracts/chainloop-vault-release.yml
This patch renames the contract from `release` to `chainloop-vault-release`, which is the actual contract used by the `release` workflow in Chainloop. Previously, even though the contract was being updated, it had no effect—because no workflow was actually linked to it.
> chore(contract): Modify name of contract

- .github/workflows/contracts/chainloop-vault-release.yml
- .github/workflows/release.yaml
his patch updates the `chainloop-vault-release` contract to include an annotation on the `slsa-attestation` material. The annotation contains a link to the GitHub attestation generated in the previous step.
Defining the material in the contract is necessary because the system does not support adding annotations to materials dynamically—they must be explicitly declared in the contract.
> chore(ci): Include SLSA attestation link on chainloop attestation

- app/cli/internal/action/attestation_status.go
This patch fixes the attestation result logic to include annotations from the attestation materials. Previously, although the annotations were present in the final attestation, they were not reflected in the attestation result, causing it to display NOT SET.
Before:
```
┌───────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ Initialized At            │ 11 Apr 25 09:49 UTC                                                     │
├───────────────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ Attestation ID            │ 4f177397-a8f8-4ca8-9ad8-82d141c8dd2c                                    │
│ Digest                    │ sha256:fffc6326efc1503972c36686c5f4a9ed587faab3ba05f08c86659b736 …
```
> fix(attestation-result): Include material annotations to attestation results

- app/controlplane/pkg/data/ent/schema/workflowrun.go
- app/controlplane/pkg/data/ent/workflowrun.go
- app/controlplane/pkg/data/ent/workflowrun/workflowrun.go
Deprecated fields were hiding this value by default
> chore: remove deprecated option

- app/controlplane/pkg/biz/workflowrun_integration_test.go
it seems that in fact we updated tests to follow the new behavior :)
> fix: tests envelope retrieval 

- app/controlplane/Dockerfile.migrations
- common.mk
This should fix https://github.com/advisories/GHSA-m454-3xv7-qj85
> chore: upgrade atlas

- pkg/attestation/renderer/chainloop/chainloop.go
- pkg/attestation/renderer/chainloop/v02.go
Add reference source component to normalized material
> feat: add main component info

- app/controlplane/Dockerfile.migrations
- common.mk
This patch upgrades Atlas to `v0.32.1-819f32c-canary` to address the CVE GHSA-vvgc-356p-c3xw
It also reverts the Atlas version in the common script to the previously working one, as the updated version caused issues in that context.
New version of Atlas does not show any CVE at this moment:
```
$ grype arigaio/atlas@sha256:5b52e74c938e2e32df081be435501d0de8f7a019840d7cc844997e6af0061bc1
✔ Loaded image                                                                                                                        arigaio/atlas@sha256:5b52e74c938e2e32df081be435501d0de8f7a019840d7cc844997e6af0061bc1
✔ Parsed image …
```
> chore(migrations): Bump atlas migration container image

- pkg/attestation/crafter/materials/csaf.go
- pkg/attestation/crafter/materials/cyclonedxjson.go
- pkg/attestation/crafter/materials/cyclonedxjson_test.go
- pkg/attestation/crafter/materials/materials.go
- pkg/attestation/crafter/materials/sarif.go
- pkg/attestation/crafter/materials/spdxjson.go
This PR adds tool information (name and version) to generic type materials (SARIF, CDX, SPDX, CSAF). It does a best effort to find the relevant properties.
The values are as annotations with names:
* chainloop.material.tool-name
* chainloop.material.tool-version 
Examples:
```
┌───────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ Initialized At            │ 23 Apr 25 23:38 UTC                                                     │
├───────────────────────────┼─────────────────────────────────────────────────────────────────────────┤
│ Attestation ID            │ 9d702308-715c-487a-a1c4-907755651776                                    │
│ Digest                    │ …
```
> feat(materials): add tool information

- pkg/attestation/crafter/runners/githubaction.go
- pkg/attestation/crafter/runners/oidc/github.go
In order to support organization repositories OIDC token on GitHub we need to check for different actor - this PR introduces the change allowing specifying multiple expected audiences.
> Add support to organization repos with GitHub OIDC token

- app/cli/cmd/workflow_workflow_run_list.go
- app/cli/documentation/cli-reference.mdx
- app/cli/documentation/generate.go
- app/controlplane/api/workflowcontract/v1/crafting_schema_validations.go
- go.mod
- go.sum
This patch adds a script that generates a single `.mdx` file from the CLI command documentation. Each command becomes a main section, with its subcommands included as subsections.
It's integrated in the main `make generate` command.
> feat(cli): Generate CLI documentation

- app/controlplane/cmd/wire_gen.go
- app/controlplane/internal/usercontext/apitoken_middleware_test.go
- app/controlplane/pkg/auditor/events/apitoken.go
- app/controlplane/pkg/auditor/events/apitoken_test.go
- app/controlplane/pkg/auditor/events/testdata/apitokens/api_token_created.json
- app/controlplane/pkg/auditor/events/testdata/apitokens/api_token_created_with_description.json
- app/controlplane/pkg/auditor/events/testdata/apitokens/api_token_created_with_expiration_date.json
- app/controlplane/pkg/auditor/events/testdata/apitokens/api_token_revoked.json
- app/controlplane/pkg/biz/apitoken.go
- app/controlplane/pkg/biz/auditor.go
- app/controlplane/pkg/biz/testhelpers/wire_gen.go
This patch instruments the API Token entity to include audit logs regarding its operations.
> chore(audit): Instrument API Tokens with event auditor

- pkg/policies/policies.go
- pkg/policies/policies_test.go
- pkg/templates/templates.go
This PR fixes the case when a required argument gets an interpolated value, and the interpolation variables are not passed. In this case, if it renders to an empty string, should be still considered missing, thus failing the validation.
This one should fail if `foo` value is not provided and `policyfoo` is required by the policy.
```
apiVersion: workflowcontract.chainloop.dev/v1
kind: PolicyGroup
metadata:
name: my-group
spec:
inputs:
- name: foo
policies:
attestation:
- ref: my-policy
with: 
policyfoo: "{{ inputs.foo }}"
```
Fixes #2012
> fix(policies): fail on required arguments that are empty after applying interpolations

- pkg/attestation/crafter/runner.go
- pkg/attestation/crafter/runners/githubaction.go
- pkg/attestation/crafter/runners/gitlabpipeline.go
- pkg/attestation/crafter/runners/gitlabpipeline_test.go
- pkg/attestation/crafter/runners/oidc/gitlab.go
- pkg/attestation/crafter/runners/oidc/gitlab_test.go
- pkg/attestation/crafter/runners/oidc/oidc.go
- pkg/attestation/crafter/runners/runners.go
This PR introduced checking for authentication information coming from Gitlab.
> Support Gitlab authentication information

- docs/examples/contracts/slsa/github.yaml
Change example to use Chainloop attestations for SLSA checks.
> feat: change example for SLSA

- .github/workflows/test.yml
- app/cli/cmd/attestation_init.go
- app/cli/internal/action/attestation_init.go
This reverts commit 5a3ccd96227fdbe9b950a9b90805f398d10620fe from this pr https://github.com/chainloop-dev/chainloop/pull/1974
this this is blocking doing attestations using federated tokens.
> Revert "feat(attestation): update contracts on attestation init (#1974)"

- .chainloop.yml
This patch modifies the version on `.chainloop.yaml` file to prepare for `v1.0.0`.
> chore(.chainloop): Prepare for v1.0.0

- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/release.yaml
- .github/workflows/test.yml
Tests are taking longer because cache action has been deprecated. This upgrade fixes the issue
> chore: upgrade setup-go

- .github/workflows/utils/bump-chart-and-dagger-version.sh
- extras/dagger/main.go
During the latest changes in the script we added a regression that was preventing the dagger module from being bumped.
This fixes it.
Fixes #2051
> fix: dagger module bump

- .github/workflows/utils/bump-project-version.sh
When bumping the minor version, we should reset the patch version to `0`.
> chore: reset patch when bumping minor version

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/controlplane/configmap.yaml
Before
```
helm template foo ./chainloop --set development=true | grep cas_server -A 3
cas_server:
grpc:
addr: foo-chainloop-cas-api:%!f(json.Number=)
insecure: true
```
after
```
helm template foo ./chainloop --set development=true | grep cas_server -A 3
cas_server:
grpc:
addr: foo-chainloop-cas-api:80
insecure: true
```
Fixes #2067
> fix(chart): render in Helm 3.18

- app/controlplane/pkg/data/workflowrun.go
Another follow up on #2070. This time we maintain untouched the original query, but return early if there are no workflows in the organization.
The resulting query plans are (with millions of records):
For the first query (workflows)
```
Limit  (cost=0.16..4.17 rows=1 width=16) (actual time=0.829..0.830 rows=0 loops=1)
->  Index Scan using workflow_organization_id on workflows  (cost=0.16..4.17 rows=1 width=16) (actual time=0.828..0.828 rows=0 loops=1)
Index Cond: (organization_id = '4b1ec0ee-e079-4307-b532-e038cb1fa76a'::uuid)
Planning Time: 0.855 ms
Execution Time: 0.882 ms
```
For the second query (workflow runs)
```
Limit  (cost=0.86..2.47 rows=26 width=236) (actual time=0.079..0.092 rows=26 loops=1)
->  Nested Loop  (cost=0.86..124127.02 rows=2000544 width=236) (actual …
```
> fix: optimize workflow runs by returning early if there are no workflows

- .github/workflows/release.yaml
This patch modifies the release workflow to include the names of the materials being attested. See this example with the latest released version to see the expected output:
```
Reading from: /Users/javirln/Development/projects/chainloop/platform/backend/artifacts.json
============================================
Image: ghcr.io/chainloop-dev/chainloop/control-plane-migrations:v1.4.3-amd64
Container name: control-plane-migrations-amd64
SBOM name: control-plane-migrations-sbom-amd64
Image: ghcr.io/chainloop-dev/chainloop/control-plane-migrations:v1.4.3-arm64
Container name: control-plane-migrations-arm64
SBOM name: control-plane-migrations-sbom-arm64
Image: ghcr.io/chainloop-dev/chainloop/artifact-cas:v1.4.3-amd64
Container name: artifact-cas-amd64
SBOM name: artifact-cas-sbom-amd64
Image: …
```
> chore(workflows): Include attestation name on release workflow

- .github/workflows/release.yaml
Fixes the name of the material being generated so it does not contain any colons.
> fix(workflow): Material name

- app/controlplane/configs/config.devel.yaml
- docs/examples/quickstart/quickstart-contract-oss.yaml
- docs/examples/quickstart/quickstart-contract.yaml
The contract shouldn't have any non-local policy, since policy provider is not configured by default. 
Closes #2076
> fix: add contract without policies for getting started

- .github/workflows/release.yaml
This pull request makes a small correction in the `.github/workflows/release.yaml` file, updating the syntax for accessing the `attestation_sha` output from the `attestation_push` step.
* [`.github/workflows/release.yaml`](diffhunk://#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaL189-R189): Changed `steps.attestation_push.attestation_sha` to `steps.attestation_push.outputs.attestation_sha` to correctly reference the output.
> fix(release-notes): Fix release outputs

- deployment/chainloop/Chart.yaml
- deployment/chainloop/templates/controlplane/secret-config.yaml
```diff
helm template foo chainloop --set development=true > /tmp/after.yaml && diff -u /tmp/before.yaml /tmp/after.yaml
--- /tmp/before.yaml	2025-06-05 17:30:30
+++ /tmp/after.yaml	2025-06-05 17:37:29
@@ -442,7 +442,7 @@
type: Opaque
data:
-  generated_jws_hmac_secret: "Mk1JRk1KRFlIWg=="
+  generated_jws_hmac_secret: "WlVYM25DQUpJZmJDcDIxSGlWMTYxZDc5dDV6ZEZCSU4="
db_migrate_source: "cG9zdGdyZXM6Ly9jaGFpbmxvb3A6Y2hhaW5sb29wcHdkQGZvby1wb3N0Z3Jlc3FsOjU0MzIvY2hhaW5sb29wLWNwP3NzbG1vZGU9ZGlzYWJsZQ=="
stringData:
@@ -466,7 +466,7 @@
-      generated_jws_hmac_secret: "2MIFMJDYHZ"
+      generated_jws_hmac_secret: "ZUX3nCAJIfbCp21HiV161d79t5zdFBIN"
```
Thanks @snieguu for the report
> fix(chart): increase auto-generated entropy

- app/controlplane/pkg/biz/apitoken.go
This pull request includes a small change to the `DefaultAuthzPolicies` configuration in the `NewAPITokenUseCase` function. The change adds the ability to list workflows by including `authz.PolicyWorkflowList` in the default authorization policies.
Workflow list commands works as expected:
```
$ chainloop --insecure wf ls --full
WRN Both user credentials and $CHAINLOOP_TOKEN set. Ignoring $CHAINLOOP_TOKEN.
┌────────────┬─────────────┬────────────┬──────┬───────────────────────┬────────┬─────────────┬─────────────────┬─────────────────────┐
│ NAME       │ DESCRIPTION │ PROJECT    │ TEAM │ CONTRACT              │ PUBLIC │ RUNNER      │ LAST RUN STATUS │ CREATED AT          │
├────────────┼─────────────┼────────────┼──────┼───────────────────────┼────────┼── …
```
> feat(api-token): Allow API tokens to list workflows

- app/cli/internal/action/attestation_push.go
> feat(attestation): allow arbitrary annotations at runtime

- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/release.yaml
- .github/workflows/test.yml
- app/artifact-cas/Dockerfile
- app/artifact-cas/Dockerfile.goreleaser
- app/cli/Dockerfile.goreleaser
- app/controlplane/Dockerfile
- app/controlplane/Dockerfile.goreleaser
- app/controlplane/Dockerfile.migrations
- common.mk
- docs/examples/ci-workflows/github.yaml
- go.mod
This patch bumps the Golang version to 1.24.4 fixing several CVEs as well as the Atlas version to v0.35.0 which also fixes a few CVEs.
> chore(golang): Bump version of Golang to 1.24.4 and fix CVEs

- app/controlplane/pkg/authz/authz.go
Simple PR to implement Project Viewer permissions.
Note that many permissions are inherited from the "Org Member" role, although RBAC is applied when needed.
I've also removed OrgMetricsRead, which is not needed, since it's assumed from the organization role.
Example command with **Project Admin** role on project "proj13":
```bash
➜ cldev wf create --project proj13 --name wf
┌──────┬─────────┬───────────┬────────┬────────┬─────────────────┬─────────────────────┐
│ NAME │ PROJECT │ CONTRACT  │ PUBLIC │ RUNNER │ LAST RUN STATUS │ CREATED AT          │
├──────┼─────────┼───────────┼────────┼────────┼─────────────────┼─────────────────────┤
│ wf   │ proj13  │ proj13-wf │ false  │        │                 │ 25 Jun 25 09:33 UTC │ …
```
> feat(rbac): implement Project Viewer role

- pkg/attestation/crafter/crafter.go
This PR implements material annotation support matching the existing attestation annotation behavior:
```
a) we do not allow overriding values that come from the contract
b) we allow adding annotations that are not defined in the contract
```
Closes #1976
> feat(attestation): allow arbitrary annotations in materials

- app/cli/cmd/attestation_init.go
- app/cli/internal/action/attestation_init.go
Adds warning when outdated contract revisions are used during attestation:
```
WRN Newer contract revision available - latest revision: 3
```
Closes #1910
> feat(attestation): add warning when outdated contract is used

- app/cli/internal/action/attestation_init.go
This is a regression introduced during the token info retrieval
Fixes #2160
> fix(cli): do not fail on federated tokens

- app/controlplane/pkg/biz/membership.go
- app/controlplane/pkg/biz/workflow.go
- app/controlplane/pkg/data/membership.go
Initially, the field was meant to be deprecated, but it's worth maintaining it for future queries for org memberships, that include all org resource memberships.
> chore(rbac): Set organization ID in all memberships

- app/controlplane/pkg/authz/authz.go
This pull request modifies the `RolesMap` in the `authz.go` file to streamline the policies associated with roles by removing specific group and membership-related policies.
Changes to role policies:
* `app/controlplane/pkg/authz/authz.go`: Removed the following policies from the `RolesMap` definition:
- `PolicyGroupList`
- `PolicyGroupRead`
- `PolicyGroupListMemberships`
- `PolicyProjectListMemberships`
> chore(authz): Cleanup roles for org viewer

- app/controlplane/internal/service/workflowrun.go
- app/controlplane/pkg/data/referrer.go
Include referrers that belong to public worklfows. Also don't apply RBAC on workflow runs from public workflows.
> chore(rbac): return graph nodes for public workflows

- app/controlplane/pkg/biz/group_integration_test.go
- app/controlplane/pkg/data/group.go
This patch modifies the query that lists the groups so the filters are applied in an OR manner rather than AND by default.
It also updates the tests to reflect the changes.
> fix(group): List group options

- app/controlplane/pkg/authz/authz.go
There was a conflict in permissions and Organization/ListMembers was using the same policy as Organization/Read.
This PR fixes it and adds missing resources to the list or managed resources.
Now only org admins/owners and members can list memberships.
> fix(rbac): viewers shouldn't see org members

- app/cli/cmd/root.go
- app/cli/pkg/plugins/manager.go
This PR adds improvement error reporting for CLI plugins - https://github.com/chainloop-dev/chainloop/issues/2210. 
I would use a logger, but the problem is that in order for the plugins mechanism to be able to expand the Cobra command I'm loading the plugins before the logger is actually initialized, so before the flags are passed to the CLI command. That means at that point I don't know the user wants a debug, info or any other log level. 
If we agree on the change the response from the CLI looks as follows:
```sh
2025-07-07T23:18:29.823+0200 [WARN]  plugin: plugin failed to exit gracefully
failed to load plugin: /Users/gro/Library/Application Support/chainloop/plugins/chainloop - reason: failed to create RPC client: Unrecognized remote plugin message: Chainloop Command Line Interface …
```
> Improve error reporting from plugins loading

- app/controlplane/pkg/authz/authz.go
RBAC check is done at service level, but routes must be enabled for OrgViewers, since they can be ProjectAdmins
> fix(rbac): allow OrgViewer to access project actions

- app/controlplane/pkg/biz/workflow_integration_test.go
- app/controlplane/pkg/data/projectversion.go
- app/controlplane/pkg/data/workflow.go
This PR makes sure there is a default version for any new project created through a workflow flow.
before this, only during attestations the project would have had a version
> feat: add default version when workflow is created

- app/cli/cmd/plugins.go
This PR adjusts the output of the:
```
chainloop config plugin describe --name platform
```
To something like this:
```
┌──────────────────────────────────────────────────────────────────┐
│ Plugin: platform                                                 │
├─────────────┬────────────────────────────────────────────────────┤
│ Version     │ v0.218.0-43-ge9b96e4e                              │
├─────────────┼────────────────────────────────────────────────────┤
│ Description │ Chainloop platform plugin for runner context data. │
├─────────────┼────────────────────────────────────────────────────┤
│ Commands    │ 1 command(s)                                       │
└─────────────┴────────────────────────────────────────────────────┘ …
```
> Adjust plugin describe command output

- app/controlplane/pkg/biz/group.go
- app/controlplane/pkg/biz/group_integration_test.go
This patch prevents users with the role org viewer to become group maintainers.
> feat(groups): Prevent user with org viewer role to become group maintainers

- deployment/chainloop/README.md
Update instructions for modern setups
Fixes #2094
> chore: update deployment file CA instructions

- app/controlplane/pkg/data/membership.go
- app/controlplane/pkg/data/project.go
This patch eagerly loads the organization of the membership, so it's available and can be used to check roles in the service and business layers.
> fix(projects): Always load organization on memberships

- app/controlplane/pkg/data/ent/migrate/migrations/20250714172256.sql
- app/controlplane/pkg/data/ent/migrate/migrations/atlas.sum
- app/controlplane/pkg/data/group.go
- app/controlplane/pkg/data/project.go
This patch fixes issues with group removal, where related resources were being left behind. Deleting a group now performs the following actions:
- Marks the group as deleted
- Marks all user group memberships as deleted
- Removes all group-related entries from the membership table, including users with the maintainer role and group memberships in projects
- Marks all pending invitations associated with the group as deleted, if any
It also creates a migration that fixes all current dangling groups if any in the system by performing the same steps as above.
> fix(group): Deletion of groups handle correctly

- app/controlplane/cmd/wire_gen.go
- app/controlplane/pkg/biz/group.go
- app/controlplane/pkg/biz/testhelpers/wire_gen.go
- app/controlplane/pkg/data/ent/migrate/migrations/20250715100956.sql
- app/controlplane/pkg/data/ent/migrate/migrations/atlas.sum
- app/controlplane/pkg/data/group.go
- app/controlplane/pkg/data/membership.go
This patch updates the way group membership counts are maintained. Instead of incrementing or decrementing the counter on each insertion or deletion, the total number of members is now recalculated after every transaction and the count is updated accordingly.
> fix(group): Calculate member count as a whole

- app/controlplane/pkg/data/group.go
This pull request includes a small but important change to the query logic in the `ListProjectsByGroup` method of the `GroupRepo` implementation. The change ensures that only non-deleted project versions are selected in addition to the latest versions.
* [`app/controlplane/pkg/data/group.go`](diffhunk://#diff-9de0461d6462eaa9b6c24a3da33235a91f45c65ebd5a291e81dd59743936c2b8L681-R681): Updated the `WithVersions` query to include a condition that filters out deleted project versions by adding `projectversion.DeletedAtIsNil()` to the query.
> fix(groups): Avoid listing removed project versions marked as latest

- app/controlplane/internal/service/service.go
- app/controlplane/pkg/biz/membership.go
- app/controlplane/pkg/biz/project.go
- app/controlplane/pkg/biz/project_integration_test.go
This reverts commit df71cee4270b4c5c8b1824fcfd4c803a9b392a07.
> Revert "chore: org viewers cannot become project admins (#2251)"

- app/controlplane/pkg/biz/membership.go
- app/controlplane/pkg/biz/membership_integration_test.go
- app/controlplane/pkg/biz/project.go
- app/controlplane/pkg/biz/project_integration_test.go
This PR skips roles acquired from groups when these are not compatible with the user's Org-level role. In particular: OrgViewer and ProjectAdmin
note that this is the re-submit of a previous buggy attempt: #2251
> feat(rbac): skip invalid role combinations

- app/controlplane/pkg/biz/membership.go
- app/controlplane/pkg/biz/membership_integration_test.go
- app/controlplane/pkg/biz/project.go
- app/controlplane/pkg/biz/project_integration_test.go
This reverts commit b1e76a830e51f622208c94c36beaf31c3507c290. We'll allow these combinations and properly inform users.
> fix(rbac): revert "feat(rbac): skip invalid role combinations (#2266)"

- app/controlplane/internal/service/group.go
- app/controlplane/pkg/authz/authz.go
As read-only admins, Org Viewers should be able to see all organization resources. 
This PR allow viewers to:
* query organization memberships  (before, only admins and owners could)
* query group memberships (berfore, only admins and group maintainers could)
Demo (sarah@chainloop.local as OrgViewer):
```
➜  cldev org member ls
┌──────────────────────────────────────┬───────────────────────┬────────┬─────────────────────┐
│ ID                                   │ EMAIL                 │ ROLE   │ JOINED AT           │
├──────────────────────────────────────┼───────────────────────┼────────┼─────────────────────┤
│ 4afbb744-bb94-43e7-a35e-a2f7e1493e60 │ john@chainloop.local  │ owner  │ 18 Jul 25 12:08 UTC │ …
```
> chore(rbac): Allow OrgViewers to see organization memberships

- internal/schemavalidators/external_schemas/runnercontext/runner-context-response-0.1.schema.json
This PR improves the runner context material validation by allowing branches without active rules which is a valid situation.
> Improve runner context material validation by allowing branches without active rules

- app/cli/internal/action/attestation_init.go
- pkg/policies/policies.go
- pkg/policies/policies_test.go
- pkg/policies/policy_groups.go
This PR adds information regarding policy name when computing policy arguments.
> Add policy name when computing policy arguments

- app/controlplane/pkg/biz/group.go
- app/controlplane/pkg/biz/orginvitation.go
- app/controlplane/pkg/biz/orginvitation_integration_test.go
- app/controlplane/pkg/biz/project.go
- app/controlplane/pkg/biz/project_integration_test.go
- app/controlplane/pkg/biz/testhelpers/database.go
- app/controlplane/pkg/biz/testhelpers/wire_gen.go
This pull request introduces changes to improve the handling of organization invitations, particularly in the context of joining groups and projects. The updates include modifying the `OrgInvitationContext` structure to use pointers for UUID fields, adding support for external metadata, and enhancing test coverage to handle edge cases like nil UUIDs.
Before, since the groupID and projectID were not pointers, they were being stored in the DB as their nil representation of UUUID the `0000-0000...` by adding a pointer, the are not store at all. The UUID != uuid.Nil check is there for already stored data.
> feat(invitations): Expand invitation context to external metadata

- app/controlplane/pkg/auditor/events/organization.go
- app/controlplane/pkg/biz/orginvitation.go
This patch adds the InvitationID to the OrgUserJoined event, indicating which invitation was used for the user to join the organization.
> feat(events): Include invitation ID on event

- pkg/policies/policies.go
- pkg/policies/policies_test.go
This PR adds a way to escape ```,``` character with ```\``` in policy arguments.
Closes #1979
> feat(policy): allow arguments with comma character

- app/cli/cmd/output.go
- app/cli/cmd/policy_develop_eval.go
- app/cli/cmd/policy_develop_lint.go
- app/cli/internal/action/policy_develop_eval.go
- app/cli/internal/policydevel/eval.go
- app/cli/internal/policydevel/eval_test.go
This PR changes policy evaluation and linting output to support proper redirection (e.g., ```chainloop policy devel eval {flags} > results.json```).
> feat(policy): change devel commands return to stdout

- app/controlplane/configs/config.devel.yaml
This patch comments out the NATS configuration in the default config file, as it’s not required to start the control plane.
> fix(startup): Remove NATS configuration from default dev config

- app/cli/documentation/generate.go
This PR fixes https://github.com/chainloop-dev/chainloop/issues/2319.
> Do not generate reference docs from the plugin

- app/controlplane/pkg/data/workflow.go
Deleting the last workflow in a project no longer automatically deletes the project.
> fix(workflow): deleting the only workflow in the project deletes the project

- app/cli/cmd/policy_develop_eval.go
- app/cli/cmd/policy_develop_lint.go
- app/cli/documentation/cli-reference.mdx
- app/cli/internal/action/policy_develop_lint.go
- app/cli/internal/policydevel/init.go
- app/cli/internal/policydevel/lint.go
- docs/examples/policies/quickstart/README.md
This PR changes the way policy file is linted. 
- when *.yaml file is passed all referenced *.rego files will also be linted. 
- when directory is passed or default (cwd) is used it looks for a ```policy.yaml``` file, if not found linting fails. (before it would lint all valid *.yaml and *.rego files)
Closes #2310
> fix(policy): add referenced script traversal

- docs/examples/policies/_testutils.sh
- docs/examples/policies/json-field-validator/README.md
- docs/examples/policies/json-field-validator/policy.yaml
- docs/examples/policies/json-field-validator/test.sh
- docs/examples/policies/json-field-validator/testdata/compliance-checklist.json
- docs/examples/policies/json-field-validator/testdata/config.json
- docs/examples/policies/json-field-validator/testdata/invalid.json
- docs/examples/policies/sbom-freshness/README.md
- docs/examples/policies/sbom-freshness/policy.yaml
- docs/examples/policies/sbom-freshness/test.sh
- docs/examples/policies/sbom-freshness/testdata/sbom-fresh.json
- docs/examples/policies/sbom-freshness/testdata/sbom-missing-timestamp.json
- docs/examples/policies/sbom-freshness/testdata/sbom-old.json
Adds a comprehensive JSON field validation policy example with shared testing utilities and improved policy structure.
- **`json-field-validator/`**: Complete policy example for validating JSON fields
- Generic field validation with dot notation support (`application.name`, `security.enabled`)
- Configurable validation types (exact values, regex patterns)
- Works with EVIDENCE material type for JSON files
- **Shared `_testutils.sh`**: Configurable test utilities supporting multiple material types
- Proper exit codes (0 for pass, 1 for fail)
- Skipped/ignored policy detection
- Custom material type support (`--kind` parameter)
- **`sbom-freshness/`**: Restructured SBOM policy following new template
- **Field Validation**: `required_field=application.name expected_value=web-service`
- …
> example(policy): New json-field-validator policy example

- pkg/attestation/crafter/crafter.go
- pkg/policies/policy_groups.go
The allowed hostnames were not being passed to the statement verification nor the policy groups verifiers.
> fix: pass allowed hostnames during group verification

- app/cli/cmd/policy_develop_eval.go
- app/cli/internal/policydevel/eval.go
- app/cli/internal/policydevel/eval_test.go
This PR adds error when no evaluations on provided material were performed.
```
apiVersion: workflowcontract.chainloop.dev/v1
kind: Policy
metadata:
name: policy
description: Chainloop validation policy
spec:
policies:
- embedded: |
package main
import rego.v1
################################
################################
result := {
"skipped": skipped,
"violations": violations,
"skip_reason": skip_reason,
"ignore": ignore,
}
default skip_reason := ""
skip_reason := m if {
not valid_input
m := "invalid input"
}
default skipped := true
skipped := false if valid_input
default ignore := false
########################################
########################################
valid_input := true
violations contains msg if {
valid_input
msg := "test"
}
kind: EVIDENCE
- embedded: |
package …
```
> feat(policy): policy eval should fail if no execution path is met

- app/cli/cmd/policy_develop_eval.go
- app/cli/documentation/cli-reference.mdx
This PR fixes issue with passing arrays in `--input` flag.
By passing `--input licenses=AGPL,GPL` in the eval command values can now be accessed with `input.args.licenses[0]` and `input.args.licenses[1]` in the rego script.
Closes #2351
> fix(policy-devel): inputs don't accept multiple values

- app/cli/cmd/policy_develop_lint.go
- app/cli/documentation/cli-reference.mdx
- app/cli/internal/policydevel/lint.go
This PR removes support for yaml and embedded rego formatting due issues caused by yaml libraries limitations.
Closes #2379
> feat(policy-devel): drop support for yaml and embedded rego formatting

- docs/examples/policies/_testutils.sh
- docs/examples/policies/json-field-validator/policy.yaml
- docs/examples/policies/sbom-freshness/policy.yaml
- docs/examples/policies/sbom-freshness/test.sh
This PR fixes issue with `_testutils.sh` functions returning exit codes in lint and eval functions. Older example policies got linted with `policy devel lint --format` to make them consistent with other examples. One of the tests in freshness policy was fixed since it was time depended. Regex is used to find result fields in the output so no additional changes were needed to adjust the script to the new `eval` output.
Closes #2376
> fix(examples): update example policies and test script

- .goreleaser.yml
Today, we are generating the cli SBOMs tool with goreleaser, which uses Syft. Syft's default configuration doesn't include license information for Go packages in the SBOM. 
Syft provides a set of settings described in https://github.com/anchore/syft/wiki/Configuration#list-of-configurable-values. Setting the environment variable SYFT_GOLANG_SEARCH_REMOTE_LICENSES=true will enable retrieving the license information for go packages when generating SBOMs .
```
golang:
search-remote-licenses: false
proxy: ""
```
The setting is added to the .goreleaser.yml, new sbom section, as recommended in https://goreleaser.com/customization/sbom/.
> fix(build): include go package licenses in sbom fixes#2363 for the cli

- pkg/policies/engine/rego/rego.go
- pkg/policies/engine/rego/rego_test.go
- pkg/policies/engine/rego/testfiles/arguments.rego
- pkg/policies/engine/rego/testfiles/arguments_array.rego
- pkg/policies/engine/rego/testfiles/check_qa.rego
- pkg/policies/engine/rego/testfiles/policy_without_violations.rego
- pkg/policies/engine/rego/testfiles/restricted_mode_networking_allowed_host.rego
- pkg/policies/engine/rego/testfiles/restrictive_mode_networking.rego
- pkg/policies/testdata/materials.rego
- pkg/policies/testdata/sbom_syft.rego
- pkg/policies/testdata/with_arguments.rego
- pkg/policies/testdata/workflow.rego
- pkg/policies/testdata/workflow_embedded.yaml
This PR removes deprecated rule handling from rego engine and updates testdata that used deprecated rule to return result rule.
Closes #2371
> feat(policy): remove support for deprecated violations rule

- app/cli/internal/policydevel/lint_test.go
- app/cli/internal/policydevel/testdata/embedded-policy.yaml
- app/cli/internal/policydevel/testdata/missing-keys.rego
- app/cli/internal/policydevel/testdata/multiple-rules.rego
- app/cli/internal/policydevel/testdata/policy.yaml
- app/cli/internal/policydevel/testdata/unformatted.rego
- app/cli/internal/policydevel/testdata/valid.rego
This PR adds missing unit tests to `lint`. 
Closes #2390
> feat(policy-devel): add lint tests

- devel/compose.common.yml
- devel/compose.labs.yml
- devel/compose.yml
This pull request updates the container images used for key services in the development Docker Compose files. The changes ensure that the images are pulled from the organization's own container registry and are pinned to specific versions.
**Container image updates:**
* Updated the `postgresql` service in `devel/compose.common.yml` to use `ghcr.io/chainloop-dev/chainloop/postgresql:16.4.0` instead of the generic Bitnami image.
* Updated the `dex` service in both `devel/compose.labs.yml` and `devel/compose.yml` to use `ghcr.io/chainloop-dev/chainloop/dex:2.43.1` instead of the generic Bitnami image. [[1]](diffhunk://#diff-f60f75bd50f651d5f09d3afce6446e5bb3a911e4302957c8e0130fc8bee53626L10-R10) [[2]](diffhunk://#diff-1dea3cd00d4352daf3b972d82bd192ffdbd428516567c4f3652c9790189dd697L11-R11)
> chore(devel): Use in-house images in docker compose file

- app/controlplane/cmd/main.go
- app/controlplane/cmd/wire_gen.go
- app/controlplane/pkg/auditor/events/casbackend.go
- app/controlplane/pkg/auditor/events/casbackend_test.go
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_created.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_created_by_system.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_deleted.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_permanent_deleted.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_soft_deleted.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_status_change.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_status_recovery.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_updated.json
- app/controlplane/pkg/auditor/events/testdata/casbackends/casbackend_updated_default_change.json
- app/controlplane/pkg/biz/.mockery.yml
- app/controlplane/pkg/biz/biz.go
- app/controlplane/pkg/biz/casbackend.go
- app/controlplane/pkg/biz/casbackend_checker.go
- app/controlplane/pkg/biz/casbackend_test.go
- app/controlplane/pkg/biz/mocks_test.go
- app/controlplane/pkg/biz/testhelpers/wire_gen.go
- app/controlplane/pkg/data/casbackend.go
This pull request introduces comprehensive support for auditing CAS backend lifecycle events in the control plane. It adds new event types and logic for tracking CAS backend creation, updates, deletion, and status changes, along with corresponding tests and golden files for validation. Additionally, it refactors application wiring to include a background CAS backend checker that runs every 30 min and checks only default CAS backend not including the INLINE ones.
**Auditing and Event Tracking Enhancements:**
* Added new CAS backend audit event types (`CASBackendCreated`, `CASBackendUpdated`, `CASBackendSoftDeleted`, `CASBackendPermanentDeleted` and `CASBackendStatusChanged`) with detailed payload structures and descriptions in `pkg/auditor/events/casbackend.go`. 
Each CAS backend is …
> feat(cas): Move check of CAS backends to ticker

- app/cli/cmd/config.go
- app/cli/cmd/plugins.go
- app/cli/cmd/root.go
- app/cli/documentation/cli-reference.mdx
- app/cli/pkg/plugins/interface.go
- Enable plugins to register subcommands under existing CLI commands 
- Provide configuration for backend API access
> feat(plugin): allow subcommands and platform configuration

- .github/workflows/contracts/chainloop-vault-release.yml
This passes the input to skip components with type "file" when executing the sbom-with-licenses policy. This will prevent unnecessary flagging as components with no license. These types of components are files installed as part of another component as a library and no additional license validation is needed.
> build(contract): skip empty license verification for the SBOM component type file

- app/cli/cmd/config.go
- app/cli/cmd/root.go
- app/cli/documentation/cli-reference.mdx
remove platform references in OSS CLI, it also exposes the shared Loader
> chore(cli): remove platform config

- app/cli/main.go
The problem was that the attestation process wrapped the error in the CLI, but our code wasn't checking actual wrapped errors—just the messages. By extending the isWrappedError function to support both behaviors, we can make it work. 
```
$ go run main.go att init --workflow test --project bar
This command is will run against the organization "chainloop"
Please confirm to continue y/N
y
ERR your authentication token has expired, please run chainloop auth login again
exit status 1
```
Fixes #2434
> fix(cli): return consistent authentication error

- .github/workflows/contracts/chainloop-vault-release.yml
The sbom-banned-licenses policy correctly flagged unknown licenses in the SBOM. After reviewing and confirming that these are permitted licenses, it is safe to add them to the allowlist. 
Fixes #2451
This PR adds Apache-2.0 as a permitted custom license (via the license.name field in the SBOM). While SPDX identifiers in the id or expression fields are the recommended approach for open source components, we’ve observed some cases where the license.name field is still used.
> (compliance/contracts): add approved licenses to custom allowlist
