app/controlplane/internal/service/attestation.go
app/controlplane/internal/service/service.go

fix(controlplane): fix variadic logger

---

app/controlplane/cmd/wire_gen.go
app/controlplane/internal/biz/attestation.go
app/controlplane/internal/biz/attestation_test.go

Removes deprecated OCI connectivity code refs #2

chore(controlplane): remove deprecated OCI code

---

.github/workflows/release.yaml
.github/workflows/test.yml
.github/workflows/utils/bump-chart-version.sh
deployment/chainloop/LICENSE.md
deployment/chainloop/README.md

Create a pull-request with a bump of the chart version after a release has been successful
Refs #64

bump Helm Chart version during release

---

app/cli/cmd/artifact_download.go
app/cli/cmd/artifact_upload.go
app/cli/cmd/attestation_add.go

Close artifact connection from CLI as well
Refs #68

fix(cli): explicit artifact-cas gRPC connection close 

---

deployment/chainloop/Chart.yaml
deployment/chainloop/values.yaml

Add k8s resources to achieve quality of service guaranteed.  
Refs #15

feat(deployment): enable k8s QoS guaranteed

---

README.md

docs: add deployment instructions

---

.github/workflows/release.yaml

fix(ci): bump-chart-version call

---

.github/workflows/test.yml
go.mod

Run `go mod tidy` during tests
Closes #125

chore(ci): check go mod tidiness

---

app/controlplane/extensions/extensions.go
app/controlplane/extensions/extensions_test.go

Updated the loading code to detect extensions with the same ID
Refs #38

feat(extensions): detect duplicated extentions

---

README.md
app/controlplane/plugins/core/dependency-track/v1/extension.go
app/controlplane/plugins/core/discord-webhook/v1/discord.go
app/controlplane/plugins/core/oci-registry/v1/ociregistry.go
app/controlplane/plugins/core/smtp/v1/extension.go
app/controlplane/plugins/sdk/readme-generator/main.go
docs/integrations.md

Integrations page that includes the following sections: 
- introduction
- available integrations table (automatically generated)
- quick start user guide
- FAQ
Note: This patch also bumped the plugins versions to match is stability status.
Refs #38

docs(integrations): list and initial user guide

---

README.md
docs/integrations.md

docs(integrations): minor gramar and typo fixes 

---

deployment/chainloop/README.md

Closes #226 
It also ran `readme-generator-for-helm` 
```
/bin/index.js --readme ~/work/chainloop/chainloop/deployment/chainloop/README.md --values ~/work/chainloop/chainloop/deployment/chainloop/values.yaml
```

docs: fix deployment example

---

.github/workflows/lint.yml
.github/workflows/package_chart.yaml
.github/workflows/release.yaml
.github/workflows/test.yml
internal/attestation/crafter/materials/cyclonedxjson_test.go
internal/attestation/crafter/materials/spdxjson_test.go

Made changes based on https://github.com/ossf/scorecard recommendations.

fix: least privilege support in automated workflows

---

internal/attestation/crafter/runners/azurepipeline.go
internal/attestation/crafter/runners/azurepipeline_test.go

fix: Azure Pipeline Run URI incorrect value

---

.goreleaser.yml

Reduce the size by stripping debug symbols

---

app/controlplane/internal/biz/workflowrun_integration_test.go
app/controlplane/internal/data/workflowcontract.go

This change makes sure that a workflow contract revision gets created only if there is an actual update in the schema content.
Closes chainloop-dev/chainloop#136

fix(controlplane): bump revision only during workflow contract update

---

app/controlplane/internal/service/casredirect.go

fix: allow downloading artifacts with http clients

---

go.mod
go.sum
internal/attestation/crafter/materials/cyclonedxjson_test.go
internal/attestation/crafter/materials/testdata/sbom.cyclonedx-1.5.json

Adds support for CycloneDX 1.5 SBOM format by upgrading our parsing library
Closes #479 
Refs #210

feat: add support for CycloneDX 1.5

---

extras/dagger/README.md
extras/dagger/main.go

Allow providing material types of other kinds other than artifacts refs #511

feat(dagger): support non-artifact materials

---

extras/dagger/main.go

Adding a description so it appears in the daggerverse [entry](https://daggerverse.dev/mod/github.com/chainloop-dev/chainloop/extras/dagger@d73b0627e85746be404a297c122e9e5ac84f4627)

chore(dagger): add description

---

extras/dagger/README.md
extras/dagger/main.go

chore(dagger): upgrade client to v0.66

---

extras/dagger/README.md

Adds information in the module about how to use it as part of a pipeline, pointing to our existing example.
Refs #532
Refs #501

docs(dagger): update module readme

---

app/controlplane/internal/biz/organization.go

The other problem listed in the issue #536 was already tackled but not released
Closes #536

chore: improve org name error message

---

extras/dagger/README.md
extras/dagger/dagger.json

chore(dagger): bump module to stable v0.10.0

---

app/cli/cmd/organization.go
app/cli/cmd/organization_list.go
app/cli/cmd/organization_member.go
app/cli/cmd/organization_member_delete.go
app/cli/cmd/organization_member_list.go
app/cli/cmd/organization_member_update.go
app/cli/internal/action/membership_leave.go
app/cli/internal/action/membership_list.go
app/cli/internal/action/membership_set.go
app/cli/internal/action/membership_update.go

Organization-scoped membership management
You can now list the members using `chainloop org member list`
update a member 
```
chainloop org member update --id [ID] --role viewer|owner|admin 
```
or delete a member
```
chainloop org delete --id [ID] 
```
Closes #558

feat(cli): organization membership

---

.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/release.yaml
.github/workflows/test.yml
app/artifact-cas/Dockerfile
app/artifact-cas/Dockerfile.goreleaser
app/controlplane/Dockerfile
app/controlplane/Dockerfile.goreleaser
go.mod

Refs https://github.com/chainloop-dev/chainloop/issues/508

chore: upgrade golang to 1.22.1

---

.github/workflows/lint.yml
extras/dagger/main.go

My bad, it seems I left some non-functional code in main

chore(ci): fix dagger linter

---

.github/workflows/codeql.yml
.github/workflows/docs_deploy.yml
.github/workflows/docs_test.yml
.github/workflows/lint.yml
.github/workflows/package_chart.yaml
.github/workflows/release.yaml
.github/workflows/scorecards.yml
.github/workflows/test.yml
docs/docs/getting-started/attestation-crafting.md
docs/examples/ci-workflows/github.yaml

Bump checkout and setup-node actions

chore(ci): bump actions

---

app/cli/cmd/attestation_push.go

Closes https://github.com/chainloop-dev/chainloop/issues/521

fix(cli): send digest to stderr

---

.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/release.yaml
.github/workflows/test.yml
app/artifact-cas/Dockerfile
app/artifact-cas/Dockerfile.goreleaser
app/controlplane/Dockerfile
app/controlplane/Dockerfile.goreleaser
go.mod

https://go.dev/doc/devel/release#go1.22.2

chore: upgrade golang 1.22.2

---

.github/workflows/codeql.yml

This PR adds chainloop CLI to codeql workflows to attest SARIF results.
Closes #707

feat(ci): Adds chainloop to codeql pipeline

---

app/controlplane/internal/biz/workflowrun.go
app/controlplane/internal/biz/workflowrun_integration_test.go

Follow up from attestation kind 
closes #719

feat(controlplane): verify that dependent attestations exist

---

.github/workflows/sync_contracts.yml

This PR fixes a level of indentation provoking GitHub action to not run.

fix(ci): Fixes level of indentation

---

.github/workflows/contracts/README.md

This PR adds a disclaimer section on the contracts' README file.

feat(ci): Updatees contracts' README file

---

app/controlplane/internal/authz/authz.go

This reverts commit 4dac4f6150ccb9d42574c7d9e878401a414784ac.
We will tackle authorization later on.

Revert "feat(policies): Add attestation as new resource type and workflow create permission (#754)

---

docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Enables posthog on our documentation site

chore(docs): enable posthog

---

.github/workflows/contracts/chainloop-vault-release.yml
.github/workflows/release.yaml

This PR adds missing amd64 cli binaries to the release contract that were missing.
Refs #731

feat(release): Add missing amd64 binaries

---

.github/workflows/contracts/chainloop-vault-release.yml
.github/workflows/release.yaml

This PR adds Chainloop source code as a new attestation artifact.

feat(ci): Add source code tarball

---

.github/workflows/package_chart.yaml

Reverting until we deploy the fixed backend
This reverts commit b889590bc9c00d670fc0648e8ac91d0a241311de.

Revert "feat(ci): Use reusable workflow creation on Helm package (#775)"

---

.github/workflows/package_chart.yaml

This reverts commit def119eb3918ce392e8a84f33e52f46b36f1b011.

Reapply "feat(ci): Use reusable workflow creation on Helm package (#775)" (#802)

---

app/cli/internal/telemetry/posthog/posthog.go

fixes #809
relates to https://github.com/Homebrew/homebrew-core/pull/172169
cc @migmartri

fix: add nil check for Tracker

---

extras/dagger/main.go

Bump Dagger module to latest version v0.89.0

chore(dagger): Bump module

---

.github/workflows/sync_contracts.yml

Bumps the version of the labs' workflow.

feat(sync-contract): Bump version of reusable workflow

---

internal/attestation/renderer/renderer.go

attestations are being wrapped twice
refs #865

fix(keyless): remove double wrap

---

app/cli/cmd/attestation_init.go

refactor: remove workflow_name env var

---

app/controlplane/Dockerfile.migrations

Upgrade migrations container image

chore: update migrations image

---

deployment/chainloop/Chart.yaml

For some reason the automatic PR failed.

chart: use images v0.91.2

---

deployment/chainloop/Chart.yaml

Manually created this PR again since the automatic PR failed again.

chore(chart): bump to v0.91.3

---

deployment/chainloop/Chart.yaml

This patch fixes de conflict and bumps the image versions.

fix(chart): Fix conflict and bump chart and images

---

app/controlplane/internal/authz/authz.go

fix: allow-deleting account even if viewer role

---

app/controlplane/pkg/biz/casbackend.go
app/controlplane/pkg/biz/casbackend_integration_test.go
app/controlplane/pkg/data/casbackend.go
app/controlplane/pkg/data/ent/casbackend_update.go
app/controlplane/pkg/data/ent/schema/casbackend.go

chore(cas-backends): make name inmutable

---

app/controlplane/pkg/data/ent/integration_update.go
app/controlplane/pkg/data/ent/schema/integration.go

Closes https://github.com/chainloop-dev/chainloop/issues/682

chore(integrations): make name inmutable

---

app/cli/cmd/workflow_list.go

Show contract name in the workflow list. This will improve our guides since the user will see right away what contract needs to be updated.

feat(cli): show contract name in wf list

---

docs/docs/getting-started/workflow-definition.mdx
docs/docs/guides/dependency-track/dependency-track.mdx
docs/docs/guides/guac/guac.mdx
docs/docs/guides/sbom-management/sbom-management.mdx
docs/docs/integrations/development/overview.md
docs/docs/integrations/integrations.md
docs/docs/quickstart.md

docs: update docs to reference name instead of id

---

.github/workflows/build_and_package.yaml
.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/test.yml
app/artifact-cas/Dockerfile
app/artifact-cas/Dockerfile.goreleaser
app/cli/Dockerfile.goreleaser
app/controlplane/Dockerfile
app/controlplane/Dockerfile.goreleaser

Follow up of #1080 bumping golang in the pipelines and Docker files

chore(go): update Go version in build pipelines

---

.github/workflows/package_chart.yaml

Changes in #1090 caused the release process to fail

fix(ci): packaged Chart

---

deployment/chainloop/Chart.yaml

Trigger Helm package refs #1090

chore: bump chart

---

docs/docs/reference/policies.md
docs/examples/policies/chainloop-commit.yaml
docs/examples/policies/chainloop-qa.yaml
docs/examples/policies/cyclonedx-licenses.yaml
docs/examples/policies/sarif-errors.yaml
docs/examples/policies/sbom-present.yaml
docs/examples/policies/sbom-syft.yaml
docs/examples/policies/trivy-vulns.yaml
docs/sidebars.js

This PR adds a new documentation page, as well as some policy examples to play with.
Refs #122

feat(policies): document policies

---

deployment/chainloop/README.md
deployment/chainloop/values.yaml

Markdown linter from Bitnami complains about naked URLs.

chore: update chart

---

deployment/chainloop/Chart.yaml
deployment/chainloop/templates/_helpers.tpl

This patch removes helpers functions of SQL Proxy
Refs #1151 https://github.com/bitnami/charts/pull/27100

feat(chart): Remove helpers for SQL Proxy

---

deployment/chainloop/Chart.yaml
deployment/chainloop/templates/_helpers.tpl

This patch fixes the helper function that injects the Dex configuration.
#1151 https://github.com/bitnami/charts/pull/27100

fix(chart): Fixes OIDC default configuration

---

deployment/chainloop/Chart.yaml
deployment/chainloop/templates/controlplane/configmap.yaml

Refs https://github.com/chainloop-dev/chainloop/issues/1180

fix(chart): problem rendering without providers

---

.goreleaser.yml

chore: add "latest" tag to control-plane-migrations

---

pkg/policies/loader.go
pkg/policies/policies_test.go

fix policy loader wrongly setting provider and name

---

app/controlplane/configs/config.devel.yaml
devel/README.md
devel/compose.common.yml
devel/compose.labs.yaml
devel/compose.yml
devel/dex/config.labs.yaml

fix(development): make development environment work by default

---

docs/docs/reference/policies.mdx

This PR adds a small section about arguments in the policies documentation.
Closes #1295

feat(docs): document policy arguments

---

.github/workflows/contracts/chainloop-vault-codeql.yml
.github/workflows/contracts/chainloop-vault-scorecards.yml

This patch add specific SARIF policies to contract that contains SARIF materials.
Refs #1312

feat(contracts): Add SARIF policies to contracts

---

extras/dagger/main.go

Bumps Dagger's version of Chainloop CLI to latest.

feat(dagger): Bump Dagger Chainloop CLI version

---

app/controlplane/pkg/data/apitoken.go

Eager load organization data for apitokens. 
Closes #1385

chore(control-plane): set organization name when getting token by ID

---

.github/workflows/package_chart.yaml
deployment/chainloop/Chart.yaml

unblock release since current CP is not compatible with latest CLI

fix(ci): pin previous version

---

docs/docs/guides/rego-policies/rego-policies.mdx
docs/docs/reference/policies.mdx
docs/examples/policies/sbom/cyclonedx-licenses.yaml

This is a follow up of https://github.com/chainloop-dev/chainloop/pull/1400 to update the documentation examples.
Related to #1321

feat(docs): update rego implementation in docs

---

docs/docs/getting-started/attestation-crafting.md
docs/docs/guides/rego-policies/rego-policies.mdx
docs/docs/quickstart.md

docs: update quickstart

---

.github/workflows/package_chart.yaml

the CP is now updated, we can revert it

revert: fix(ci): pin previous version

---

extras/dagger/main.go

Support providing project version on att init, refs #1433

feat(dagger): support versioning

---

app/cli/cmd/attestation_init.go
app/cli/cmd/config.go

Tries to load the version from a .chainloop.[yaml|yml] traversing up until it finds a .git directory.
closes #1461

feat: load version from local file

---

.chainloop.yml
.github/workflows/build_and_package.yaml
.github/workflows/utils/bump-project-version.sh

- Add current version to .chainloop.yaml so it can be used once #1461 is released
- Added automation to automatically bump the version

feat: add project version to repository

---

.github/workflows/release.yaml

Include the tag version on the release workflow.

feat(ci): Include proper version on release workflow

---

.chainloop.yml
.github/workflows/build_and_package.yaml
.github/workflows/utils/bump-project-version.sh

The bump script prepares the next version to be released
Ref https://github.com/chainloop-dev/chainloop/issues/1470

feat: bump next version

---

extras/dagger/main.go

feat(dagger): add pre-release version support

---

.github/workflows/build_and_package.yaml

feat(ci): mark version as released

---

pkg/attestation/crafter/api/attestation/v1/crafting_state.go
pkg/attestation/crafter/materials/helmchart.go
pkg/attestation/crafter/materials/helmchart_test.go
pkg/attestation/crafter/materials/materials.go
pkg/attestation/crafter/materials/oci_image.go

The Helm Chart material type now supports OCI references.
This feature will talk to the oci registry, validate that's a Helm chart, take the info  including signatures, and store it in the attestation.
```
go run main.go att add --kind HELM_CHART --value oci://registry-1.docker.io/bitnamicharts/chainloop:2.0.16
INF material added to attestation
```
the resulting attestation
```json
"materials": [
{
"annotations": {
"chainloop.material.image.tag": "2.0.16",
"chainloop.material.name": "material-1730893782022855000",
"chainloop.material.signature": "eyJzY2hlbWFWZXJzaW9uIjoyLCJtZWRpYVR5cGUiOiJhcHBsaWNhdGlvbi92bmQub2NpLmltYWdlLm1hbmlmZXN0LnYxK2pzb24iLCJjb25maWciOnsibWVkaWFUeXBlIjoiYXBwbGljYXRpb24vdm5kLmNuY2Yubm90YXJ5LnNpZ25hdHVyZSIsImRpZ2VzdCI6InNoYTI1Njo0NDEzNmZhMzU1YjM2NzhhMTE0NmFkMTZmN2U4NjQ …
```

feat(cli): remote Helm Charts

---

.github/workflows/contracts/chainloop-chainloop-github-release.yaml
.github/workflows/contracts/chainloop-docs-release.yml
.github/workflows/contracts/chainloop-vault-codeql.yml
.github/workflows/contracts/chainloop-vault-helm-package.yml
.github/workflows/contracts/chainloop-vault-release.yml
.github/workflows/contracts/chainloop-vault-scorecards.yml

Update contracts so that they leverage chainloop internal policies.

chore: update contracts in chainloop oss

---

app/cli/cmd/output.go
app/cli/cmd/workflow_list.go
app/cli/cmd/workflow_update.go
app/cli/internal/action/action.go
app/cli/internal/action/workflow_list.go

This patch introduces workflow pagination on the CLI by allowing two optional flags, `page` and `page-size`.
Example:
```
$ chainloop wf ls --page 1 --page-size 13
┌────────────────────────────────┬────────────────────────────┬──────────┬────────┬─────────────┬─────────────────┬─────────────────────┐
│ NAME                           │ PROJECT                    │ CONTRACT │ PUBLIC │ RUNNER      │ LAST RUN STATUS │ CREATED AT          │
├────────────────────────────────┼────────────────────────────┼──────────┼────────┼─────────────┼─────────────────┼─────────────────────┤
│ reviews-pm                     │ one-project                │          │ false  │             │                 │ 13 Nov 24 11:54 UTC │
│ chainloop-labs-tests           │ tests …
```

feat(cli): Introduce workflow pagination on CLI 

---

app/controlplane/pkg/biz/membership.go
app/controlplane/pkg/data/membership.go

Will be used to dynamically load the membership from the header

chore: add load membership by orgName

---

app/controlplane/internal/service/attestation.go

feat(push): upload to CAS in background

---

app/cli/cmd/attestation_add.go
app/cli/cmd/attestation_init.go
app/cli/cmd/attestation_push.go
app/cli/cmd/errors.go

general purpose retry mechanism for `att init, add and push`
ref #1533

feat: add backoff retry to all attestation commands

---

app/controlplane/pkg/biz/cascredentials.go

chore: increase validity window for the upload token

---

deployment/chainloop/Chart.yaml
deployment/chainloop/templates/controlplane/configmap.yaml

fix(chart): remove quotes profiler

---

app/controlplane/pkg/biz/workflowcontract.go
app/controlplane/pkg/data/workflowcontract.go
app/controlplane/pkg/policies/policyprovider.go
app/controlplane/pkg/unmarshal/unmarshal.go

chore: do not validate contract on reading

---

app/controlplane/internal/service/attestation.go
app/controlplane/pkg/data/workflowcontract.go

the describe endpoint was masking the underlying error under a 404
ref #1533

fix: do not mask 404 error

---

app/controlplane/pkg/data/workflow.go
app/controlplane/pkg/data/workflowrun.go

simplify query partitioning it to two more simple ones.

chore(db): improve find workflow by name

---

app/controlplane/pkg/data/workflowcontract.go

fix: remove print statement

---

app/controlplane/pkg/data/casbackend.go
app/controlplane/pkg/data/integration.go
app/controlplane/pkg/data/membership.go
app/controlplane/pkg/data/referrer.go
app/controlplane/pkg/data/workflow.go

Properly handle tx rollbacks thorough the app 
refs #1533

handle rollbacks

---

app/controlplane/pkg/biz/workflow_integration_test.go
app/controlplane/pkg/data/workflow.go

This patch fixes the workflow filter by adding the description of the workflows to the free fields search under an OR query.

fix(workflow): Move description filter for workflows

---

app/controlplane/pkg/biz/workflow_integration_test.go
app/controlplane/pkg/data/workflow.go

The description filter option was being added to the wrong set of conditions.

fix(workflow): Update workflow list query

---

deployment/chainloop/Chart.yaml
deployment/chainloop/README.md
deployment/chainloop/templates/_helpers.tpl
deployment/chainloop/templates/controlplane/secret-config.yaml
deployment/chainloop/values.yaml

Configurable event stream in Helm Chart
closes #1628

deployment: support nats configuration

---

deployment/chainloop/Chart.yaml
deployment/chainloop/README.md
deployment/chainloop/templates/_helpers.tpl
deployment/chainloop/templates/controlplane/secret-config.yaml
deployment/chainloop/values.yaml

This reverts commit 305f9b2b061061ff3a8d962ae95dde72a1ab9292.
let's double check log exposure in backend first.

Revert "deployment: support nats configuration (#1631)"

---

app/controlplane/pkg/authz/authz.go
app/controlplane/pkg/biz/apitoken.go

feat: allow to create contracts from API token

---

docs/docs/reference/policies.mdx

Small PR to improve policy groups documentaiton.

chore(docs): document material name placeholders in policy groups

---

.golangci.yml

Adds support to range-based headers

chore(linter): happy new year 2025

---

.github/workflows/docs_deploy.yml
docs/.syft.yaml

It seems some options are not relative to the current folder but from project root..

fix(wofklows): add config parameter to syft

---

app/cli/cmd/attestation_status.go
app/cli/cmd/workflow_workflow_run_describe.go

Show skipped policies, including their skip reasons
Closes #1704

feat(cli): show skipped policies

---

app/controlplane/pkg/data/workflow.go

fix(cli): show contract name in wf list

---

app/cli/cmd/attestation_status.go
pkg/attestation/crafter/crafter.go

fix: reset policy evaluations on repeated additions

---

app/cli/cmd/attestation_add.go
app/cli/cmd/attestation_status.go
app/cli/cmd/output.go
app/cli/internal/action/attestation_add.go
app/cli/internal/action/attestation_status.go

---
- Resolves issue #1686: 
- Added the `GetMaterialInfo` function to display material information.
- The material information will be shown at the `chainloop` after adding new materials.
- This allows users to view the material they have added.
```
go run app/cli/main.go att add --name skynet-sbom --value /home/yoi/Downloads/sbom.json --token=mytoken ;)
INF material kind detected kind=SBOM_CYCLONEDX_JSON
INF material added to attestation
┌──────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Name     │ skynet-sbom                                                                                            │
├──────────┼───────────────────────────────────────────────────────────────────────── …
```

feat: show material info at chainloop att add

---

pkg/attestation/renderer/chainloop/testdata/attestation.output.v0.2.json
pkg/attestation/renderer/chainloop/v02.go

Full example
```json
{
"type": "https://in-toto.io/Statement/v1",
"subject": [
{
"name": "chainloop.workflow.gh-1686-issue",
"digest": {
"sha256": "325e3ec535cde9a8289a12ac1f02c8a743322baa871349fed2b2880888e14314"
}
},
{
"name": "git.head",
"digest": {
"sha1": "ccf452ac8317ccd9b2fa179a8213681cd4a6db2c"
},
"annotations": {
"author.email": "miguel@chainloop.dev",
"author.name": "Miguel Martinez",
"date": "2025-01-20T21:42:07Z",
"message": "fix(attestation): camelcase all the things\n\nSigned-off-by: Miguel Martinez \u003cmiguel@chainloop.dev\u003e\n",
"remotes": [
{
"name": "origin",
"url": "git@github.com:migmartri/chainloop.git"
},
{
"name": "upstream",
"url": "git@github.com:chainloop-dev/chainloop.git"
},
{
"name": "test-token",
"url": "https://github.com/chainloop-dev/chainloop.git"
} …
```

fix(attestation): camelcase all the things

---

.github/workflows/docs_deploy.yml
docs/package.json
docs/yarn.lock

upgrade dependencies to remove path-to-regexp vulnerability.
Related to #1761

fix(vulns): docs vulnerabilities and workflow

---

.github/workflows/build_and_package.yaml
.github/workflows/docs_deploy.yml
.github/workflows/docs_test.yml
.github/workflows/release.yaml
.github/workflows/scorecards.yml

Upgrade to latest version of scorecards (5)
Closes #1761

chore: fix some scorecards issues

---

.github/workflows/contracts/chainloop-vault-codeql.yml
.github/workflows/contracts/chainloop-vault-helm-package.yml
.github/workflows/contracts/chainloop-vault-release.yml
.github/workflows/contracts/chainloop-vault-scorecards.yml
.github/workflows/package_chart.yaml

This patch modifies the contracts of Chainloop to include several requirements and also signs the Helm Chart.

chore(contracts): Add requirements to contracts and sign Helm Chart

---

app/cli/cmd/attestation_push.go

Missed this other message, sorry

fix(cli): remove hardcoded message

---

.github/workflows/release.yaml

Remove `--kind` flag from `attestation add`

fix(ci): Fix attestation command

---

.github/workflows/release.yaml

Removes material name from add command.

fix(ci): Remove material name

---

app/controlplane/internal/service/auth.go

This PR improves login handling by
- Exposing errors returned by identity providers, like the one below regarding email requirement
- Handles internal errors differently than authorization errors by not raising the latter 
- Extends the login/callback state cookie duration to be more permissive on the time that the user might take to do the whole oauth dance

feat: SSO improve auth handling

---

docs/docs/quickstart.mdx

Fixes path referencing material.

fix(docs): Updates reference to material

---

docs/yarn.lock

chore: upgrade docs dependencies

---

app/controlplane/Dockerfile.migrations

0.32 in fact didn't fix the issue

chore: upgrade atlas

---

docs/examples/quickstart/quickstart-contract.yaml

docs: fix quickstart contract

---

app/controlplane/plugins/core/dependency-track/v1/client/sbom.go
app/controlplane/plugins/core/dependency-track/v1/extension.go
devel/integrations.md

fix(dependency-track): verify project directly

---

docs/examples/contracts/slsa/github.yaml

Example contract with container image SLSA provenance and policy group pointing for SLSA compliance verification.

feat(examples) - example contract with container image, SLSA provenance and policy group 

---

docs/examples/contracts/sbom/sbom-quality.yaml
docs/examples/contracts/vulnerabilities/vulnerability-management.yaml

docs: add example contracts

---

pkg/attestation/crafter/runners/oidc/gitlab.go

This PR adds verification of the Gitlab OIDC token.

Verify Gitlab OIDC token audience

---

app/controlplane/internal/usercontext/attjwtmiddleware/attmiddleware_test.go

The tokens had expiration time

fix(tests): replace test data

---

app/controlplane/pkg/biz/workflowcontract.go
app/controlplane/pkg/data/workflowcontract.go

This patch queries for missing filds and eager loads projects when looking to load the workflow reference in the context of a contract.
The project name gets loaded correctly for the `describe`:
```
$ chainloop wf contract describe --name core-containers-sbom
INF To download the contract, run the command with the "--output schema" option
┌─────────────────────────────────────────────┐
│ Contract                                    │
├──────────────────────┬──────────────────────┤
│ Name                 │ core-containers-sbom │
├──────────────────────┼──────────────────────┤
│ Description          │                      │
├──────────────────────┼──────────────────────┤
│ Associated Workflows │ core/containers-sbom │ …
```

fix(contracts): Add missing project eager loading

---

app/controlplane/pkg/data/workflowrun.go

This is a follow up of https://github.com/chainloop-dev/chainloop/pull/2058
This optimization optimizes the query by avoiding a JOIN between workflows and worflow_runs, which is expensive specially in the case when there are no workflows yet (in this case the join just consists of the whole database contents).
The solution is to first query workflows and then workflow runs. Both queries are optimized.
From (note the 2M rows JOIN):
```
Limit  (cost=0.58..15.46 rows=26 width=236) (actual time=767.852..767.854 rows=0 loops=1)
->  Nested Loop Semi Join  (cost=0.58..104130.07 rows=181868 width=236) (actual time=767.850..767.851 rows=0 loops=1)
Join Filter: (workflow_runs.workflow_id = workflows.id)
->  Index Scan using workflow_runs_created_at_index on workflow_runs  (cost=0.43..74112.59 …
```

fix(database): optimize workflow run list query

---

.chainloop.yml

chore: prepare release 1.4.3

---

.chainloop.yml
app/controlplane/pkg/data/workflowrun.go

We want to find a way that works for any number of workflows

chore: rollback query optimization

---

deployment/chainloop/Chart.yaml
deployment/chainloop/templates/controlplane/configmap.yaml

I am reverting back the change I made to make it work with helm 3.18 since it breaks compatibility with 3.17, it might be related to https://github.com/helm/helm/issues/30901
refs #2067

fix(chart): revert back to support Helm <3.18

---

.github/workflows/release.yaml

This patch modifies the release workflow to include the names of the materials being attested. See this example with the latest released version to see the expected output:
Example of successful attestation.
```
Reading from: /Users/javirln/Development/projects/chainloop/artifacts.json
============================================
INF Attestation initialized! now you can check its status or add materials to it
┌───────────────────────────┬────────────────────────────────────────────┐
│ Initialized At            │ 27 May 25 09:08 UTC                        │
├───────────────────────────┼────────────────────────────────────────────┤
│ Attestation ID            │ 4d8d9166-5d5d-496e-92c1-867b77b268ca       │
│ Organization              │ testing …
```

chore(workflows): Include attestation name on release workflow

---

app/controlplane/pkg/biz/signing.go

This patch fixes an issue while rotating TSAs. The signing TSA is not properly detected

fix(tsa): Fix issuer detection when multiple TSAs are configured

---

.chainloop.yml

Increment patch version for release

chore: Prepare release 1.6.1

---

README.md

issue reported here https://github.com/chainloop-dev/chainloop/pull/1998?notification_referrer_id=NT_kwDNX8uxMTYwMzMwNTQ4MDQ6MjQ1MjM#issuecomment-2979752774

fix(docs): update download instructions in readme

---

pkg/attestation/renderer/chainloop/chainloop.go
pkg/attestation/renderer/chainloop/testdata/attestation-pe-snake.json
pkg/attestation/renderer/chainloop/testdata/attestation.output-2.v0.2.json
pkg/attestation/renderer/chainloop/testdata/attestation.output.v0.2.json

feat(attestation): add workflow name to attestation metadata (#1916)

---

app/controlplane/pkg/authz/authz.go

Org members can create and update contracts. This PR adds the Delete action to be consistent with the rest of endpoints.

chore(rbac): Allow org members to delete contracts

---

app/controlplane/internal/service/referrer.go

Follow up to apply project visibility on API tokens.

chore: apply project filters in referrers API with API tokens

---

.chainloop.yml

chore: prepare next release v1.35.0

---

app/controlplane/pkg/auditor/events/project.go

Define a project deletion event, dispatched from platform

chore: define project version deleted
